/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates08 : List A15CentroidRawCertificate :=
[
  { d := #[-52, -8, -8, -8, -8, 0, 0, 0, 0, 0, 0, 8, 8, 12, 28, 28]
    q := #[3, -2, -3, -3, -3, -3, 3, 3, 3, 3, 3, 3, -3, -3, -3, 3, 3]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 2032 },
  { d := #[-52, -8, -8, -8, -4, -4, 4, 4, 4, 4, 4, 4, 4, 4, 12, 40]
    q := #[2, -2, 0, 0, 0, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -2, 2]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 1672 },
  { d := #[-52, -8, -8, -8, -4, 0, 0, 0, 0, 0, 0, 0, 8, 20, 20, 32]
    q := #[4, 1, 1, 1, 1, -4, 4, 4, 4, 4, 4, 4, 4, -4, 4, 4, 4]
    reportedResidue := 0
    reportedEligible := 80
    reportedGap := 2640 },
  { d := #[-52, -8, -8, -8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 12, 20, 36]
    q := #[12, 8, -12, -12, -12, 5, 5, 5, 5, 5, 5, 5, 5, -12, -12, 12, 12]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 4760 },
  { d := #[-52, -8, -8, -8, 0, 0, 0, 0, 0, 0, 0, 4, 4, 8, 28, 32]
    q := #[0, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 352 },
  { d := #[-52, -8, -8, -4, -4, -4, -4, 0, 4, 4, 4, 4, 4, 4, 28, 32]
    q := #[0, -1, 1, 1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, -1, 1]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 400 },
  { d := #[-52, -8, -8, -4, -4, 0, 0, 0, 0, 0, 0, 0, 8, 8, 28, 32]
    q := #[3, -3, 3, 3, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -3, 2]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 1106 },
  { d := #[-52, -8, -8, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 28, 32]
    q := #[0, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1]
    reportedResidue := 0
    reportedEligible := 108
    reportedGap := 616 },
  { d := #[-52, -8, -8, -4, 0, 0, 0, 0, 0, 0, 0, 0, 4, 8, 24, 36]
    q := #[0, -1, 1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, -1, 1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 528 },
  { d := #[-52, -8, -8, -4, 0, 0, 0, 0, 0, 0, 0, 0, 8, 12, 12, 40]
    q := #[2, -2, 2, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0, -2, -1, -1, 2]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1760 }
]

theorem a15GeneratedCentroidCertificates08_length :
    a15GeneratedCentroidCertificates08.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates08_checked :
    a15GeneratedCentroidCertificates08.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
