/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates29 : List A15CentroidRawCertificate :=
[
  { d := #[-44, -8, -8, -4, -4, -4, -4, -4, -4, -4, 8, 8, 8, 8, 8, 48]
    q := #[2, -2, 2, 2, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 2]
    reportedResidue := 0
    reportedEligible := 112
    reportedGap := 1364 },
  { d := #[-44, -8, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, 8, 16, 32, 36]
    q := #[0, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 1144 },
  { d := #[-44, -8, -4, -4, -4, -4, -4, -4, -4, -4, -4, 0, 4, 16, 28, 40]
    q := #[3, -3, 3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, 3, 3, -3, 2]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 3220 },
  { d := #[-40, -28, -28, -8, 4, 4, 4, 4, 4, 4, 4, 4, 12, 16, 16, 28]
    q := #[2, 2, -2, -2, -2, 2, 2, 2, 2, 2, 2, 2, 2, -2, 1, 1, 2]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 1368 },
  { d := #[-40, -28, -28, -4, -4, -4, 0, 0, 12, 12, 12, 12, 12, 12, 12, 24]
    q := #[-2, -1, -2, -2, 2, 2, 2, -2, -2, 1, 1, 1, 1, 1, 1, 1, -2]
    reportedResidue := 0
    reportedEligible := 83
    reportedGap := 1076 },
  { d := #[-40, -28, -28, -4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 24, 28]
    q := #[2, 2, -2, -2, -2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, -2, 1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 1628 },
  { d := #[-40, -28, -28, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 12, 24, 28]
    q := #[4, 1, -4, -4, -4, -4, 4, 4, 4, 4, 4, 4, 4, 4, 4, -4, -1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 3476 },
  { d := #[-40, -28, -28, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 20, 32]
    q := #[0, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1]
    reportedResidue := 0
    reportedEligible := 111
    reportedGap := 744 },
  { d := #[-40, -28, -28, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 36]
    q := #[3, 2, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -3, -3, -3, 3]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 3140 },
  { d := #[-40, -28, -24, -4, -4, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 36]
    q := #[4, -4, -4, -4, 4, 4, 4, 4, -3, -3, -3, -3, -3, -3, -3, -3, 4]
    reportedResidue := 0
    reportedEligible := 89
    reportedGap := 2512 }
]

theorem a15GeneratedCentroidCertificates29_length :
    a15GeneratedCentroidCertificates29.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates29_checked :
    a15GeneratedCentroidCertificates29.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
