/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates52 : List A15CentroidRawCertificate :=
[
  { d := #[-36, -16, -16, -16, -16, -16, 0, 8, 8, 8, 8, 8, 8, 12, 20, 36]
    q := #[0, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 80
    reportedGap := 704 },
  { d := #[-36, -16, -16, -16, -16, -12, -4, 8, 8, 8, 8, 8, 8, 8, 24, 36]
    q := #[4, -4, 1, 1, 1, 1, -4, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4]
    reportedResidue := 0
    reportedEligible := 81
    reportedGap := 2640 },
  { d := #[-36, -16, -16, -16, -12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 12, 48]
    q := #[2, -2, -1, -1, 2, 2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 2, 2]
    reportedResidue := 0
    reportedEligible := 112
    reportedGap := 1496 },
  { d := #[-36, -16, -16, -16, -4, -4, -4, -4, -4, -4, -4, 16, 20, 20, 28, 28]
    q := #[0, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 97
    reportedGap := 704 },
  { d := #[-36, -16, -16, -16, -4, -4, -4, -4, -4, -4, 8, 8, 16, 16, 20, 40]
    q := #[3, -2, -3, -3, -3, 3, 3, 3, 3, 3, 3, -3, -3, -3, -3, 3, 3]
    reportedResidue := 0
    reportedEligible := 83
    reportedGap := 1596 },
  { d := #[-36, -16, -16, -16, 0, 0, 0, 0, 0, 0, 0, 0, 12, 12, 12, 48]
    q := #[1, -1, -1, 0, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 484 },
  { d := #[-36, -16, -16, -12, -12, -12, 4, 4, 4, 4, 4, 4, 8, 8, 20, 44]
    q := #[10, 2, 10, 10, -10, -10, -10, 3, 3, 3, 3, 3, 3, -10, -10, 10, 10]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 5760 },
  { d := #[-36, -16, -16, -12, -12, -4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 48]
    q := #[2, -2, -1, -1, 2, 2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 2, 2]
    reportedResidue := 0
    reportedEligible := 88
    reportedGap := 1848 },
  { d := #[-36, -16, -16, -12, -12, 0, 0, 0, 0, 0, 0, 0, 16, 16, 16, 44]
    q := #[3, -3, -3, -3, 3, 3, -3, -3, -3, -3, -3, -3, -3, 3, 3, 3, -2]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 2296 },
  { d := #[-36, -16, -16, -12, -4, -4, -4, -4, -4, -4, -4, 12, 12, 20, 32, 32]
    q := #[8, 2, -8, -8, -8, 5, 5, 5, 5, 5, 5, 5, -8, -8, -5, 8, 8]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 5720 }
]

theorem a15GeneratedCentroidCertificates52_length :
    a15GeneratedCentroidCertificates52.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates52_checked :
    a15GeneratedCentroidCertificates52.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
