/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates82 : List A15CentroidRawCertificate :=
[
  { d := #[-28, -28, -24, -4, -4, -4, -4, -4, -4, -4, 8, 8, 8, 28, 28, 28]
    q := #[6, -6, -6, -1, 6, 6, 6, 6, 6, 6, 6, -6, -6, -6, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 106
    reportedGap := 2772 },
  { d := #[-28, -28, -24, -4, -4, -4, -4, -4, -4, 8, 8, 8, 12, 12, 12, 44]
    q := #[4, -4, -4, 4, 4, 4, 4, 4, 4, 4, -1, -1, -1, 4, 4, 4, -1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 2068 },
  { d := #[-28, -28, -20, -20, -20, -12, 8, 8, 8, 8, 8, 16, 16, 16, 20, 20]
    q := #[2, -2, -2, -1, 2, -1, -2, 2, 2, 2, 2, 2, -2, -2, -2, 2, 2]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1224 },
  { d := #[-28, -28, -20, -20, -20, 0, 8, 8, 8, 8, 8, 8, 8, 12, 12, 36]
    q := #[8, -8, -8, 5, 5, 5, -8, -5, -5, -5, -5, -5, -5, -5, 8, 8, 8]
    reportedResidue := 0
    reportedEligible := 79
    reportedGap := 5312 },
  { d := #[-28, -28, -20, -20, -20, 4, 4, 8, 8, 8, 8, 8, 8, 8, 16, 36]
    q := #[8, -8, -8, 5, 5, 5, -8, 8, -5, -5, -5, -5, -5, -5, -5, 8, 8]
    reportedResidue := 0
    reportedEligible := 81
    reportedGap := 4608 },
  { d := #[-28, -28, -20, -20, -16, -12, -8, 12, 12, 12, 16, 16, 16, 16, 16, 16]
    q := #[2, -2, -1, -2, -2, -2, -1, 2, 2, 2, 2, -2, -2, -2, -2, -2, -2]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 656 },
  { d := #[-28, -28, -20, -20, -16, 4, 4, 4, 4, 4, 4, 4, 16, 16, 16, 36]
    q := #[0, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 97
    reportedGap := 704 },
  { d := #[-28, -28, -20, -16, -16, -16, 4, 4, 12, 12, 12, 12, 12, 12, 12, 32]
    q := #[3, 3, -2, -3, -3, -3, -3, -3, -3, 3, 3, 3, 3, 3, 3, 3, -3]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 2428 },
  { d := #[-28, -28, -20, -16, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 12, 48]
    q := #[1, -1, -1, -1, 1, 0, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1032 },
  { d := #[-28, -28, -20, -8, -8, -4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 48]
    q := #[1, -1, -1, -1, 0, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1]
    reportedResidue := 0
    reportedEligible := 93
    reportedGap := 406 }
]

theorem a15GeneratedCentroidCertificates82_length :
    a15GeneratedCentroidCertificates82.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates82_checked :
    a15GeneratedCentroidCertificates82.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
