/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates03 : List A15CentroidRawCertificate :=
[
  { d := #[-56, -12, -12, -12, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 20, 24]
    q := #[3, 2, -3, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, -3, -3, 3, 3]
    reportedResidue := 0
    reportedEligible := 88
    reportedGap := 2380 },
  { d := #[-56, -12, -12, -8, 0, 4, 4, 4, 4, 4, 4, 4, 4, 12, 16, 28]
    q := #[3, -3, 3, 3, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, -3, 2, 3]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 2200 },
  { d := #[-56, -12, -12, -8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 24, 24]
    q := #[3, 2, 3, 3, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 1804 },
  { d := #[-56, -8, -8, -8, -8, -8, -8, 4, 12, 12, 12, 12, 12, 12, 12, 16]
    q := #[0, 1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 105
    reportedGap := 616 },
  { d := #[-56, -8, -8, -8, -8, -8, 0, 4, 4, 4, 12, 12, 12, 12, 12, 24]
    q := #[1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, 0]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 384 },
  { d := #[-56, -8, -8, -8, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 24, 28]
    q := #[2, -2, 2, 2, 1, 2, 2, 2, -2, -2, -2, -2, -2, -2, -2, 1, 2]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 1244 },
  { d := #[-56, -8, -4, -4, -4, -4, -4, 4, 4, 4, 4, 4, 4, 8, 24, 28]
    q := #[2, -2, -2, 2, 2, 2, 2, 2, -2, -2, -2, -2, -2, -2, 1, 1, 2]
    reportedResidue := 0
    reportedEligible := 80
    reportedGap := 1788 },
  { d := #[-56, -8, -4, -4, -4, 0, 0, 0, 0, 0, 0, 0, 16, 16, 16, 28]
    q := #[1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 0, 1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 748 },
  { d := #[-56, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4, 4, 16, 16, 20, 24]
    q := #[1, 0, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, 1]
    reportedResidue := 0
    reportedEligible := 87
    reportedGap := 782 },
  { d := #[-56, -4, -4, -4, -4, -4, -4, -4, 4, 4, 4, 4, 8, 8, 24, 28]
    q := #[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 376 }
]

theorem a15GeneratedCentroidCertificates03_length :
    a15GeneratedCentroidCertificates03.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates03_checked :
    a15GeneratedCentroidCertificates03.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
