/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates198 : List A15CentroidRawCertificate :=
[
  { d := #[-26, -26, -26, -26, -18, -2, 10, 10, 10, 10, 10, 10, 10, 14, 14, 26]
    q := #[0, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1]
    reportedResidue := 2
    reportedEligible := 84
    reportedGap := 1144 },
  { d := #[-26, -26, -26, -26, -18, 6, 6, 10, 10, 10, 10, 10, 10, 10, 10, 30]
    q := #[-4, -4, -4, -4, -4, 4, -4, 4, 1, 1, 1, 1, 1, 1, 1, 1, -4]
    reportedResidue := 2
    reportedEligible := 104
    reportedGap := 2464 },
  { d := #[-26, -26, -26, -26, -14, -6, 6, 6, 6, 6, 10, 18, 18, 18, 18, 18]
    q := #[8, -8, -8, -8, -8, 5, -8, 8, 8, 8, 8, 8, -5, -5, -5, -5, -5]
    reportedResidue := 2
    reportedEligible := 84
    reportedGap := 2472 },
  { d := #[-26, -26, -26, -26, -14, 6, 6, 6, 6, 6, 6, 6, 10, 18, 18, 30]
    q := #[0, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 92
    reportedGap := 704 },
  { d := #[-26, -26, -26, -26, -14, 6, 6, 6, 6, 10, 10, 10, 10, 10, 10, 34]
    q := #[0, -1, -1, -1, -1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, -1]
    reportedResidue := 2
    reportedEligible := 84
    reportedGap := 880 },
  { d := #[-26, -26, -26, -26, -6, -6, -2, -2, 6, 6, 18, 18, 18, 18, 18, 18]
    q := #[4, 1, 1, 1, 1, 4, 4, 4, 4, -4, -4, 4, 4, 4, 4, 4, 4]
    reportedResidue := 2
    reportedEligible := 88
    reportedGap := 2392 },
  { d := #[-26, -26, -26, -22, -22, -6, 6, 6, 14, 14, 14, 14, 14, 14, 14, 18]
    q := #[0, 1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 78
    reportedGap := 704 },
  { d := #[-26, -26, -26, -22, -22, -2, -2, 10, 14, 14, 14, 14, 14, 14, 14, 18]
    q := #[5, 4, 4, 4, -5, -5, -5, -5, 5, 5, 5, 5, 5, 5, 5, 5, -5]
    reportedResidue := 2
    reportedEligible := 81
    reportedGap := 3032 },
  { d := #[-26, -26, -26, -22, -22, 2, 10, 10, 10, 10, 10, 10, 10, 10, 10, 30]
    q := #[0, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 111
    reportedGap := 1056 },
  { d := #[-26, -26, -26, -22, -18, -6, -6, 14, 14, 14, 14, 14, 14, 14, 14, 18]
    q := #[-1, 0, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 84
    reportedGap := 916 }
]

theorem a15GeneratedCentroidCertificates198_length :
    a15GeneratedCentroidCertificates198.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates198_checked :
    a15GeneratedCentroidCertificates198.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
