/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates96 : List A15CentroidRawCertificate :=
[
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, -4, 0, 12, 20, 20, 20, 20, 32]
    q := #[12, -12, -12, 5, 5, 5, 5, 5, 5, -12, 12, 12, -5, -5, -5, -5, 2]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 2712 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, -4, 4, 8, 16, 16, 24, 24, 32]
    q := #[2, -2, -2, 2, 2, 2, 2, 2, 2, -2, -2, 2, 1, 1, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1012 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, 0, 4, 4, 12, 16, 28, 28, 28]
    q := #[2, -2, -2, 1, 1, 1, 1, 1, 1, -2, -2, -2, 2, -2, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 1112 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, 0, 4, 4, 16, 20, 20, 20, 36]
    q := #[2, -2, -2, 1, 1, 1, 1, 1, 1, -2, -2, -2, -2, 2, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 1160 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, 0, 4, 12, 16, 16, 16, 16, 40]
    q := #[0, -1, -1, 0, 0, 0, 0, 0, 0, 1, -1, 1, -1, -1, -1, -1, 1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 304 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, 0, 8, 8, 8, 12, 20, 32, 32]
    q := #[2, -2, -2, 1, 1, 1, 1, 1, 1, -2, -2, -2, -2, 2, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 1112 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -12, 0, 8, 8, 8, 16, 16, 28, 36]
    q := #[2, -2, -2, 1, 1, 1, 1, 1, 1, -2, -2, -2, -2, 2, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 1160 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -8, 0, 0, 0, 16, 16, 28, 28, 28]
    q := #[3, 2, -3, -3, -3, -3, -3, -3, -3, 3, 3, 3, -3, -3, 3, 3, 3]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 1410 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, -4, -4, -4, 0, 24, 24, 24, 24, 24]
    q := #[1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 346 },
  { d := #[-24, -24, -12, -12, -12, -12, -12, 0, 0, 0, 8, 8, 8, 20, 20, 44]
    q := #[3, 2, -3, -3, -3, -3, -3, -3, 3, 3, 3, -3, -3, -3, 3, 3, 3]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 1410 }
]

theorem a15GeneratedCentroidCertificates96_length :
    a15GeneratedCentroidCertificates96.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates96_checked :
    a15GeneratedCentroidCertificates96.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
