/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates86 : List A15CentroidRawCertificate :=
[
  { d := #[-28, -24, -20, -16, -16, -8, -8, 0, 0, 0, 20, 20, 20, 20, 20, 20]
    q := #[2, -2, 2, -2, 2, 2, 2, 2, -2, -2, -2, 1, 1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 80
    reportedGap := 872 },
  { d := #[-28, -24, -20, -16, -12, 4, 4, 4, 4, 4, 4, 4, 4, 8, 12, 48]
    q := #[1, -1, -1, -1, 0, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1078 },
  { d := #[-28, -24, -16, -16, -16, -16, -4, 0, 0, 0, 20, 20, 20, 20, 20, 20]
    q := #[6, 6, -6, 6, 6, 6, 6, 6, -6, -6, -6, 5, 5, 5, 5, 5, 5]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 3168 },
  { d := #[-28, -24, -16, -16, -16, -4, -4, -4, -4, 8, 8, 8, 8, 28, 28, 28]
    q := #[5, -5, 5, 4, 4, 4, -5, -5, -5, -5, 5, 5, 5, 5, 5, 5, 5]
    reportedResidue := 0
    reportedEligible := 79
    reportedGap := 2406 },
  { d := #[-28, -24, -16, -12, -12, -8, 4, 4, 4, 4, 4, 4, 4, 4, 20, 48]
    q := #[4, -3, 4, -4, -4, -4, 4, -4, -4, -4, -4, -4, -4, -4, -4, 4, 3]
    reportedResidue := 0
    reportedEligible := 91
    reportedGap := 1676 },
  { d := #[-28, -24, -16, -8, -8, -8, -8, -8, -8, 12, 12, 12, 12, 12, 12, 44]
    q := #[0, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 105
    reportedGap := 616 },
  { d := #[-28, -24, -16, -4, -4, -4, -4, -4, -4, -4, -4, -4, 16, 20, 28, 40]
    q := #[3, -2, 3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, 3, 3, -3, 3]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 2476 },
  { d := #[-28, -24, -16, -4, -4, -4, -4, -4, -4, -4, 0, 0, 0, 32, 32, 32]
    q := #[3, -3, 2, -3, 3, 3, 3, 3, 3, 3, 3, -3, -3, -3, 3, 3, 3]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 1938 },
  { d := #[-28, -24, -16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 56]
    q := #[1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 0]
    reportedResidue := 0
    reportedEligible := 108
    reportedGap := 484 },
  { d := #[-28, -24, -12, -12, -12, -12, -12, 4, 4, 4, 4, 4, 8, 16, 32, 36]
    q := #[0, -1, 1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, -1]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 432 }
]

theorem a15GeneratedCentroidCertificates86_length :
    a15GeneratedCentroidCertificates86.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates86_checked :
    a15GeneratedCentroidCertificates86.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
