/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates53 : List A15CentroidRawCertificate :=
[
  { d := #[-36, -16, -16, -12, -4, -4, -4, -4, -4, 8, 8, 8, 8, 8, 12, 48]
    q := #[7, -7, 3, 3, -7, -2, -2, -2, -2, -2, -7, -7, -7, -7, -7, 7, 7]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 4660 },
  { d := #[-36, -16, -16, -8, -8, -8, -8, -8, 0, 4, 12, 12, 12, 12, 12, 44]
    q := #[2, -2, -2, -2, -2, -2, -2, -2, -2, 2, 2, -1, -1, -1, -1, -1, -1]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 860 },
  { d := #[-36, -16, -16, -8, -4, -4, -4, -4, -4, -4, -4, 12, 12, 12, 28, 40]
    q := #[4, -1, 4, 4, -4, -4, -4, -4, -4, -4, -4, -4, 0, 0, 0, 4, -3]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 1364 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, -4, -4, 16, 28, 28, 32]
    q := #[2, 2, -1, -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 2136 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, -4, 0, 12, 20, 32, 36]
    q := #[4, 1, 4, 4, -4, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4, -1, 4]
    reportedResidue := 0
    reportedEligible := 92
    reportedGap := 2356 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4, 28, 32, 32]
    q := #[6, -4, 6, 6, -5, -5, -5, -5, -5, -5, -5, -5, -6, -6, -6, 6, 6]
    reportedResidue := 0
    reportedEligible := 88
    reportedGap := 4400 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, -4, 4, 8, 20, 28, 40]
    q := #[4, 1, 4, 4, -4, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4, -1, 4]
    reportedResidue := 0
    reportedEligible := 96
    reportedGap := 2032 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, -4, 4, 16, 16, 20, 44]
    q := #[3, 2, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, 3, 3]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 2364 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, -4, 8, 12, 12, 24, 44]
    q := #[4, 1, 4, 4, -4, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4, -1, 4]
    reportedResidue := 0
    reportedEligible := 103
    reportedGap := 1708 },
  { d := #[-36, -16, -16, -4, -4, -4, -4, -4, -4, -4, 0, 0, 12, 20, 20, 44]
    q := #[2, 2, -1, -1, 2, 2, 2, 2, 2, 2, 2, -2, -2, 2, 2, 2, 2]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1448 }
]

theorem a15GeneratedCentroidCertificates53_length :
    a15GeneratedCentroidCertificates53.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates53_checked :
    a15GeneratedCentroidCertificates53.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
