/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates77 : List A15CentroidRawCertificate :=
[
  { d := #[-32, -12, -12, -12, -12, -12, -12, -12, -4, -4, 16, 16, 16, 20, 28, 28]
    q := #[3, 3, -3, -3, -3, -3, -3, -3, -3, 3, 3, 3, 3, 3, 3, -3, 2]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 2428 },
  { d := #[-32, -12, -12, -12, -12, -12, -12, -4, -4, -4, 0, 16, 16, 28, 28, 28]
    q := #[1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 0, -1, -1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 884 },
  { d := #[-32, -12, -12, -12, -12, -12, -8, -8, -4, -4, -4, 24, 24, 24, 24, 24]
    q := #[6, 6, -6, -6, -6, -6, -6, -6, 1, 6, 6, 6, 1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 85
    reportedGap := 3836 },
  { d := #[-32, -12, -12, -12, -12, -12, -4, -4, -4, -4, -4, 12, 16, 16, 32, 36]
    q := #[1, 1, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 786 },
  { d := #[-32, -12, -12, -12, -12, -12, -4, -4, -4, -4, 0, 8, 8, 28, 28, 36]
    q := #[0, 1, -1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 77
    reportedGap := 536 },
  { d := #[-32, -12, -12, -12, -12, -12, -4, -4, -4, 0, 8, 8, 8, 16, 16, 48]
    q := #[3, 2, -3, -3, -3, -3, -3, 3, 3, 3, -3, -3, -3, -3, 3, 3, 3]
    reportedResidue := 0
    reportedEligible := 75
    reportedGap := 1606 },
  { d := #[-32, -12, -12, -12, -12, -8, -8, -8, -8, -8, 0, 24, 24, 24, 24, 24]
    q := #[0, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 80
    reportedGap := 1056 },
  { d := #[-32, -12, -12, -12, -12, -8, -8, -8, -8, -8, 16, 16, 16, 16, 16, 40]
    q := #[0, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 80
    reportedGap := 1056 },
  { d := #[-32, -12, -12, -12, -8, -8, -8, -8, 0, 8, 8, 8, 8, 8, 8, 52]
    q := #[1, -1, 1, 1, 0, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 524 },
  { d := #[-32, -12, -12, -8, -8, -8, -8, -8, -8, -8, -8, 16, 24, 24, 28, 28]
    q := #[3, 2, 3, 3, -3, -3, -3, -3, -3, -3, -3, -3, -3, 3, 3, 3, 3]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 3016 }
]

theorem a15GeneratedCentroidCertificates77_length :
    a15GeneratedCentroidCertificates77.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates77_checked :
    a15GeneratedCentroidCertificates77.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
