/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates151 : List A15CentroidRawCertificate :=
[
  { d := #[-38, -26, -26, -2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 18, 22, 34]
    q := #[0, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1]
    reportedResidue := 2
    reportedEligible := 108
    reportedGap := 704 },
  { d := #[-38, -26, -26, -2, 2, 2, 2, 2, 2, 2, 2, 2, 10, 10, 18, 38]
    q := #[2, 2, -2, -2, -2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, -2, 1]
    reportedResidue := 2
    reportedEligible := 92
    reportedGap := 1208 },
  { d := #[-38, -26, -26, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 14, 18, 38]
    q := #[0, 1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 1]
    reportedResidue := 2
    reportedEligible := 135
    reportedGap := 528 },
  { d := #[-38, -26, -22, -14, -10, -10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 30]
    q := #[0, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 103
    reportedGap := 1032 },
  { d := #[-38, -26, -22, -14, -10, 2, 2, 2, 2, 2, 14, 14, 14, 14, 14, 30]
    q := #[0, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 80
    reportedGap := 632 },
  { d := #[-38, -26, -22, -14, 2, 2, 2, 2, 2, 2, 2, 2, 14, 14, 26, 30]
    q := #[3, -3, 3, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, -3]
    reportedResidue := 2
    reportedEligible := 75
    reportedGap := 2000 },
  { d := #[-38, -26, -22, -10, -2, 2, 6, 6, 6, 6, 6, 6, 6, 6, 6, 42]
    q := #[12, -12, -12, -12, 12, 12, 12, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3]
    reportedResidue := 2
    reportedEligible := 95
    reportedGap := 9288 },
  { d := #[-38, -26, -22, -6, -2, 2, 2, 2, 2, 2, 2, 2, 2, 22, 22, 34]
    q := #[0, -1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 2
    reportedEligible := 92
    reportedGap := 512 },
  { d := #[-38, -26, -22, -6, -2, 2, 2, 2, 2, 2, 2, 2, 6, 18, 18, 38]
    q := #[3, -3, -3, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -3, -3, -2]
    reportedResidue := 2
    reportedEligible := 74
    reportedGap := 1294 },
  { d := #[-38, -26, -22, -2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 14, 14, 42]
    q := #[4, -3, 4, -4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, -4, -4, 3]
    reportedResidue := 2
    reportedEligible := 117
    reportedGap := 1952 }
]

theorem a15GeneratedCentroidCertificates151_length :
    a15GeneratedCentroidCertificates151.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates151_checked :
    a15GeneratedCentroidCertificates151.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
