/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates69 : List A15CentroidRawCertificate :=
[
  { d := #[-32, -28, -8, -4, -4, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 52]
    q := #[0, -1, 1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 352 },
  { d := #[-32, -28, -8, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 12, 52]
    q := #[3, -2, 3, -3, -3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -3, 3, 3]
    reportedResidue := 0
    reportedEligible := 82
    reportedGap := 2270 },
  { d := #[-32, -28, -4, -4, -4, -4, -4, -4, 0, 4, 4, 4, 4, 8, 8, 52]
    q := #[0, -1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, -1, -1, 1]
    reportedResidue := 0
    reportedEligible := 78
    reportedGap := 400 },
  { d := #[-32, -24, -24, -20, -20, 8, 8, 8, 8, 8, 8, 8, 8, 12, 12, 32]
    q := #[1, -1, -1, 0, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 968 },
  { d := #[-32, -24, -24, -20, -16, 4, 8, 8, 8, 8, 8, 8, 8, 8, 12, 36]
    q := #[4, -4, -4, -4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, -4]
    reportedResidue := 0
    reportedEligible := 83
    reportedGap := 2836 },
  { d := #[-32, -24, -24, -20, -12, -12, 8, 8, 8, 8, 8, 8, 16, 16, 16, 28]
    q := #[0, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 81
    reportedGap := 448 },
  { d := #[-32, -24, -24, -20, -12, -4, 8, 8, 8, 8, 8, 8, 8, 8, 16, 36]
    q := #[2, -2, -2, -2, -2, 2, 1, -2, -2, -2, -2, -2, -2, -2, -2, 2, 1]
    reportedResidue := 0
    reportedEligible := 84
    reportedGap := 1288 },
  { d := #[-32, -24, -24, -16, -16, -16, 4, 12, 12, 12, 12, 12, 12, 12, 16, 24]
    q := #[-5, 5, -5, -5, -5, -5, -5, 5, 2, 2, 2, 2, 2, 2, 2, 5, -5]
    reportedResidue := 0
    reportedEligible := 83
    reportedGap := 2986 },
  { d := #[-32, -24, -24, -16, -16, -8, -4, 4, 12, 12, 12, 12, 12, 12, 24, 24]
    q := #[2, -2, -2, -2, -1, -1, -2, 2, 2, -2, -2, -2, -2, -2, -2, 2, 2]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 1012 },
  { d := #[-32, -24, -24, -12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 48]
    q := #[0, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 165
    reportedGap := 704 }
]

theorem a15GeneratedCentroidCertificates69_length :
    a15GeneratedCentroidCertificates69.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates69_checked :
    a15GeneratedCentroidCertificates69.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
