/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates195 : List A15CentroidRawCertificate :=
[
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -10, 10, 14, 14, 14, 34, 34]
    q := #[1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1]
    reportedResidue := 2
    reportedEligible := 84
    reportedGap := 1210 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -10, 14, 14, 14, 18, 18, 42]
    q := #[0, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1]
    reportedResidue := 2
    reportedEligible := 113
    reportedGap := 1056 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, -6, 18, 26, 26, 26, 26]
    q := #[-4, 4, -1, -1, -1, -1, -1, -1, -1, -1, -4, 4, -4, 4, 4, 4, 4]
    reportedResidue := 2
    reportedEligible := 104
    reportedGap := 2464 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, -6, 22, 22, 22, 26, 30]
    q := #[2, 2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 1, 1, -2, 2]
    reportedResidue := 2
    reportedEligible := 82
    reportedGap := 1532 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, -2, 14, 18, 22, 30, 34]
    q := #[1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, 1, 1]
    reportedResidue := 2
    reportedEligible := 75
    reportedGap := 932 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, 2, 10, 18, 18, 34, 34]
    q := #[4, 4, -3, -3, -3, -3, -3, -3, -3, -3, -4, -4, 4, -4, -4, 4, 4]
    reportedResidue := 2
    reportedEligible := 80
    reportedGap := 3456 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, 2, 14, 14, 18, 30, 38]
    q := #[1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, 1, 1]
    reportedResidue := 2
    reportedEligible := 82
    reportedGap := 742 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, 6, 6, 14, 22, 34, 34]
    q := #[1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, 1, 1]
    reportedResidue := 2
    reportedEligible := 75
    reportedGap := 936 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, 6, 6, 14, 26, 26, 38]
    q := #[4, 4, -1, -1, -1, -1, -1, -1, -1, -1, -4, -4, -4, 4, 4, 4, 4]
    reportedResidue := 2
    reportedEligible := 90
    reportedGap := 2904 },
  { d := #[-30, -10, -10, -10, -10, -10, -10, -10, -10, -6, 6, 10, 10, 22, 30, 38]
    q := #[1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, 1, 1]
    reportedResidue := 2
    reportedEligible := 74
    reportedGap := 954 }
]

theorem a15GeneratedCentroidCertificates195_length :
    a15GeneratedCentroidCertificates195.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates195_checked :
    a15GeneratedCentroidCertificates195.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
