/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15FarkasKernel

/-!
# Generated A15 centroid separator data chunk

The declarations in this chunk contain exact integer data only. Lean checks
the profile invariants, eligible four-subsets, and separator gaps with the
bounded choose-four kernel checker.
-/

namespace SRG266

set_option maxRecDepth 100000 in
def a15GeneratedCentroidCertificates97 : List A15CentroidRawCertificate :=
[
  { d := #[-24, -24, -12, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, 32, 32, 36]
    q := #[-2, -2, -2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, 2, -2]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 1408 },
  { d := #[-24, -24, -12, -4, -4, -4, -4, -4, -4, -4, -4, -4, 12, 16, 16, 52]
    q := #[1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 0]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 792 },
  { d := #[-24, -24, -8, -8, -8, -4, -4, -4, -4, -4, -4, -4, 0, 32, 32, 36]
    q := #[4, -4, 1, 4, 4, 4, -4, -4, -4, -4, -4, -4, -4, -4, 4, 4, -1]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 3272 },
  { d := #[-24, -24, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, 8, 12, 12, 56]
    q := #[3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, 3, -3, -3, -2]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 1804 },
  { d := #[-24, -24, -4, -4, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60]
    q := #[0, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1]
    reportedResidue := 0
    reportedEligible := 120
    reportedGap := 1056 },
  { d := #[-24, -20, -20, -20, -20, -20, 0, 4, 4, 4, 16, 16, 16, 16, 24, 24]
    q := #[1, 1, -1, -1, -1, -1, -1, 1, 0, 0, 0, -1, -1, -1, -1, 1, 1]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 544 },
  { d := #[-24, -20, -20, -20, -20, -8, 4, 4, 4, 4, 4, 4, 4, 20, 32, 32]
    q := #[4, 4, 1, 1, 1, 1, -4, 4, 4, 4, 4, 4, 4, 4, -4, 4, 4]
    reportedResidue := 0
    reportedEligible := 92
    reportedGap := 2464 },
  { d := #[-24, -20, -20, -16, -8, -8, -8, -8, -8, -8, 20, 20, 20, 20, 20, 28]
    q := #[0, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1]
    reportedResidue := 0
    reportedEligible := 90
    reportedGap := 792 },
  { d := #[-24, -20, -20, -12, -8, -8, -8, -8, -8, -8, 12, 12, 16, 28, 28, 28]
    q := #[5, 4, 4, 4, -5, -5, -5, -5, -5, -5, -5, -5, -5, 5, 5, 5, 5]
    reportedResidue := 0
    reportedEligible := 76
    reportedGap := 3016 },
  { d := #[-24, -20, -20, -8, -8, -8, -8, -8, -8, -8, 0, 16, 24, 24, 28, 28]
    q := #[-1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1]
    reportedResidue := 0
    reportedEligible := 74
    reportedGap := 838 }
]

theorem a15GeneratedCentroidCertificates97_length :
    a15GeneratedCentroidCertificates97.length = 10 := by
  rfl

set_option maxRecDepth 100000 in
theorem a15GeneratedCentroidCertificates97_checked :
    a15GeneratedCentroidCertificates97.all A15CentroidRawCertificate.fastCheck = true := by
  decide +kernel

end SRG266
