/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_e7_four_eight_generic.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7FourEightGenericBaseData

namespace SRG266
namespace E7FourEightGenericData

set_option maxRecDepth 100000

theorem class1_inner_two_closed_checked_block_04
    (i : Class1Index) (w : Shell) (hi : 64 ≤ i.1 ∧ i.1 < 80)
    (h : e7ShellInner (class1Vertex i).1 w.1 = 2) :
    e7ResidualEvaluation d₄ w.1.1 = 1 := by
  decide +kernel +revert

end E7FourEightGenericData
end SRG266
