/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_projector_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15ProjectorData.Profile12
import SRG266.Hosts.A15QuickBridge

import SRG266.Certificates.A15ProjectorAudit.Profile12Members00
import SRG266.Certificates.A15ProjectorAudit.Profile12Members01
import SRG266.Certificates.A15ProjectorAudit.Profile12Members02
import SRG266.Certificates.A15ProjectorAudit.Profile12Members03
import SRG266.Certificates.A15ProjectorAudit.Profile12Members04
import SRG266.Certificates.A15ProjectorAudit.Profile12Members05
import SRG266.Certificates.A15ProjectorAudit.Profile12Members06
import SRG266.Certificates.A15ProjectorAudit.Profile12Members07
import SRG266.Certificates.A15ProjectorAudit.Profile12Members08
import SRG266.Certificates.A15ProjectorAudit.Profile12Members09
import SRG266.Certificates.A15ProjectorAudit.Profile12Members10
import SRG266.Certificates.A15ProjectorAudit.Profile12Members11

/-!
# Assembled A15 projector profile audit

The negative witnesses are imported from bounded five-record audit modules.
The survivor and affine-cover checks are evaluated separately here.
-/

namespace SRG266

set_option maxRecDepth 100000 in
theorem a15ProjectorProfile12_tail_checked :
    (a15ProjectorProfile12.survivors.all (fun totals =>
        decide (a15ProjectorProfile12.profile.orbitTotalsValid totals)) &&
      a15ProjectorProfile12.cover.check a15ProjectorProfile12.profile a15ProjectorProfile12.listedTotals) = true := by
  unfold a15ProjectorProfile12
  decide +kernel

set_option maxRecDepth 100000 in
theorem a15ProjectorProfile12_membershipBase_checked :
    decide a15ProjectorProfile12BridgeCertificate.BaseValid = true := by
  unfold a15ProjectorProfile12BridgeCertificate a15ProjectorProfile12
  decide +kernel

set_option maxRecDepth 100000 in
theorem a15ProjectorProfile12_bridgeStatic_checked :
    decide a15ProjectorProfile12.profile.bridgeStaticValid = true := by
  unfold a15ProjectorProfile12
  decide +kernel

theorem a15ProjectorProfile12_membership_valid :
    a15ProjectorProfile12BridgeCertificate.Valid := by
  apply a15ProjectorProfile12BridgeCertificate.valid_of_checks
  · exact a15ProjectorProfile12_membershipBase_checked
  · rw [a15ProjectorProfile12BridgeCertificate_entries]
    simp only [List.all_append, a15ProjectorProfile12BridgeEntries00_checked, a15ProjectorProfile12BridgeEntries01_checked, a15ProjectorProfile12BridgeEntries02_checked, a15ProjectorProfile12BridgeEntries03_checked, a15ProjectorProfile12BridgeEntries04_checked, a15ProjectorProfile12BridgeEntries05_checked, a15ProjectorProfile12BridgeEntries06_checked, a15ProjectorProfile12BridgeEntries07_checked, a15ProjectorProfile12BridgeEntries08_checked, a15ProjectorProfile12BridgeEntries09_checked, a15ProjectorProfile12BridgeEntries10_checked, a15ProjectorProfile12BridgeEntries11_checked, Bool.true_and]

theorem a15ProjectorProfile12_membership_checked :
    a15ProjectorProfile12BridgeCertificate.check = true := by
  exact decide_eq_true a15ProjectorProfile12_membership_valid

theorem a15ProjectorProfile12_checked : a15ProjectorProfile12.essentialCheck = true := by
  have hrejections :
      a15ProjectorProfile12.rejections.all
        (A15ProjectorRejection.check a15ProjectorProfile12.profile) = true := by
    rw [a15ProjectorProfile12_rejections]
    rw [Array.all_eq_true_iff_forall_mem]
    simp
  have htail := a15ProjectorProfile12_tail_checked
  simpa only [A15ProjectorProfileCertificate.essentialCheck,
    hrejections, Bool.true_and] using htail

theorem a15ProjectorProfile12_quickBridge_checked :
    a15ProjectorProfile12.rejections.all (fun rejection =>
      A15ProjectorWitness.quickCheckBridge a15ProjectorProfile12.profile
        rejection.witness) = true := by
  rw [a15ProjectorProfile12_rejections]
  rw [Array.all_eq_true_iff_forall_mem]
  simp


end SRG266
