/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_projector_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15ProjectorData.Profile04
import SRG266.Hosts.A15QuickBridge
import SRG266.Certificates.A15ProjectorAudit.Profile04Chunk00
import SRG266.Certificates.A15ProjectorAudit.Profile04Chunk01
import SRG266.Certificates.A15ProjectorAudit.Profile04Members00
import SRG266.Certificates.A15ProjectorAudit.Profile04Members01
import SRG266.Certificates.A15ProjectorAudit.Profile04Members02
import SRG266.Certificates.A15ProjectorAudit.Profile04Members03
import SRG266.Certificates.A15ProjectorAudit.Profile04Members04
import SRG266.Certificates.A15ProjectorAudit.Profile04Members05
import SRG266.Certificates.A15ProjectorAudit.Profile04Members06
import SRG266.Certificates.A15ProjectorAudit.Profile04Members07
import SRG266.Certificates.A15ProjectorAudit.Profile04Members08
import SRG266.Certificates.A15ProjectorAudit.Profile04Members09

/-!
# Assembled A15 projector profile audit

The negative witnesses are imported from bounded five-record audit modules.
The survivor and affine-cover checks are evaluated separately here.
-/

namespace SRG266

set_option maxRecDepth 100000 in
theorem a15ProjectorProfile04_tail_checked :
    (a15ProjectorProfile04.survivors.all (fun totals =>
        decide (a15ProjectorProfile04.profile.orbitTotalsValid totals)) &&
      a15ProjectorProfile04.cover.check a15ProjectorProfile04.profile a15ProjectorProfile04.listedTotals) = true := by
  unfold a15ProjectorProfile04
  decide +kernel

set_option maxRecDepth 100000 in
theorem a15ProjectorProfile04_membershipBase_checked :
    decide a15ProjectorProfile04BridgeCertificate.BaseValid = true := by
  unfold a15ProjectorProfile04BridgeCertificate a15ProjectorProfile04
  decide +kernel

set_option maxRecDepth 100000 in
theorem a15ProjectorProfile04_bridgeStatic_checked :
    decide a15ProjectorProfile04.profile.bridgeStaticValid = true := by
  unfold a15ProjectorProfile04
  decide +kernel

theorem a15ProjectorProfile04_membership_valid :
    a15ProjectorProfile04BridgeCertificate.Valid := by
  apply a15ProjectorProfile04BridgeCertificate.valid_of_checks
  · exact a15ProjectorProfile04_membershipBase_checked
  · rw [a15ProjectorProfile04BridgeCertificate_entries]
    simp only [List.all_append, a15ProjectorProfile04BridgeEntries00_checked, a15ProjectorProfile04BridgeEntries01_checked, a15ProjectorProfile04BridgeEntries02_checked, a15ProjectorProfile04BridgeEntries03_checked, a15ProjectorProfile04BridgeEntries04_checked, a15ProjectorProfile04BridgeEntries05_checked, a15ProjectorProfile04BridgeEntries06_checked, a15ProjectorProfile04BridgeEntries07_checked, a15ProjectorProfile04BridgeEntries08_checked, a15ProjectorProfile04BridgeEntries09_checked, Bool.true_and]

theorem a15ProjectorProfile04_membership_checked :
    a15ProjectorProfile04BridgeCertificate.check = true := by
  exact decide_eq_true a15ProjectorProfile04_membership_valid

theorem a15ProjectorProfile04_checked : a15ProjectorProfile04.essentialCheck = true := by
  have hrejections :
      a15ProjectorProfile04.rejections.all
        (A15ProjectorRejection.check a15ProjectorProfile04.profile) = true := by
    rw [a15ProjectorProfile04_rejections]
    rw [Array.all_eq_true_iff_forall_mem]
    intro rejection hrejection
    have hall : (a15ProjectorProfile04Rejections00 ++
      a15ProjectorProfile04Rejections01).all
        (A15ProjectorRejection.check a15ProjectorProfile04.profile) = true := by
      simp only [List.all_append, a15ProjectorProfile04Rejections00_checked, a15ProjectorProfile04Rejections01_checked, Bool.true_and]
    apply (List.all_eq_true.mp hall) rejection
    simpa using hrejection
  have htail := a15ProjectorProfile04_tail_checked
  simpa only [A15ProjectorProfileCertificate.essentialCheck,
    hrejections, Bool.true_and] using htail

theorem a15ProjectorProfile04_quickBridge_checked :
    a15ProjectorProfile04.rejections.all (fun rejection =>
      A15ProjectorWitness.quickCheckBridge a15ProjectorProfile04.profile
        rejection.witness) = true := by
  rw [a15ProjectorProfile04_rejections]
  rw [Array.all_eq_true_iff_forall_mem]
  intro rejection hrejection
  have hall : (a15ProjectorProfile04Rejections00 ++
      a15ProjectorProfile04Rejections01).all (fun rejection =>
      A15ProjectorWitness.quickCheckBridge a15ProjectorProfile04.profile
        rejection.witness) = true := by
    simp only [List.all_append, a15ProjectorProfile04Rejections00_quickBridge_checked, a15ProjectorProfile04Rejections01_quickBridge_checked, Bool.true_and]
  apply (List.all_eq_true.mp hall) rejection
  simpa using hrejection


end SRG266
