/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicPrefixLRAT.Part260

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

/-- Complete low-memory cubic cover for original orbit group 15. -/
theorem cubicPrefixGroupCovered0F :
    CubicWitnessPrefixCovered cubicOrbitWitnesses0F 4 15 := by
  exact cubicPrefixCoveredB04P00F

end SRG266.Certificates
