/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB07P074
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB07P074 : Sat.Fmla :=
  exactCountCoverChunkFmla 28 7 116 cubic8Constraints
    (cubicPrefixWitnessesB07P074.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB07P074 cubicPrefixFmlaB07P074
  (include_str "../../../certificates/root_cubic_prefix/B07P074.lrat")

theorem cubicPrefixCoveredB07P074 :
    CubicWitnessPrefixCovered cubicOrbitWitnesses04
      7 116 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB07P074
  · exact cubicPrefixUnsatB07P074

end SRG266.Certificates
