/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB09P0D2
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB09P0D2 : Sat.Fmla :=
  exactCountCoverChunkFmla 28 9 210 cubic8Constraints
    (cubicPrefixWitnessesB09P0D2.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB09P0D2 cubicPrefixFmlaB09P0D2
  (include_str "../../../certificates/root_cubic_prefix/B09P0D2.lrat")

theorem cubicPrefixCoveredB09P0D2 :
    CubicWitnessPrefixCovered cubicOrbitWitnesses02
      9 210 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB09P0D2
  · exact cubicPrefixUnsatB09P0D2

end SRG266.Certificates
