/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB09P0AA
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB09P0AA : Sat.Fmla :=
  exactCountCoverChunkFmla 28 9 170 cubic8Constraints
    (cubicPrefixWitnessesB09P0AA.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB09P0AA cubicPrefixFmlaB09P0AA
  (include_str "../../../certificates/root_cubic_prefix/B09P0AA.lrat")

theorem cubicPrefixCoveredB09P0AA :
    CubicWitnessPrefixCovered cubicOrbitWitnesses0A
      9 170 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB09P0AA
  · exact cubicPrefixUnsatB09P0AA

end SRG266.Certificates
