/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB09P0CA
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB09P0CA : Sat.Fmla :=
  exactCountCoverChunkFmla 28 9 202 cubic8Constraints
    (cubicPrefixWitnessesB09P0CA.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB09P0CA cubicPrefixFmlaB09P0CA
  (include_str "../../../certificates/root_cubic_prefix/B09P0CA.lrat")

theorem cubicPrefixCoveredB09P0CA :
    CubicWitnessPrefixCovered cubicOrbitWitnesses0A
      9 202 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB09P0CA
  · exact cubicPrefixUnsatB09P0CA

end SRG266.Certificates
