/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB10P113
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB10P113 : Sat.Fmla :=
  exactCountCoverChunkFmla 28 10 275 cubic8Constraints
    (cubicPrefixWitnessesB10P113.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB10P113 cubicPrefixFmlaB10P113
  (include_str "../../../certificates/root_cubic_prefix/B10P113.lrat")

theorem cubicPrefixCoveredB10P113 :
    CubicWitnessPrefixCovered cubicOrbitWitnesses03
      10 275 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB10P113
  · exact cubicPrefixUnsatB10P113

end SRG266.Certificates
