/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB09P1D1
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB09P1D1 : Sat.Fmla :=
  exactCountCoverChunkFmla 28 9 465 cubic8Constraints
    (cubicPrefixWitnessesB09P1D1.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB09P1D1 cubicPrefixFmlaB09P1D1
  (include_str "../../../certificates/root_cubic_prefix/B09P1D1.lrat")

theorem cubicPrefixCoveredB09P1D1 :
    CubicWitnessPrefixCovered cubicOrbitWitnesses01
      9 465 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB09P1D1
  · exact cubicPrefixUnsatB09P1D1

end SRG266.Certificates
