/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicWitnessChecks.LeafB10P30E
import SRG266.QuasiSymmetric.RootCubicPrefixCertificate
import SRG266.Search.LRAT

namespace SRG266.Certificates

open SRG266.QuasiSymmetric
open SRG266.Search

def cubicPrefixFmlaB10P30E : Sat.Fmla :=
  exactCountCoverChunkFmla 28 10 782 cubic8Constraints
    (cubicPrefixWitnessesB10P30E.map CubicOrbitWitness.mask)

lrat_unsat_for_computed cubicPrefixUnsatB10P30E cubicPrefixFmlaB10P30E
  (include_str "../../../certificates/root_cubic_prefix/B10P30E.lrat")

theorem cubicPrefixCoveredB10P30E :
    CubicWitnessPrefixCovered cubicOrbitWitnesses0E
      10 782 := by
  apply cubicWitnessPrefixCovered_of_unsat
  · exact cubicPrefixWitnessesOKB10P30E
  · exact cubicPrefixUnsatB10P30E

end SRG266.Certificates
