/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk08

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB07P028 : List CubicOrbitWitness :=
  cubicOrbitWitnesses08.filter fun witness =>
    witness.mask % 128 == 40

theorem cubicPrefixWitnessesB07P028Length : cubicPrefixWitnessesB07P028.length = 0 := by
  decide +kernel



theorem cubicPrefixWitnessesOKB07P028Tail00 :
    (cubicPrefixWitnessesB07P028.drop 0).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB07P028.length ≤ 0 := by
    norm_num [cubicPrefixWitnessesB07P028Length]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB07P028 : cubicPrefixWitnessesB07P028.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB07P028Tail00

end SRG266.Certificates
