/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk03

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P013 : List CubicOrbitWitness :=
  cubicOrbitWitnesses03.filter fun witness =>
    witness.mask % 1024 == 19

theorem cubicPrefixWitnessesB10P013Length : cubicPrefixWitnessesB10P013.length = 108 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P013Slice00 :
    ((cubicPrefixWitnessesB10P013.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P013Slice01 :
    ((cubicPrefixWitnessesB10P013.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P013Slice02 :
    ((cubicPrefixWitnessesB10P013.drop 64).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P013Slice03 :
    ((cubicPrefixWitnessesB10P013.drop 96).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P013Tail04 :
    (cubicPrefixWitnessesB10P013.drop 128).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P013.length ≤ 128 := by
    norm_num [cubicPrefixWitnessesB10P013Length]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P013Tail03 :
    (cubicPrefixWitnessesB10P013.drop 96).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P013.drop 96)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P013Slice03
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P013Tail04

theorem cubicPrefixWitnessesOKB10P013Tail02 :
    (cubicPrefixWitnessesB10P013.drop 64).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P013.drop 64)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P013Slice02
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P013Tail03

theorem cubicPrefixWitnessesOKB10P013Tail01 :
    (cubicPrefixWitnessesB10P013.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P013.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P013Slice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P013Tail02

theorem cubicPrefixWitnessesOKB10P013Tail00 :
    (cubicPrefixWitnessesB10P013.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P013.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P013Slice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P013Tail01

theorem cubicPrefixWitnessesOKB10P013 : cubicPrefixWitnessesB10P013.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P013Tail00

end SRG266.Certificates
