/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk08

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P358 : List CubicOrbitWitness :=
  cubicOrbitWitnesses08.filter fun witness =>
    witness.mask % 1024 == 856

theorem cubicPrefixWitnessesB10P358Length : cubicPrefixWitnessesB10P358.length = 70 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P358Slice00 :
    ((cubicPrefixWitnessesB10P358.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P358Slice01 :
    ((cubicPrefixWitnessesB10P358.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P358Slice02 :
    ((cubicPrefixWitnessesB10P358.drop 64).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P358Tail03 :
    (cubicPrefixWitnessesB10P358.drop 96).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P358.length ≤ 96 := by
    norm_num [cubicPrefixWitnessesB10P358Length]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P358Tail02 :
    (cubicPrefixWitnessesB10P358.drop 64).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P358.drop 64)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P358Slice02
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P358Tail03

theorem cubicPrefixWitnessesOKB10P358Tail01 :
    (cubicPrefixWitnessesB10P358.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P358.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P358Slice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P358Tail02

theorem cubicPrefixWitnessesOKB10P358Tail00 :
    (cubicPrefixWitnessesB10P358.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P358.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P358Slice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P358Tail01

theorem cubicPrefixWitnessesOKB10P358 : cubicPrefixWitnessesB10P358.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P358Tail00

end SRG266.Certificates
