/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk0B

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P20B : List CubicOrbitWitness :=
  cubicOrbitWitnesses0B.filter fun witness =>
    witness.mask % 1024 == 523

theorem cubicPrefixWitnessesB10P20BLength : cubicPrefixWitnessesB10P20B.length = 81 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P20BSlice00 :
    ((cubicPrefixWitnessesB10P20B.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P20BSlice01 :
    ((cubicPrefixWitnessesB10P20B.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P20BSlice02 :
    ((cubicPrefixWitnessesB10P20B.drop 64).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P20BTail03 :
    (cubicPrefixWitnessesB10P20B.drop 96).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P20B.length ≤ 96 := by
    norm_num [cubicPrefixWitnessesB10P20BLength]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P20BTail02 :
    (cubicPrefixWitnessesB10P20B.drop 64).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P20B.drop 64)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P20BSlice02
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P20BTail03

theorem cubicPrefixWitnessesOKB10P20BTail01 :
    (cubicPrefixWitnessesB10P20B.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P20B.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P20BSlice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P20BTail02

theorem cubicPrefixWitnessesOKB10P20BTail00 :
    (cubicPrefixWitnessesB10P20B.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P20B.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P20BSlice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P20BTail01

theorem cubicPrefixWitnessesOKB10P20B : cubicPrefixWitnessesB10P20B.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P20BTail00

end SRG266.Certificates
