/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk02

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P362 : List CubicOrbitWitness :=
  cubicOrbitWitnesses02.filter fun witness =>
    witness.mask % 1024 == 866

theorem cubicPrefixWitnessesB10P362Length : cubicPrefixWitnessesB10P362.length = 142 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P362Slice00 :
    ((cubicPrefixWitnessesB10P362.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P362Slice01 :
    ((cubicPrefixWitnessesB10P362.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P362Slice02 :
    ((cubicPrefixWitnessesB10P362.drop 64).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P362Slice03 :
    ((cubicPrefixWitnessesB10P362.drop 96).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P362Slice04 :
    ((cubicPrefixWitnessesB10P362.drop 128).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P362Tail05 :
    (cubicPrefixWitnessesB10P362.drop 160).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P362.length ≤ 160 := by
    norm_num [cubicPrefixWitnessesB10P362Length]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P362Tail04 :
    (cubicPrefixWitnessesB10P362.drop 128).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P362.drop 128)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P362Slice04
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P362Tail05

theorem cubicPrefixWitnessesOKB10P362Tail03 :
    (cubicPrefixWitnessesB10P362.drop 96).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P362.drop 96)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P362Slice03
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P362Tail04

theorem cubicPrefixWitnessesOKB10P362Tail02 :
    (cubicPrefixWitnessesB10P362.drop 64).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P362.drop 64)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P362Slice02
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P362Tail03

theorem cubicPrefixWitnessesOKB10P362Tail01 :
    (cubicPrefixWitnessesB10P362.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P362.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P362Slice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P362Tail02

theorem cubicPrefixWitnessesOKB10P362Tail00 :
    (cubicPrefixWitnessesB10P362.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P362.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P362Slice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P362Tail01

theorem cubicPrefixWitnessesOKB10P362 : cubicPrefixWitnessesB10P362.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P362Tail00

end SRG266.Certificates
