/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk09

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P099 : List CubicOrbitWitness :=
  cubicOrbitWitnesses09.filter fun witness =>
    witness.mask % 1024 == 153

theorem cubicPrefixWitnessesB10P099Length : cubicPrefixWitnessesB10P099.length = 135 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P099Slice00 :
    ((cubicPrefixWitnessesB10P099.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P099Slice01 :
    ((cubicPrefixWitnessesB10P099.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P099Slice02 :
    ((cubicPrefixWitnessesB10P099.drop 64).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P099Slice03 :
    ((cubicPrefixWitnessesB10P099.drop 96).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P099Slice04 :
    ((cubicPrefixWitnessesB10P099.drop 128).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P099Tail05 :
    (cubicPrefixWitnessesB10P099.drop 160).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P099.length ≤ 160 := by
    norm_num [cubicPrefixWitnessesB10P099Length]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P099Tail04 :
    (cubicPrefixWitnessesB10P099.drop 128).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P099.drop 128)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P099Slice04
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P099Tail05

theorem cubicPrefixWitnessesOKB10P099Tail03 :
    (cubicPrefixWitnessesB10P099.drop 96).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P099.drop 96)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P099Slice03
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P099Tail04

theorem cubicPrefixWitnessesOKB10P099Tail02 :
    (cubicPrefixWitnessesB10P099.drop 64).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P099.drop 64)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P099Slice02
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P099Tail03

theorem cubicPrefixWitnessesOKB10P099Tail01 :
    (cubicPrefixWitnessesB10P099.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P099.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P099Slice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P099Tail02

theorem cubicPrefixWitnessesOKB10P099Tail00 :
    (cubicPrefixWitnessesB10P099.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P099.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P099Slice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P099Tail01

theorem cubicPrefixWitnessesOKB10P099 : cubicPrefixWitnessesB10P099.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P099Tail00

end SRG266.Certificates
