/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk06

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P016 : List CubicOrbitWitness :=
  cubicOrbitWitnesses06.filter fun witness =>
    witness.mask % 1024 == 22

theorem cubicPrefixWitnessesB10P016Length : cubicPrefixWitnessesB10P016.length = 36 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P016Slice00 :
    ((cubicPrefixWitnessesB10P016.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P016Slice01 :
    ((cubicPrefixWitnessesB10P016.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P016Tail02 :
    (cubicPrefixWitnessesB10P016.drop 64).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P016.length ≤ 64 := by
    norm_num [cubicPrefixWitnessesB10P016Length]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P016Tail01 :
    (cubicPrefixWitnessesB10P016.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P016.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P016Slice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P016Tail02

theorem cubicPrefixWitnessesOKB10P016Tail00 :
    (cubicPrefixWitnessesB10P016.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P016.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P016Slice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P016Tail01

theorem cubicPrefixWitnessesOKB10P016 : cubicPrefixWitnessesB10P016.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P016Tail00

end SRG266.Certificates
