/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_cubic_prefix_certificates.py`.
-/
import SRG266.Certificates.RootCubicOrbitData.Chunk0E

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

private theorem allAppendTrue {left right : List CubicOrbitWitness}
    (hleft : left.all checkCubicOrbitWitness = true)
    (hright : right.all checkCubicOrbitWitness = true) :
    (left ++ right).all checkCubicOrbitWitness = true := by
  rw [List.all_append, hleft, hright]
  rfl

def cubicPrefixWitnessesB10P10E : List CubicOrbitWitness :=
  cubicOrbitWitnesses0E.filter fun witness =>
    witness.mask % 1024 == 270

theorem cubicPrefixWitnessesB10P10ELength : cubicPrefixWitnessesB10P10E.length = 108 := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P10ESlice00 :
    ((cubicPrefixWitnessesB10P10E.drop 0).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P10ESlice01 :
    ((cubicPrefixWitnessesB10P10E.drop 32).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P10ESlice02 :
    ((cubicPrefixWitnessesB10P10E.drop 64).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P10ESlice03 :
    ((cubicPrefixWitnessesB10P10E.drop 96).take 32).all
      checkCubicOrbitWitness = true := by
  decide +kernel

theorem cubicPrefixWitnessesOKB10P10ETail04 :
    (cubicPrefixWitnessesB10P10E.drop 128).all
      checkCubicOrbitWitness = true := by
  have hlength : cubicPrefixWitnessesB10P10E.length ≤ 128 := by
    norm_num [cubicPrefixWitnessesB10P10ELength]
  rw [List.drop_eq_nil_of_le hlength]
  rfl

theorem cubicPrefixWitnessesOKB10P10ETail03 :
    (cubicPrefixWitnessesB10P10E.drop 96).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P10E.drop 96)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P10ESlice03
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P10ETail04

theorem cubicPrefixWitnessesOKB10P10ETail02 :
    (cubicPrefixWitnessesB10P10E.drop 64).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P10E.drop 64)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P10ESlice02
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P10ETail03

theorem cubicPrefixWitnessesOKB10P10ETail01 :
    (cubicPrefixWitnessesB10P10E.drop 32).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P10E.drop 32)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P10ESlice01
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P10ETail02

theorem cubicPrefixWitnessesOKB10P10ETail00 :
    (cubicPrefixWitnessesB10P10E.drop 0).all checkCubicOrbitWitness = true := by
  rw [← List.take_append_drop 32
    (cubicPrefixWitnessesB10P10E.drop 0)]
  apply allAppendTrue cubicPrefixWitnessesOKB10P10ESlice00
  simpa only [List.drop_drop] using cubicPrefixWitnessesOKB10P10ETail01

theorem cubicPrefixWitnessesOKB10P10E : cubicPrefixWitnessesB10P10E.all checkCubicOrbitWitness = true := by
  simpa using cubicPrefixWitnessesOKB10P10ETail00

end SRG266.Certificates
