/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_e7_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7CentroidData.Chunk52

/-!
# Generated `E₇ ⊕ E₇` centroid separator data chunk

These declarations contain the integer profiles and separator vectors from
one chunk of the Python certificate.  Lean regenerates all eligible columns
and recomputes every exact Farkas gap.
-/

namespace SRG266

open scoped Matrix

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
def e7GeneratedCentroidCertificates56 : List E7CentroidCertificate :=
[
  { y₁ := ![-18, -12, -2, 0, 0, 4, 10, 18]
    y₂ := ![-12, 0, 0, 0, 0, 0, 0, 12]
    q := fun
      | .count => 0
      | .left i => ![1, -1, -1, -1, -1, 1, 1, 1] i
      | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
    reportedEligible := 80
    reportedGap := 616 },
  { y₁ := ![-18, -12, -2, 0, 0, 4, 10, 18]
    y₂ := ![-6, -6, -6, -6, 6, 6, 6, 6]
    q := fun
      | .count => 0
      | .left i => ![1, -1, -1, -1, -1, 1, 1, 1] i
      | .right i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
    reportedEligible := 80
    reportedGap := 616 },
  { y₁ := ![-18, -12, -2, 4, 6, 6, 8, 8]
    y₂ := ![-16, 0, 0, 0, 0, 0, 0, 16]
    q := fun
      | .count => 2
      | .left i => ![-1, 0, 1, 2, -2, -2, -2, -2] i
      | .right i => ![-2, 0, 0, 0, 0, 0, 0, 2] i
    reportedEligible := 104
    reportedGap := 1144 },
  { y₁ := ![-18, -12, -2, 4, 6, 6, 8, 8]
    y₂ := ![-8, -8, -8, -8, 8, 8, 8, 8]
    q := fun
      | .count => -2
      | .left i => ![-1, -1, 2, 2, -2, -2, -2, -2] i
      | .right i => ![-1, -1, -1, -1, 2, 2, 2, 2] i
    reportedEligible := 104
    reportedGap := 1188 },
  { y₁ := ![-18, -12, -2, 6, 6, 6, 6, 8]
    y₂ := ![-17, -1, -1, 1, 1, 1, 1, 15]
    q := fun
      | .count => 2
      | .left i => ![-2, 2, 2, 2, 2, 2, 2, -2] i
      | .right i => ![-1, -1, 2, -2, -2, -2, -2, 2] i
    reportedEligible := 76
    reportedGap := 1316 }
]

theorem e7GeneratedCentroidCertificates56_length :
    e7GeneratedCentroidCertificates56.length = 5 := by
  rfl

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem e7GeneratedCentroidCertificates56_no_bounded_solution
    (c : E7CentroidCertificate) (hc : c ∈ e7GeneratedCentroidCertificates56) :
    ¬∃ m : E7EligibleIndex c.y₁ c.y₂ → ℤ,
      (∀ w, 0 ≤ m w) ∧
      (∀ w, m w ≤ 3) ∧
      e7CentroidMatrix c.y₁ c.y₂ *ᵥ m =
        e7CentroidTarget c.y₁ c.y₂ := by
  let certificates : List E7KernelCentroidCertificate :=
  [
  { base :=
      { y₁ := ![-18, -12, -2, 0, 0, 4, 10, 18]
        y₂ := ![-12, 0, 0, 0, 0, 0, 0, 12]
        q := fun
          | .count => 0
          | .left i => ![1, -1, -1, -1, -1, 1, 1, 1] i
          | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
        reportedEligible := 80
        reportedGap := 616 }
    leftCentroidPositive := ![-120, -80, -72, -72, -56, -32, 0, -56, -48, -48, -32, -8, 24, -8, -8, 8, 32, 64, 0, 16, 40, 72, 16, 40, 72, 56, 88, 112]
    rightCentroidPositive := ![-48, -48, -48, -48, -48, -48, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 48, 0, 0, 0, 48, 0, 0, 48, 0, 48, 48]
    leftSeparatorPositive := ![0, 0, 0, 0, 8, 8, 8, -8, -8, -8, 0, 0, 0, -8, -8, 0, 0, 0, -8, 0, 0, 0, 0, 0, 0, 8, 8, 8]
    rightSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  { base :=
      { y₁ := ![-18, -12, -2, 0, 0, 4, 10, 18]
        y₂ := ![-6, -6, -6, -6, 6, 6, 6, 6]
        q := fun
          | .count => 0
          | .left i => ![1, -1, -1, -1, -1, 1, 1, 1] i
          | .right i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
        reportedEligible := 80
        reportedGap := 616 }
    leftCentroidPositive := ![-120, -80, -72, -72, -56, -32, 0, -56, -48, -48, -32, -8, 24, -8, -8, 8, 32, 64, 0, 16, 40, 72, 16, 40, 72, 56, 88, 112]
    rightCentroidPositive := ![-48, -48, -48, 0, 0, 0, 0, -48, -48, 0, 0, 0, 0, -48, 0, 0, 0, 0, 0, 0, 0, 0, 48, 48, 48, 48, 48, 48]
    leftSeparatorPositive := ![0, 0, 0, 0, 8, 8, 8, -8, -8, -8, 0, 0, 0, -8, -8, 0, 0, 0, -8, 0, 0, 0, 0, 0, 0, 8, 8, 8]
    rightSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  { base :=
      { y₁ := ![-18, -12, -2, 4, 6, 6, 8, 8]
        y₂ := ![-16, 0, 0, 0, 0, 0, 0, 16]
        q := fun
          | .count => 2
          | .left i => ![-1, 0, 1, 2, -2, -2, -2, -2] i
          | .right i => ![-2, 0, 0, 0, 0, 0, 0, 2] i
        reportedEligible := 104
        reportedGap := 1144 }
    leftCentroidPositive := ![-120, -80, -56, -48, -48, -40, -40, -56, -32, -24, -24, -16, -16, 8, 16, 16, 24, 24, 40, 40, 48, 48, 48, 56, 56, 56, 56, 64]
    rightCentroidPositive := ![-64, -64, -64, -64, -64, -64, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 64, 0, 0, 0, 64, 0, 0, 64, 0, 64, 64]
    leftSeparatorPositive := ![2, 6, 10, -6, -6, -6, -6, 10, 14, -2, -2, -2, -2, 18, 2, 2, 2, 2, 6, 6, 6, 6, -10, -10, -10, -10, -10, -10]
    rightSeparatorPositive := ![-8, -8, -8, -8, -8, -8, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0, 8, 0, 0, 8, 0, 8, 8] },
  { base :=
      { y₁ := ![-18, -12, -2, 4, 6, 6, 8, 8]
        y₂ := ![-8, -8, -8, -8, 8, 8, 8, 8]
        q := fun
          | .count => -2
          | .left i => ![-1, -1, 2, 2, -2, -2, -2, -2] i
          | .right i => ![-1, -1, -1, -1, 2, 2, 2, 2] i
        reportedEligible := 104
        reportedGap := 1188 }
    leftCentroidPositive := ![-120, -80, -56, -48, -48, -40, -40, -56, -32, -24, -24, -16, -16, 8, 16, 16, 24, 24, 40, 40, 48, 48, 48, 56, 56, 56, 56, 64]
    rightCentroidPositive := ![-64, -64, -64, 0, 0, 0, 0, -64, -64, 0, 0, 0, 0, -64, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 64, 64, 64]
    leftSeparatorPositive := ![-2, 10, 10, -6, -6, -6, -6, 10, 10, -6, -6, -6, -6, 22, 6, 6, 6, 6, 6, 6, 6, 6, -10, -10, -10, -10, -10, -10]
    rightSeparatorPositive := ![-12, -12, -12, 0, 0, 0, 0, -12, -12, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 0, 0, 0, 12, 12, 12, 12, 12, 12] },
  { base :=
      { y₁ := ![-18, -12, -2, 6, 6, 6, 6, 8]
        y₂ := ![-17, -1, -1, 1, 1, 1, 1, 15]
        q := fun
          | .count => 2
          | .left i => ![-2, 2, 2, 2, 2, 2, 2, -2] i
          | .right i => ![-1, -1, 2, -2, -2, -2, -2, 2] i
        reportedEligible := 76
        reportedGap := 1316 }
    leftCentroidPositive := ![-120, -80, -48, -48, -48, -48, -40, -56, -24, -24, -24, -24, -16, 16, 16, 16, 16, 24, 48, 48, 48, 56, 48, 48, 56, 48, 56, 56]
    rightCentroidPositive := ![-72, -72, -64, -64, -64, -64, -8, -8, 0, 0, 0, 0, 56, 0, 0, 0, 0, 56, 8, 8, 8, 64, 8, 8, 64, 8, 64, 64]
    leftSeparatorPositive := ![-8, -8, -8, -8, -8, -8, -24, 8, 8, 8, 8, 8, -8, 8, 8, 8, 8, -8, 8, 8, 8, -8, 8, 8, -8, 8, -8, -8]
    rightSeparatorPositive := ![-2, 10, -6, -6, -6, -6, 10, 10, -6, -6, -6, -6, 10, 6, 6, 6, 6, 22, -10, -10, -10, 6, -10, -10, 6, -10, 6, 6] }
  ]
  have hchecked :
      certificates.all E7KernelCentroidCertificate.check = true := by
    decide +kernel
  have hbases :
      certificates.map E7KernelCentroidCertificate.base =
        e7GeneratedCentroidCertificates56 := by
    rfl
  rw [← hbases] at hc
  simp only [List.mem_map] at hc
  obtain ⟨certificate, hmem, rfl⟩ := hc
  apply certificate.no_bounded_solution
  exact (List.all_eq_true.mp hchecked) certificate hmem

end SRG266
