/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_e7_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7CentroidData.Chunk51

/-!
# Generated `E₇ ⊕ E₇` centroid separator data chunk

These declarations contain the integer profiles and separator vectors from
one chunk of the Python certificate.  Lean regenerates all eligible columns
and recomputes every exact Farkas gap.
-/

namespace SRG266

open scoped Matrix

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
def e7GeneratedCentroidCertificates55 : List E7CentroidCertificate :=
[
  { y₁ := ![-18, -12, -4, -2, 4, 4, 10, 18]
    y₂ := ![-4, -4, -4, -4, -4, 4, 4, 12]
    q := fun
      | .count => 8
      | .left i => ![-8, -8, -3, -8, -8, -8, 8, 3] i
      | .right i => ![2, 2, 2, 2, 2, -3, -3, -8] i
    reportedEligible := 80
    reportedGap := 3276 },
  { y₁ := ![-18, -12, -4, -2, 4, 4, 14, 14]
    y₂ := ![-12, 0, 0, 0, 0, 0, 0, 12]
    q := fun
      | .count => 0
      | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
      | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
    reportedEligible := 80
    reportedGap := 616 },
  { y₁ := ![-18, -12, -4, -2, 4, 4, 14, 14]
    y₂ := ![-6, -6, -6, -6, 6, 6, 6, 6]
    q := fun
      | .count => 0
      | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
      | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
    reportedEligible := 80
    reportedGap := 616 },
  { y₁ := ![-18, -12, -4, 2, 4, 4, 12, 12]
    y₂ := ![-14, 0, 0, 0, 0, 0, 0, 14]
    q := fun
      | .count => 0
      | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
      | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
    reportedEligible := 104
    reportedGap := 616 },
  { y₁ := ![-18, -12, -4, 2, 4, 4, 12, 12]
    y₂ := ![-7, -7, -7, -7, 7, 7, 7, 7]
    q := fun
      | .count => 0
      | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
      | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
    reportedEligible := 104
    reportedGap := 616 }
]

theorem e7GeneratedCentroidCertificates55_length :
    e7GeneratedCentroidCertificates55.length = 5 := by
  rfl

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem e7GeneratedCentroidCertificates55_no_bounded_solution
    (c : E7CentroidCertificate) (hc : c ∈ e7GeneratedCentroidCertificates55) :
    ¬∃ m : E7EligibleIndex c.y₁ c.y₂ → ℤ,
      (∀ w, 0 ≤ m w) ∧
      (∀ w, m w ≤ 3) ∧
      e7CentroidMatrix c.y₁ c.y₂ *ᵥ m =
        e7CentroidTarget c.y₁ c.y₂ := by
  let certificates : List E7KernelCentroidCertificate :=
  [
  { base :=
      { y₁ := ![-18, -12, -4, -2, 4, 4, 10, 18]
        y₂ := ![-4, -4, -4, -4, -4, 4, 4, 12]
        q := fun
          | .count => 8
          | .left i => ![-8, -8, -3, -8, -8, -8, 8, 3] i
          | .right i => ![2, 2, 2, 2, 2, -3, -3, -8] i
        reportedEligible := 80
        reportedGap := 3276 }
    leftCentroidPositive := ![-120, -88, -80, -56, -56, -32, 0, -64, -56, -32, -32, -8, 24, -24, 0, 0, 24, 56, 8, 8, 32, 64, 32, 56, 88, 56, 88, 112]
    rightCentroidPositive := ![-32, -32, -32, -32, 0, 0, 32, -32, -32, -32, 0, 0, 32, -32, -32, 0, 0, 32, -32, 0, 0, 32, 0, 0, 32, 32, 64, 64]
    leftSeparatorPositive := ![-32, -12, -32, -32, -32, 32, 12, -12, -32, -32, -32, 32, 12, -12, -12, -12, 52, 32, -32, -32, 32, 12, -32, 32, 12, 32, 12, 76]
    rightSeparatorPositive := ![20, 20, 20, 20, 0, 0, -20, 20, 20, 20, 0, 0, -20, 20, 20, 0, 0, -20, 20, 0, 0, -20, 0, 0, -20, -20, -40, -40] },
  { base :=
      { y₁ := ![-18, -12, -4, -2, 4, 4, 14, 14]
        y₂ := ![-12, 0, 0, 0, 0, 0, 0, 12]
        q := fun
          | .count => 0
          | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
          | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
        reportedEligible := 80
        reportedGap := 616 }
    leftCentroidPositive := ![-120, -88, -80, -56, -56, -16, -16, -64, -56, -32, -32, 8, 8, -24, 0, 0, 40, 40, 8, 8, 48, 48, 32, 72, 72, 72, 72, 112]
    rightCentroidPositive := ![-48, -48, -48, -48, -48, -48, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 48, 0, 0, 0, 48, 0, 0, 48, 0, 48, 48]
    leftSeparatorPositive := ![0, -8, 0, -8, -8, 0, 0, 0, 8, 0, 0, 8, 8, 0, -8, -8, 0, 0, 0, 0, 8, 8, -8, 0, 0, 0, 0, 8]
    rightSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  { base :=
      { y₁ := ![-18, -12, -4, -2, 4, 4, 14, 14]
        y₂ := ![-6, -6, -6, -6, 6, 6, 6, 6]
        q := fun
          | .count => 0
          | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
          | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
        reportedEligible := 80
        reportedGap := 616 }
    leftCentroidPositive := ![-120, -88, -80, -56, -56, -16, -16, -64, -56, -32, -32, 8, 8, -24, 0, 0, 40, 40, 8, 8, 48, 48, 32, 72, 72, 72, 72, 112]
    rightCentroidPositive := ![-48, -48, -48, 0, 0, 0, 0, -48, -48, 0, 0, 0, 0, -48, 0, 0, 0, 0, 0, 0, 0, 0, 48, 48, 48, 48, 48, 48]
    leftSeparatorPositive := ![0, -8, 0, -8, -8, 0, 0, 0, 8, 0, 0, 8, 8, 0, -8, -8, 0, 0, 0, 0, 8, 8, -8, 0, 0, 0, 0, 8]
    rightSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  { base :=
      { y₁ := ![-18, -12, -4, 2, 4, 4, 12, 12]
        y₂ := ![-14, 0, 0, 0, 0, 0, 0, 14]
        q := fun
          | .count => 0
          | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
          | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
        reportedEligible := 104
        reportedGap := 616 }
    leftCentroidPositive := ![-120, -88, -64, -56, -56, -24, -24, -64, -40, -32, -32, 0, 0, -8, 0, 0, 32, 32, 24, 24, 56, 56, 32, 64, 64, 64, 64, 96]
    rightCentroidPositive := ![-56, -56, -56, -56, -56, -56, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0, 56, 0, 0, 0, 56, 0, 0, 56, 0, 56, 56]
    leftSeparatorPositive := ![0, -8, 0, -8, -8, 0, 0, 0, 8, 0, 0, 8, 8, 0, -8, -8, 0, 0, 0, 0, 8, 8, -8, 0, 0, 0, 0, 8]
    rightSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  { base :=
      { y₁ := ![-18, -12, -4, 2, 4, 4, 12, 12]
        y₂ := ![-7, -7, -7, -7, 7, 7, 7, 7]
        q := fun
          | .count => 0
          | .left i => ![-1, 1, -1, 1, -1, -1, 1, 1] i
          | .right i => ![1, 1, 1, 1, 1, 1, 1, 1] i
        reportedEligible := 104
        reportedGap := 616 }
    leftCentroidPositive := ![-120, -88, -64, -56, -56, -24, -24, -64, -40, -32, -32, 0, 0, -8, 0, 0, 32, 32, 24, 24, 56, 56, 32, 64, 64, 64, 64, 96]
    rightCentroidPositive := ![-56, -56, -56, 0, 0, 0, 0, -56, -56, 0, 0, 0, 0, -56, 0, 0, 0, 0, 0, 0, 0, 0, 56, 56, 56, 56, 56, 56]
    leftSeparatorPositive := ![0, -8, 0, -8, -8, 0, 0, 0, 8, 0, 0, 8, 8, 0, -8, -8, 0, 0, 0, 0, 8, 8, -8, 0, 0, 0, 0, 8]
    rightSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
  ]
  have hchecked :
      certificates.all E7KernelCentroidCertificate.check = true := by
    decide +kernel
  have hbases :
      certificates.map E7KernelCentroidCertificate.base =
        e7GeneratedCentroidCertificates55 := by
    rfl
  rw [← hbases] at hc
  simp only [List.mem_map] at hc
  obtain ⟨certificate, hmem, rfl⟩ := hc
  apply certificate.no_bounded_solution
  exact (List.all_eq_true.mp hchecked) certificate hmem

end SRG266
