/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_e7_centroid_data.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7CentroidData.Chunk116

/-!
# Generated `E₇ ⊕ E₇` centroid separator data chunk

These declarations contain the integer profiles and separator vectors from
one chunk of the Python certificate.  Lean regenerates all eligible columns
and recomputes every exact Farkas gap.
-/

namespace SRG266

open scoped Matrix

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
def e7GeneratedCentroidCertificates120 : List E7CentroidCertificate :=
[
  { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
    y₂ := ![-12, -10, -6, 0, 0, 0, 14, 14]
    q := fun
      | .count => 2
      | .left i => ![1, 2, 2, 2, 2, 2, 0, 1] i
      | .right i => ![-2, -2, 2, -2, -2, -2, -1, -1] i
    reportedEligible := 80
    reportedGap := 352 },
  { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
    y₂ := ![-12, -10, -4, -2, -2, 2, 12, 16]
    q := fun
      | .count => 4
      | .left i => ![-3, 2, 2, 2, 2, 2, -4, 1] i
      | .right i => ![4, -4, 4, -1, -1, -4, 4, -2] i
    reportedEligible := 80
    reportedGap := 740 },
  { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
    y₂ := ![-11, -11, -3, -3, -3, 3, 13, 15]
    q := fun
      | .count => 0
      | .left i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
      | .right i => ![-1, -1, 1, 1, 1, -1, -1, 1] i
    reportedEligible := 80
    reportedGap := 264 },
  { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
    y₂ := ![-11, -11, -3, -3, -1, 1, 11, 17]
    q := fun
      | .count => 0
      | .left i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
      | .right i => ![-1, -1, 1, 1, -1, 1, 1, -1] i
    reportedEligible := 80
    reportedGap := 264 },
  { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
    y₂ := ![-10, -8, -6, -4, -4, 4, 10, 18]
    q := fun
      | .count => 0
      | .left i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
      | .right i => ![1, -1, 1, -1, -1, 1, -1, 1] i
    reportedEligible := 80
    reportedGap := 264 }
]

theorem e7GeneratedCentroidCertificates120_length :
    e7GeneratedCentroidCertificates120.length = 5 := by
  rfl

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem e7GeneratedCentroidCertificates120_no_bounded_solution
    (c : E7CentroidCertificate) (hc : c ∈ e7GeneratedCentroidCertificates120) :
    ¬∃ m : E7EligibleIndex c.y₁ c.y₂ → ℤ,
      (∀ w, 0 ≤ m w) ∧
      (∀ w, m w ≤ 3) ∧
      e7CentroidMatrix c.y₁ c.y₂ *ᵥ m =
        e7CentroidTarget c.y₁ c.y₂ := by
  let certificates : List E7KernelCentroidCertificate :=
  [
  { base :=
      { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
        y₂ := ![-12, -10, -6, 0, 0, 0, 14, 14]
        q := fun
          | .count => 2
          | .left i => ![1, 2, 2, 2, 2, 2, 0, 1] i
          | .right i => ![-2, -2, 2, -2, -2, -2, -1, -1] i
        reportedEligible := 80
        reportedGap := 352 }
    leftCentroidPositive := ![-64, -64, -64, -64, -64, -48, 8, -8, -8, -8, -8, 8, 64, -8, -8, -8, 8, 64, -8, -8, 8, 64, -8, 8, 64, 8, 64, 80]
    rightCentroidPositive := ![-88, -72, -48, -48, -48, 8, 8, -64, -40, -40, -40, 16, 16, -24, -24, -24, 32, 32, 0, 0, 56, 56, 0, 56, 56, 56, 56, 112]
    leftSeparatorPositive := ![0, 0, 0, 0, 0, -8, -4, 4, 4, 4, 4, -4, 0, 4, 4, 4, -4, 0, 4, 4, -4, 0, 4, -4, 0, -4, 0, -8]
    rightSeparatorPositive := ![-6, 10, -6, -6, -6, -2, -2, 10, -6, -6, -6, -2, -2, 10, 10, 10, 14, 14, -6, -6, -2, -2, -6, -2, -2, -2, -2, 2] },
  { base :=
      { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
        y₂ := ![-12, -10, -4, -2, -2, 2, 12, 16]
        q := fun
          | .count => 4
          | .left i => ![-3, 2, 2, 2, 2, 2, -4, 1] i
          | .right i => ![4, -4, 4, -1, -1, -4, 4, -2] i
        reportedEligible := 80
        reportedGap := 740 }
    leftCentroidPositive := ![-64, -64, -64, -64, -64, -48, 8, -8, -8, -8, -8, 8, 64, -8, -8, -8, 8, 64, -8, -8, 8, 64, -8, 8, 64, 8, 64, 80]
    rightCentroidPositive := ![-88, -64, -56, -56, -40, 0, 16, -56, -48, -48, -32, 8, 24, -24, -24, -8, 32, 48, -16, 0, 40, 56, 0, 40, 56, 56, 72, 112]
    leftSeparatorPositive := ![-8, -8, -8, -8, -8, -32, -12, 12, 12, 12, 12, -12, 8, 12, 12, 12, -12, 8, 12, 12, -12, 8, 12, -12, 8, -12, 8, -16]
    rightSeparatorPositive := ![0, 32, 12, 12, 0, 32, 8, 0, -20, -20, -32, 0, -24, 12, 12, 0, 32, 8, -8, -20, 12, -12, -20, 12, -12, 0, -24, 8] },
  { base :=
      { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
        y₂ := ![-11, -11, -3, -3, -3, 3, 13, 15]
        q := fun
          | .count => 0
          | .left i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
          | .right i => ![-1, -1, 1, 1, 1, -1, -1, 1] i
        reportedEligible := 80
        reportedGap := 264 }
    leftCentroidPositive := ![-64, -64, -64, -64, -64, -48, 8, -8, -8, -8, -8, 8, 64, -8, -8, -8, 8, 64, -8, -8, 8, 64, -8, 8, 64, 8, 64, 80]
    rightCentroidPositive := ![-88, -56, -56, -56, -32, 8, 16, -56, -56, -56, -32, 8, 16, -24, -24, 0, 40, 48, -24, 0, 40, 48, 0, 40, 48, 64, 72, 112]
    leftSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    rightSeparatorPositive := ![-8, 0, 0, 0, -8, -8, 0, 0, 0, 0, -8, -8, 0, 8, 8, 0, 0, 8, 8, 0, 0, 8, 0, 0, 8, -8, 0, 0] },
  { base :=
      { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
        y₂ := ![-11, -11, -3, -3, -1, 1, 11, 17]
        q := fun
          | .count => 0
          | .left i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
          | .right i => ![-1, -1, 1, 1, -1, 1, 1, -1] i
        reportedEligible := 80
        reportedGap := 264 }
    leftCentroidPositive := ![-64, -64, -64, -64, -64, -48, 8, -8, -8, -8, -8, 8, 64, -8, -8, -8, 8, 64, -8, -8, 8, 64, -8, 8, 64, 8, 64, 80]
    rightCentroidPositive := ![-88, -56, -56, -48, -40, 0, 24, -56, -56, -48, -40, 0, 24, -24, -16, -8, 32, 56, -16, -8, 32, 56, 0, 40, 64, 48, 72, 112]
    leftSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    rightSeparatorPositive := ![-8, 0, 0, -8, 0, 0, -8, 0, 0, -8, 0, 0, -8, 8, 0, 8, 8, 0, 0, 8, 8, 0, 0, 0, -8, 8, 0, 0] },
  { base :=
      { y₁ := ![-15, -1, -1, -1, -1, -1, 3, 17]
        y₂ := ![-10, -8, -6, -4, -4, 4, 10, 18]
        q := fun
          | .count => 0
          | .left i => ![-1, -1, -1, -1, -1, -1, -1, -1] i
          | .right i => ![1, -1, 1, -1, -1, 1, -1, 1] i
        reportedEligible := 80
        reportedGap := 264 }
    leftCentroidPositive := ![-64, -64, -64, -64, -64, -48, 8, -8, -8, -8, -8, 8, 64, -8, -8, -8, 8, 64, -8, -8, 8, 64, -8, 8, 64, 8, 64, 80]
    rightCentroidPositive := ![-72, -64, -56, -56, -24, 0, 32, -56, -48, -48, -16, 8, 40, -40, -40, -8, 16, 48, -32, 0, 24, 56, 0, 24, 56, 56, 88, 112]
    leftSeparatorPositive := ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    rightSeparatorPositive := ![0, 8, 0, 0, 8, 0, 8, 0, -8, -8, 0, -8, 0, 0, 0, 8, 0, 8, -8, 0, -8, 0, 0, -8, 0, 0, 8, 0] }
  ]
  have hchecked :
      certificates.all E7KernelCentroidCertificate.check = true := by
    decide +kernel
  have hbases :
      certificates.map E7KernelCentroidCertificate.base =
        e7GeneratedCentroidCertificates120 := by
    rfl
  rw [← hbases] at hc
  simp only [List.mem_map] at hc
  obtain ⟨certificate, hmem, rfl⟩ := hc
  apply certificate.no_bounded_solution
  exact (List.all_eq_true.mp hchecked) certificate hmem

end SRG266
