/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_e7_two_ten_psd.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7TwoTenShell.Eligible

/-!
# Rows 56 through 63 of the exact `2 x 10` PSD factor

Keeping the integer literal in eight-row blocks bounds elaboration cost without
changing the mathematical certificate.
-/

namespace SRG266
namespace E7TwoTenData

def scaledFactorDataBlock07 : Array (Array ℤ) :=
#[
  #[11, -21, 39, -32, -96, 43, 319, -220, 188, -439, -657, 54, -41, -41, 73, 73, -29, -22, -110, 193, 7, -25, -5, -2, 2, -3, -3, 1],
  #[-5, 33, -15, 56, -8, -147, -61, 392, -16, 869, -3, -120, -41, -41, 73, 73, -29, -22, -110, 193, 7, -25, -5, -2, 2, -3, -3, 1],
  #[11, -21, 39, -32, 80, -59, -367, 188, -220, 359, 577, -62, 17, 17, -169, -169, 13, -22, -110, -9, 39, -25, -5, -2, -2, 3, 3, -1],
  #[-5, 33, -15, 56, -8, 131, 13, -424, -16, -949, -77, 112, 17, 17, -169, -169, 13, -22, -110, -9, 39, -25, -5, -2, -2, 3, 3, -1],
  #[11, -21, 39, -32, 80, -59, -367, 188, 188, -439, -657, 54, 17, 17, -169, 73, -29, -22, -7, -108, -27, 37, -5, -2, -2, 3, -3, 1],
  #[-5, 33, -15, 56, -8, 131, 13, -424, -16, 869, -3, -120, 17, 17, -169, 73, -29, -22, -7, -108, -27, 37, -5, -2, -2, 3, -3, 1],
  #[11, -21, 39, -32, 80, -59, 203, -81, -285, 651, -657, 54, 17, 17, 68, -174, -29, -1, -108, -108, -27, -27, 7, -2, -2, -2, 4, 1],
  #[-5, 33, -15, 56, -8, 131, 13, 225, 21, -1311, -3, -120, 17, 17, 68, -174, -29, -1, -108, -108, -27, -27, 7, -2, -2, -2, 4, 1]
]

end E7TwoTenData
end SRG266
