/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

Generated by `scripts/generate_e7_concrete_expansion.py`.
Do not edit by hand.
-/
import SRG266.Certificates.E7ConcreteFilterData

/-!
# One block of the concrete E7 filtering sweep

Each theorem evaluates the filtering sweep below one frontier state.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

theorem e7ConcreteChunkOdd0156 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨11, 7, 12, 144, [], [12]⟩ : E7FilterState) =
      [#[-5, -5, -5, -5, -5, -5, 5, 25], #[-11, -7, -7, -1, -1, 1, 1, 25], #[-11, -7, -7, -5, -3, 3, 5, 25], #[-11, -11, -5, -3, -3, 3, 5, 25], #[-15, -5, -5, -5, -5, 5, 5, 25]] := by
  decide +kernel

theorem e7ConcreteChunkOdd0157 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨11, 6, 24, 288, [], [12, 12]⟩ : E7FilterState) =
      [] := by
  decide +kernel

end SRG266
