/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

Generated by `scripts/generate_e7_concrete_expansion.py`.
Do not edit by hand.
-/
import SRG266.Certificates.E7ConcreteFilterData

/-!
# One block of the concrete E7 filtering sweep

Each theorem evaluates the filtering sweep below one frontier state.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

theorem e7ConcreteChunkOdd0129 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨9, 6, -20, 200, [-10, -10], []⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0130 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨9, 5, -10, 300, [-10, -10], [10]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0131 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨9, 5, -30, 300, [-10, -10, -10], []⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0132 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨8, 7, 11, 121, [], [11]⟩ : E7FilterState) =
      [#[-9, -7, -7, -7, -1, 1, 7, 23], #[-13, -9, -5, -5, -3, 5, 7, 23], #[-13, -9, -9, -3, -1, 5, 7, 23]] := by
  decide +kernel

theorem e7ConcreteChunkOdd0133 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨8, 6, 20, 202, [], [9, 11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0134 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨8, 5, 29, 283, [], [9, 9, 11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0135 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨8, 6, 2, 202, [-9], [11]⟩ : E7FilterState) =
      [#[-17, -1, -1, -1, -1, -1, -1, 23]] := by
  decide +kernel

theorem e7ConcreteChunkOdd0136 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨8, 5, 11, 283, [-9], [9, 11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0137 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨8, 5, -7, 283, [-9, -9], [11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0138 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨9, 6, 21, 221, [], [10, 11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0139 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨9, 6, 1, 221, [-10], [11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

theorem e7ConcreteChunkOdd0140 :
    e7FilterAuxState e7ConcreteRelevant 1
        (⟨10, 6, 22, 242, [], [11, 11]⟩ : E7FilterState) =
      [] := by
  decide +kernel

end SRG266
