/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15EnumerationChunks.Chunk0451
import SRG266.Certificates.A15EnumerationChunks.Chunk0452
import SRG266.Certificates.A15EnumerationChunks.Chunk0453
import SRG266.Certificates.A15EnumerationChunks.Chunk0454
import SRG266.Certificates.A15EnumerationChunks.Chunk0455
import SRG266.Certificates.A15EnumerationChunks.Chunk0456
import SRG266.Certificates.A15EnumerationChunks.Chunk0457
import SRG266.Certificates.A15EnumerationChunks.Chunk0458
import SRG266.Certificates.A15EnumerationChunks.Chunk0459
import SRG266.Certificates.A15EnumerationChunks.Chunk0460
import SRG266.Certificates.A15EnumerationChunks.Chunk0461
import SRG266.Certificates.A15EnumerationChunks.Chunk0462
import SRG266.Certificates.A15EnumerationChunks.Chunk0463
import SRG266.Certificates.A15EnumerationChunks.Chunk0464
import SRG266.Certificates.A15EnumerationChunks.Chunk0465
import SRG266.Certificates.A15EnumerationChunks.Chunk0466
import SRG266.Certificates.A15EnumerationChunks.Chunk0467
import SRG266.Certificates.A15EnumerationChunks.Chunk0468
import SRG266.Certificates.A15EnumerationChunks.Chunk0469
import SRG266.Certificates.A15EnumerationChunks.Chunk0470
import SRG266.Certificates.A15EnumerationChunks.Chunk0471
import SRG266.Certificates.A15EnumerationChunks.Chunk0472
import SRG266.Certificates.A15EnumerationChunks.Chunk0473
import SRG266.Certificates.A15EnumerationChunks.Chunk0474
import SRG266.Certificates.A15EnumerationChunks.Chunk0475
import SRG266.Certificates.A15EnumerationChunks.Chunk0476
import SRG266.Certificates.A15EnumerationChunks.Chunk0477
import SRG266.Certificates.A15EnumerationChunks.Chunk0478
import SRG266.Certificates.A15EnumerationChunks.Chunk0479
import SRG266.Certificates.A15EnumerationChunks.Chunk0480

/-!
# Bounded A15 enumeration group 016

Chunks 0451 to 0480 of the
residue-2 branch, concatenated.  No search is evaluated here: the
chunk certificates are glued with `a15PolyExpand_append`, which distributes
`List.flatMap` over `++`.
-/

namespace SRG266

/-- Frontier states of group 016. -/
def a15EnumGroup016 : List A15MagState :=
    a15EnumChunk0451 ++ a15EnumChunk0452 ++ a15EnumChunk0453 ++
    a15EnumChunk0454 ++ a15EnumChunk0455 ++ a15EnumChunk0456 ++
    a15EnumChunk0457 ++ a15EnumChunk0458 ++ a15EnumChunk0459 ++
    a15EnumChunk0460 ++ a15EnumChunk0461 ++ a15EnumChunk0462 ++
    a15EnumChunk0463 ++ a15EnumChunk0464 ++ a15EnumChunk0465 ++
    a15EnumChunk0466 ++ a15EnumChunk0467 ++ a15EnumChunk0468 ++
    a15EnumChunk0469 ++ a15EnumChunk0470 ++ a15EnumChunk0471 ++
    a15EnumChunk0472 ++ a15EnumChunk0473 ++ a15EnumChunk0474 ++
    a15EnumChunk0475 ++ a15EnumChunk0476 ++ a15EnumChunk0477 ++
    a15EnumChunk0478 ++ a15EnumChunk0479 ++ a15EnumChunk0480

/-- The profiles emitted below group 016. -/
def a15EnumGroup016Out : List (Array ℤ) :=
    a15EnumChunk0451Out ++ a15EnumChunk0452Out ++ a15EnumChunk0453Out ++
    a15EnumChunk0454Out ++ a15EnumChunk0455Out ++ a15EnumChunk0456Out ++
    a15EnumChunk0457Out ++ a15EnumChunk0458Out ++ a15EnumChunk0459Out ++
    a15EnumChunk0460Out ++ a15EnumChunk0461Out ++ a15EnumChunk0462Out ++
    a15EnumChunk0463Out ++ a15EnumChunk0464Out ++ a15EnumChunk0465Out ++
    a15EnumChunk0466Out ++ a15EnumChunk0467Out ++ a15EnumChunk0468Out ++
    a15EnumChunk0469Out ++ a15EnumChunk0470Out ++ a15EnumChunk0471Out ++
    a15EnumChunk0472Out ++ a15EnumChunk0473Out ++ a15EnumChunk0474Out ++
    a15EnumChunk0475Out ++ a15EnumChunk0476Out ++ a15EnumChunk0477Out ++
    a15EnumChunk0478Out ++ a15EnumChunk0479Out ++ a15EnumChunk0480Out

theorem a15EnumGroup016_eq :
    a15PolyExpand 2 5 a15EnumGroup016 = a15EnumGroup016Out := by
  rw [a15EnumGroup016, a15EnumGroup016Out]
  simp only [a15PolyExpand_append, a15EnumChunk0451_eq, a15EnumChunk0452_eq,
    a15EnumChunk0453_eq, a15EnumChunk0454_eq, a15EnumChunk0455_eq,
    a15EnumChunk0456_eq, a15EnumChunk0457_eq, a15EnumChunk0458_eq,
    a15EnumChunk0459_eq, a15EnumChunk0460_eq, a15EnumChunk0461_eq,
    a15EnumChunk0462_eq, a15EnumChunk0463_eq, a15EnumChunk0464_eq,
    a15EnumChunk0465_eq, a15EnumChunk0466_eq, a15EnumChunk0467_eq,
    a15EnumChunk0468_eq, a15EnumChunk0469_eq, a15EnumChunk0470_eq,
    a15EnumChunk0471_eq, a15EnumChunk0472_eq, a15EnumChunk0473_eq,
    a15EnumChunk0474_eq, a15EnumChunk0475_eq, a15EnumChunk0476_eq,
    a15EnumChunk0477_eq, a15EnumChunk0478_eq, a15EnumChunk0479_eq,
    a15EnumChunk0480_eq]

end SRG266
