/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15EnumerationChunks.Chunk0210
import SRG266.Certificates.A15EnumerationChunks.Chunk0211
import SRG266.Certificates.A15EnumerationChunks.Chunk0212
import SRG266.Certificates.A15EnumerationChunks.Chunk0213
import SRG266.Certificates.A15EnumerationChunks.Chunk0214
import SRG266.Certificates.A15EnumerationChunks.Chunk0215
import SRG266.Certificates.A15EnumerationChunks.Chunk0216
import SRG266.Certificates.A15EnumerationChunks.Chunk0217
import SRG266.Certificates.A15EnumerationChunks.Chunk0218
import SRG266.Certificates.A15EnumerationChunks.Chunk0219
import SRG266.Certificates.A15EnumerationChunks.Chunk0220
import SRG266.Certificates.A15EnumerationChunks.Chunk0221
import SRG266.Certificates.A15EnumerationChunks.Chunk0222
import SRG266.Certificates.A15EnumerationChunks.Chunk0223
import SRG266.Certificates.A15EnumerationChunks.Chunk0224
import SRG266.Certificates.A15EnumerationChunks.Chunk0225
import SRG266.Certificates.A15EnumerationChunks.Chunk0226
import SRG266.Certificates.A15EnumerationChunks.Chunk0227
import SRG266.Certificates.A15EnumerationChunks.Chunk0228
import SRG266.Certificates.A15EnumerationChunks.Chunk0229
import SRG266.Certificates.A15EnumerationChunks.Chunk0230
import SRG266.Certificates.A15EnumerationChunks.Chunk0231
import SRG266.Certificates.A15EnumerationChunks.Chunk0232
import SRG266.Certificates.A15EnumerationChunks.Chunk0233
import SRG266.Certificates.A15EnumerationChunks.Chunk0234
import SRG266.Certificates.A15EnumerationChunks.Chunk0235
import SRG266.Certificates.A15EnumerationChunks.Chunk0236
import SRG266.Certificates.A15EnumerationChunks.Chunk0237
import SRG266.Certificates.A15EnumerationChunks.Chunk0238
import SRG266.Certificates.A15EnumerationChunks.Chunk0239

/-!
# Bounded A15 enumeration group 007

Chunks 0210 to 0239 of the
residue-0 branch, concatenated.  No search is evaluated here: the
chunk certificates are glued with `a15PolyExpand_append`, which distributes
`List.flatMap` over `++`.
-/

namespace SRG266

/-- Frontier states of group 007. -/
def a15EnumGroup007 : List A15MagState :=
    a15EnumChunk0210 ++ a15EnumChunk0211 ++ a15EnumChunk0212 ++
    a15EnumChunk0213 ++ a15EnumChunk0214 ++ a15EnumChunk0215 ++
    a15EnumChunk0216 ++ a15EnumChunk0217 ++ a15EnumChunk0218 ++
    a15EnumChunk0219 ++ a15EnumChunk0220 ++ a15EnumChunk0221 ++
    a15EnumChunk0222 ++ a15EnumChunk0223 ++ a15EnumChunk0224 ++
    a15EnumChunk0225 ++ a15EnumChunk0226 ++ a15EnumChunk0227 ++
    a15EnumChunk0228 ++ a15EnumChunk0229 ++ a15EnumChunk0230 ++
    a15EnumChunk0231 ++ a15EnumChunk0232 ++ a15EnumChunk0233 ++
    a15EnumChunk0234 ++ a15EnumChunk0235 ++ a15EnumChunk0236 ++
    a15EnumChunk0237 ++ a15EnumChunk0238 ++ a15EnumChunk0239

/-- The profiles emitted below group 007. -/
def a15EnumGroup007Out : List (Array ℤ) :=
    a15EnumChunk0210Out ++ a15EnumChunk0211Out ++ a15EnumChunk0212Out ++
    a15EnumChunk0213Out ++ a15EnumChunk0214Out ++ a15EnumChunk0215Out ++
    a15EnumChunk0216Out ++ a15EnumChunk0217Out ++ a15EnumChunk0218Out ++
    a15EnumChunk0219Out ++ a15EnumChunk0220Out ++ a15EnumChunk0221Out ++
    a15EnumChunk0222Out ++ a15EnumChunk0223Out ++ a15EnumChunk0224Out ++
    a15EnumChunk0225Out ++ a15EnumChunk0226Out ++ a15EnumChunk0227Out ++
    a15EnumChunk0228Out ++ a15EnumChunk0229Out ++ a15EnumChunk0230Out ++
    a15EnumChunk0231Out ++ a15EnumChunk0232Out ++ a15EnumChunk0233Out ++
    a15EnumChunk0234Out ++ a15EnumChunk0235Out ++ a15EnumChunk0236Out ++
    a15EnumChunk0237Out ++ a15EnumChunk0238Out ++ a15EnumChunk0239Out

theorem a15EnumGroup007_eq :
    a15PolyExpand 0 5 a15EnumGroup007 = a15EnumGroup007Out := by
  rw [a15EnumGroup007, a15EnumGroup007Out]
  simp only [a15PolyExpand_append, a15EnumChunk0210_eq, a15EnumChunk0211_eq,
    a15EnumChunk0212_eq, a15EnumChunk0213_eq, a15EnumChunk0214_eq,
    a15EnumChunk0215_eq, a15EnumChunk0216_eq, a15EnumChunk0217_eq,
    a15EnumChunk0218_eq, a15EnumChunk0219_eq, a15EnumChunk0220_eq,
    a15EnumChunk0221_eq, a15EnumChunk0222_eq, a15EnumChunk0223_eq,
    a15EnumChunk0224_eq, a15EnumChunk0225_eq, a15EnumChunk0226_eq,
    a15EnumChunk0227_eq, a15EnumChunk0228_eq, a15EnumChunk0229_eq,
    a15EnumChunk0230_eq, a15EnumChunk0231_eq, a15EnumChunk0232_eq,
    a15EnumChunk0233_eq, a15EnumChunk0234_eq, a15EnumChunk0235_eq,
    a15EnumChunk0236_eq, a15EnumChunk0237_eq, a15EnumChunk0238_eq,
    a15EnumChunk0239_eq]

end SRG266
