/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15EnumerationChunks.Chunk0361
import SRG266.Certificates.A15EnumerationChunks.Chunk0362
import SRG266.Certificates.A15EnumerationChunks.Chunk0363
import SRG266.Certificates.A15EnumerationChunks.Chunk0364
import SRG266.Certificates.A15EnumerationChunks.Chunk0365
import SRG266.Certificates.A15EnumerationChunks.Chunk0366
import SRG266.Certificates.A15EnumerationChunks.Chunk0367
import SRG266.Certificates.A15EnumerationChunks.Chunk0368
import SRG266.Certificates.A15EnumerationChunks.Chunk0369
import SRG266.Certificates.A15EnumerationChunks.Chunk0370
import SRG266.Certificates.A15EnumerationChunks.Chunk0371
import SRG266.Certificates.A15EnumerationChunks.Chunk0372
import SRG266.Certificates.A15EnumerationChunks.Chunk0373
import SRG266.Certificates.A15EnumerationChunks.Chunk0374
import SRG266.Certificates.A15EnumerationChunks.Chunk0375
import SRG266.Certificates.A15EnumerationChunks.Chunk0376
import SRG266.Certificates.A15EnumerationChunks.Chunk0377
import SRG266.Certificates.A15EnumerationChunks.Chunk0378
import SRG266.Certificates.A15EnumerationChunks.Chunk0379
import SRG266.Certificates.A15EnumerationChunks.Chunk0380
import SRG266.Certificates.A15EnumerationChunks.Chunk0381
import SRG266.Certificates.A15EnumerationChunks.Chunk0382
import SRG266.Certificates.A15EnumerationChunks.Chunk0383
import SRG266.Certificates.A15EnumerationChunks.Chunk0384
import SRG266.Certificates.A15EnumerationChunks.Chunk0385
import SRG266.Certificates.A15EnumerationChunks.Chunk0386
import SRG266.Certificates.A15EnumerationChunks.Chunk0387
import SRG266.Certificates.A15EnumerationChunks.Chunk0388
import SRG266.Certificates.A15EnumerationChunks.Chunk0389
import SRG266.Certificates.A15EnumerationChunks.Chunk0390

/-!
# Bounded A15 enumeration group 013

Chunks 0361 to 0390 of the
residue-2 branch, concatenated.  No search is evaluated here: the
chunk certificates are glued with `a15PolyExpand_append`, which distributes
`List.flatMap` over `++`.
-/

namespace SRG266

/-- Frontier states of group 013. -/
def a15EnumGroup013 : List A15MagState :=
    a15EnumChunk0361 ++ a15EnumChunk0362 ++ a15EnumChunk0363 ++
    a15EnumChunk0364 ++ a15EnumChunk0365 ++ a15EnumChunk0366 ++
    a15EnumChunk0367 ++ a15EnumChunk0368 ++ a15EnumChunk0369 ++
    a15EnumChunk0370 ++ a15EnumChunk0371 ++ a15EnumChunk0372 ++
    a15EnumChunk0373 ++ a15EnumChunk0374 ++ a15EnumChunk0375 ++
    a15EnumChunk0376 ++ a15EnumChunk0377 ++ a15EnumChunk0378 ++
    a15EnumChunk0379 ++ a15EnumChunk0380 ++ a15EnumChunk0381 ++
    a15EnumChunk0382 ++ a15EnumChunk0383 ++ a15EnumChunk0384 ++
    a15EnumChunk0385 ++ a15EnumChunk0386 ++ a15EnumChunk0387 ++
    a15EnumChunk0388 ++ a15EnumChunk0389 ++ a15EnumChunk0390

/-- The profiles emitted below group 013. -/
def a15EnumGroup013Out : List (Array ℤ) :=
    a15EnumChunk0361Out ++ a15EnumChunk0362Out ++ a15EnumChunk0363Out ++
    a15EnumChunk0364Out ++ a15EnumChunk0365Out ++ a15EnumChunk0366Out ++
    a15EnumChunk0367Out ++ a15EnumChunk0368Out ++ a15EnumChunk0369Out ++
    a15EnumChunk0370Out ++ a15EnumChunk0371Out ++ a15EnumChunk0372Out ++
    a15EnumChunk0373Out ++ a15EnumChunk0374Out ++ a15EnumChunk0375Out ++
    a15EnumChunk0376Out ++ a15EnumChunk0377Out ++ a15EnumChunk0378Out ++
    a15EnumChunk0379Out ++ a15EnumChunk0380Out ++ a15EnumChunk0381Out ++
    a15EnumChunk0382Out ++ a15EnumChunk0383Out ++ a15EnumChunk0384Out ++
    a15EnumChunk0385Out ++ a15EnumChunk0386Out ++ a15EnumChunk0387Out ++
    a15EnumChunk0388Out ++ a15EnumChunk0389Out ++ a15EnumChunk0390Out

theorem a15EnumGroup013_eq :
    a15PolyExpand 2 5 a15EnumGroup013 = a15EnumGroup013Out := by
  rw [a15EnumGroup013, a15EnumGroup013Out]
  simp only [a15PolyExpand_append, a15EnumChunk0361_eq, a15EnumChunk0362_eq,
    a15EnumChunk0363_eq, a15EnumChunk0364_eq, a15EnumChunk0365_eq,
    a15EnumChunk0366_eq, a15EnumChunk0367_eq, a15EnumChunk0368_eq,
    a15EnumChunk0369_eq, a15EnumChunk0370_eq, a15EnumChunk0371_eq,
    a15EnumChunk0372_eq, a15EnumChunk0373_eq, a15EnumChunk0374_eq,
    a15EnumChunk0375_eq, a15EnumChunk0376_eq, a15EnumChunk0377_eq,
    a15EnumChunk0378_eq, a15EnumChunk0379_eq, a15EnumChunk0380_eq,
    a15EnumChunk0381_eq, a15EnumChunk0382_eq, a15EnumChunk0383_eq,
    a15EnumChunk0384_eq, a15EnumChunk0385_eq, a15EnumChunk0386_eq,
    a15EnumChunk0387_eq, a15EnumChunk0388_eq, a15EnumChunk0389_eq,
    a15EnumChunk0390_eq]

end SRG266
