/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.A15EnumerationGroups.Group013
import SRG266.Certificates.A15EnumerationGroups.Group014
import SRG266.Certificates.A15EnumerationGroups.Group015
import SRG266.Certificates.A15EnumerationGroups.Group016
import SRG266.Certificates.A15EnumerationGroups.Group017
import SRG266.Certificates.A15EnumerationGroups.Group018
import SRG266.Certificates.A15EnumerationGroups.Group019
import SRG266.Certificates.A15EnumerationGroups.Group020
import SRG266.Certificates.A15EnumerationGroups.Group021
import SRG266.Certificates.A15EnumerationGroups.Group022
import SRG266.Certificates.A15EnumerationGroups.Group023
import SRG266.Certificates.A15EnumerationGroups.Group024
import SRG266.Certificates.A15EnumerationGroups.Group025

/-!
# The residue-2 branch of the A15 centroid enumeration

The 2927 magnitude-five frontier states of the residue-2 branch and the 1105
canonical profiles the branch emits.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- All magnitude-five frontier states of the residue-2 branch. -/
def a15Branch2Frontier : List A15MagState :=
    a15EnumGroup013 ++ a15EnumGroup014 ++ a15EnumGroup015 ++
    a15EnumGroup016 ++ a15EnumGroup017 ++ a15EnumGroup018 ++
    a15EnumGroup019 ++ a15EnumGroup020 ++ a15EnumGroup021 ++
    a15EnumGroup022 ++ a15EnumGroup023 ++ a15EnumGroup024 ++
    a15EnumGroup025

/-- The frontier is what the search reaches after twelve magnitude levels. -/
theorem a15Branch2Frontier_eq :
    a15Frontier 2 17 12 16 0 0 [] [] =
      a15Branch2Frontier := by
  decide +kernel

/-- The canonical profiles emitted by the residue-2 branch. -/
def a15Branch2Profiles : List (Array ℤ) :=
    a15EnumGroup013Out ++ a15EnumGroup014Out ++ a15EnumGroup015Out ++
    a15EnumGroup016Out ++ a15EnumGroup017Out ++ a15EnumGroup018Out ++
    a15EnumGroup019Out ++ a15EnumGroup020Out ++ a15EnumGroup021Out ++
    a15EnumGroup022Out ++ a15EnumGroup023Out ++ a15EnumGroup024Out ++
    a15EnumGroup025Out

theorem a15Branch2_eq :
    a15PolyEnumerateByMagnitudeAux 2 17 16 0 0 [] [] =
      a15Branch2Profiles := by
  have hsplit :
      a15PolyEnumerateByMagnitudeAux 2 17 16 0 0 [] [] =
        a15PolyExpand 2 5
          (a15Frontier 2 17 12 16 0 0 [] []) :=
    a15PolyEnumerateByMagnitudeAux_eq_frontier 2
      5 12 16 0 0 [] []
  rw [hsplit, a15Branch2Frontier_eq, a15Branch2Frontier, a15Branch2Profiles]
  simp only [a15PolyExpand_append, a15EnumGroup013_eq, a15EnumGroup014_eq,
    a15EnumGroup015_eq, a15EnumGroup016_eq, a15EnumGroup017_eq,
    a15EnumGroup018_eq, a15EnumGroup019_eq, a15EnumGroup020_eq,
    a15EnumGroup021_eq, a15EnumGroup022_eq, a15EnumGroup023_eq,
    a15EnumGroup024_eq, a15EnumGroup025_eq]

end SRG266
