/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

Generated by `scripts/generate_e7_concrete_expansion.py`.
Do not edit by hand.
-/
import SRG266.Certificates.E7ConcreteFilterCover.Chunk000
import SRG266.Certificates.E7ConcreteFilterCover.Chunk001
import SRG266.Certificates.E7ConcreteFilterCover.Chunk002
import SRG266.Certificates.E7ConcreteFilterCover.Chunk003
import SRG266.Certificates.E7ConcreteFilterCover.Chunk004
import SRG266.Certificates.E7ConcreteFilterCover.Chunk005
import SRG266.Certificates.E7ConcreteFilterCover.Chunk006
import SRG266.Certificates.E7ConcreteFilterCover.Chunk007
import SRG266.Certificates.E7ConcreteFilterCover.Chunk008
import SRG266.Certificates.E7ConcreteFilterCover.Chunk009
import SRG266.Certificates.E7ConcreteFilterCover.Chunk010
import SRG266.Certificates.E7ConcreteFilterCover.Chunk011
import SRG266.Certificates.E7ConcreteFilterCover.Chunk012
import SRG266.Certificates.E7ConcreteFilterCover.Chunk013
import SRG266.Certificates.E7ConcreteFilterCover.Chunk014
import SRG266.Certificates.E7ConcreteFilterCover.Chunk015
import SRG266.Certificates.E7ConcreteFilterCover.Chunk016
import SRG266.Certificates.E7ConcreteFilterCover.Chunk017
import SRG266.Certificates.E7ConcreteFilterCover.Chunk018
import SRG266.Certificates.E7ConcreteFilterCover.Chunk019
import SRG266.Certificates.E7ConcreteFilterCover.Chunk020
import SRG266.Certificates.E7ConcreteFilterCover.Chunk021
import SRG266.Certificates.E7ConcreteFilterCover.Chunk022
import SRG266.Certificates.E7ConcreteFilterCover.Chunk023
import SRG266.Certificates.E7ConcreteFilterCover.Chunk024
import SRG266.Certificates.E7ConcreteFilterCover.Chunk025
import SRG266.Certificates.E7ConcreteFilterCover.Chunk026
import SRG266.Certificates.E7ConcreteFilterCover.Chunk027
import SRG266.Certificates.E7ConcreteFilterCover.Chunk028
import SRG266.Certificates.E7ConcreteFilterCover.Chunk029
import SRG266.Certificates.E7ConcreteFilterCover.Chunk030
import SRG266.Certificates.E7ConcreteFilterCover.Chunk031
import SRG266.Certificates.E7ConcreteFilterCover.Chunk032
import SRG266.Certificates.E7ConcreteFilterCover.Chunk033
import SRG266.Certificates.E7ConcreteFilterCover.Chunk034
import SRG266.Certificates.E7ConcreteFilterCover.Chunk035
import SRG266.Certificates.E7ConcreteFilterCover.Chunk036

/-!
# Assembly of the concrete E7 filtering sweep

The chunk modules check the sweep below each frontier state.  This
module verifies the two prefixes above the frontiers and concludes that
`e7ConcreteRelevantProfiles` lists exactly the enumerated component
profiles carrying one of the listed component keys.

The chunk modules are deliberately outside the default build: each is a
multi-gigabyte kernel evaluation.  Use
`scripts/build_e7_concrete_chunks.py` to check them one at a time.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

private theorem e7ConcreteFrontierEven_checked :
    ∀ entry ∈ e7ConcreteFrontierEven,
      e7FilterAuxState e7ConcreteRelevant 0 entry.1 = entry.2 := by
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0000, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0001, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0002, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0003, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0004, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0005, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0006, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0007, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0008, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0009, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0010, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0011, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0012, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0013, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0014, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0015, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0016, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0017, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0018, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0019, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0020, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0021, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0022, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0023, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0024, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0025, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0026, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0027, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0028, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0029, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0030, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0031, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0032, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0033, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0034, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0035, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0036, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0037, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0038, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0039, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0040, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0041, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0042, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0043, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0044, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0045, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0046, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0047, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0048, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0049, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0050, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0051, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0052, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0053, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0054, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0055, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0056, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0057, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0058, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0059, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0060, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0061, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0062, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0063, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0064, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0065, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0066, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0067, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0068, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0069, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0070, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0071, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0072, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0073, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0074, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0075, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0076, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0077, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0078, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0079, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0080, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0081, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0082, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0083, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0084, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0085, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0086, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0087, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0088, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0089, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0090, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0091, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0092, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0093, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0094, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0095, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0096, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0097, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0098, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0099, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0100, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0101, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0102, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0103, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0104, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0105, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0106, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0107, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0108, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0109, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0110, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0111, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0112, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0113, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0114, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0115, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0116, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0117, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0118, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0119, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0120, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0121, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0122, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0123, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0124, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0125, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0126, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0127, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0128, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0129, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0130, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0131, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0132, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0133, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0134, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0135, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0136, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0137, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0138, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0139, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0140, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0141, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0142, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0143, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0144, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0145, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0146, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0147, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0148, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0149, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0150, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkEven0151, ?_⟩
  exact List.forall_mem_nil _

private theorem e7ConcretePrefixEven_checked :
    e7FilterPrefix e7ConcreteRelevant e7ConcreteFrontierEven 0
        17 8 0 0 [] [] = e7ConcreteRelevantEven := by
  decide +kernel

/-- The even filtering sweep keeps exactly the listed profiles. -/
theorem e7ConcreteFilterEven_checked :
    e7FilterAux e7ConcreteRelevant 0 17 8 0 0 [] [] =
      e7ConcreteRelevantEven := by
  rw [← e7FilterAux_of_prefix e7ConcreteRelevant e7ConcreteFrontierEven 0
    e7ConcreteFrontierEven_checked 17 8 0 0 [] []]
  exact e7ConcretePrefixEven_checked

private theorem e7ConcreteFrontierOdd_checked :
    ∀ entry ∈ e7ConcreteFrontierOdd,
      e7FilterAuxState e7ConcreteRelevant 1 entry.1 = entry.2 := by
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0000, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0001, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0002, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0003, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0004, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0005, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0006, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0007, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0008, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0009, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0010, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0011, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0012, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0013, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0014, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0015, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0016, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0017, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0018, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0019, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0020, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0021, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0022, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0023, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0024, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0025, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0026, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0027, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0028, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0029, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0030, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0031, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0032, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0033, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0034, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0035, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0036, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0037, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0038, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0039, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0040, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0041, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0042, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0043, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0044, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0045, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0046, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0047, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0048, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0049, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0050, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0051, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0052, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0053, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0054, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0055, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0056, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0057, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0058, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0059, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0060, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0061, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0062, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0063, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0064, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0065, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0066, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0067, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0068, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0069, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0070, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0071, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0072, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0073, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0074, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0075, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0076, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0077, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0078, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0079, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0080, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0081, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0082, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0083, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0084, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0085, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0086, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0087, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0088, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0089, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0090, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0091, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0092, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0093, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0094, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0095, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0096, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0097, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0098, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0099, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0100, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0101, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0102, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0103, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0104, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0105, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0106, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0107, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0108, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0109, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0110, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0111, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0112, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0113, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0114, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0115, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0116, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0117, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0118, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0119, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0120, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0121, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0122, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0123, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0124, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0125, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0126, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0127, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0128, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0129, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0130, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0131, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0132, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0133, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0134, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0135, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0136, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0137, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0138, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0139, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0140, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0141, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0142, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0143, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0144, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0145, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0146, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0147, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0148, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0149, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0150, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0151, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0152, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0153, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0154, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0155, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0156, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0157, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0158, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0159, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0160, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0161, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0162, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0163, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0164, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0165, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0166, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0167, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0168, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0169, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0170, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0171, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0172, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0173, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0174, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0175, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0176, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0177, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0178, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0179, ?_⟩
  refine List.forall_mem_cons.mpr ⟨e7ConcreteChunkOdd0180, ?_⟩
  exact List.forall_mem_nil _

private theorem e7ConcretePrefixOdd_checked :
    e7FilterPrefix e7ConcreteRelevant e7ConcreteFrontierOdd 1
        17 8 0 0 [] [] = e7ConcreteRelevantOdd := by
  decide +kernel

/-- The odd filtering sweep keeps exactly the listed profiles. -/
theorem e7ConcreteFilterOdd_checked :
    e7FilterAux e7ConcreteRelevant 1 17 8 0 0 [] [] =
      e7ConcreteRelevantOdd := by
  rw [← e7FilterAux_of_prefix e7ConcreteRelevant e7ConcreteFrontierOdd 1
    e7ConcreteFrontierOdd_checked 17 8 0 0 [] []]
  exact e7ConcretePrefixOdd_checked

/-- The enumerated profiles carrying a listed component key are exactly
the listed ones. -/
theorem e7ConcreteRelevantProfiles_checked :
    e7EnumeratedComponentProfiles.filter e7ConcreteRelevant =
      e7ConcreteRelevantProfiles := by
  rw [e7EnumeratedComponentProfiles_filter, e7ConcreteFilterEven_checked,
    e7ConcreteFilterOdd_checked]
  rfl

end SRG266
