/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_e7_sixg_sixs_psd.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.E7Residual

/-!
# Critical shell data for the residual E7 `6g × 6s` case

This lightweight module contains the shell enumeration and critical matrix.
The LDLᵀ factor is isolated in `E7SixGenericSixSpecialPSDBase`.
-/

open scoped Matrix

namespace SRG266
namespace E7SixGenericSixSpecialData

set_option maxRecDepth 100000

def d₆g : Fin 8 → ℤ :=
  ![-4, 0, 0, 0, 0, 0, 2, 2]

def d₆s : Fin 8 → ℤ :=
  ![-3, -3, 1, 1, 1, 1, 1, 1]

abbrev Shell := E7ResidualEligibleIndex d₆g d₆s

def criticalVertices : List E7ShellIndex :=
[
  ((false, ⟨7, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨8, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨9, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨10, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨13, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨14, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨15, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨18, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨19, by decide⟩), (true, ⟨0, by decide⟩)),
  ((false, ⟨22, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨7, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨8, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨9, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨10, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨13, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨14, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨15, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨18, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨19, by decide⟩), (true, ⟨0, by decide⟩)),
  ((true, ⟨22, by decide⟩), (true, ⟨0, by decide⟩))
]

abbrev CriticalIndex := Fin criticalVertices.length

instance : Nonempty CriticalIndex :=
  ⟨⟨0, by decide⟩⟩

theorem criticalVertex_eligible (i : CriticalIndex) :
    e7ResidualEligible d₆g d₆s (criticalVertices.get i) := by
  decide +kernel +revert

def criticalVertex (i : CriticalIndex) : Shell :=
  ⟨criticalVertices.get i, criticalVertex_eligible i⟩

abbrev CriticalShell :=
  {w : Shell // e7ResidualEvaluation d₆g w.1.1 = 0}

instance : Fintype CriticalShell :=
  Fintype.subtype
    (Finset.univ.filter fun w =>
      e7ResidualEvaluation d₆g w.1.1 = 0)
    (by simp)

theorem criticalVertex_label (i : CriticalIndex) :
    e7ResidualEvaluation d₆g (criticalVertex i).1.1 = 0 := by
  decide +kernel +revert

def criticalToFun (i : CriticalIndex) : CriticalShell :=
  ⟨criticalVertex i, criticalVertex_label i⟩

def criticalC : Matrix CriticalIndex CriticalIndex ℕ :=
  fun i j =>
    (if e7ShellInner (criticalVertex i).1 (criticalVertex j).1 = 2
      then 1 else 0) +
    if i = j then 3 else 0

def centeredMatrix : Matrix CriticalIndex CriticalIndex ℚ :=
  fun i j => 20 * criticalC i j - 12

theorem criticalIndex_card : Fintype.card CriticalIndex = 20 := by
  rfl

end E7SixGenericSixSpecialData
end SRG266
