/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_e7_sixg_sixs_psd.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7SixGenericSixSpecialCriticalLeftCard
import SRG266.Certificates.E7SixGenericSixSpecialCriticalRightCard

/-!
# Bounded shell bijection for the `6g × 6s` E7 residual case

This finite check is isolated from the large rational matrix data so it can
be compiled and audited independently.
-/

namespace SRG266
namespace E7SixGenericSixSpecialData

set_option maxRecDepth 100000

private theorem criticalToFun_injective :
    Function.Injective criticalToFun := by
  intro i j
  revert i j
  decide +kernel

private theorem criticalShell_card : Fintype.card CriticalShell = 20 := by
  calc
    Fintype.card CriticalShell =
        Fintype.card (CriticalLeft × CriticalRight) :=
      Fintype.card_congr criticalShellProductEquiv.symm
    _ = Fintype.card CriticalLeft * Fintype.card CriticalRight :=
      Fintype.card_prod _ _
    _ = 20 := by rw [criticalLeft_card, criticalRight_card]

theorem criticalToFun_bijective :
    Function.Bijective criticalToFun := by
  exact (Fintype.bijective_iff_injective_and_card _).mpr
    ⟨criticalToFun_injective,
      criticalIndex_card.trans criticalShell_card.symm⟩

noncomputable def criticalEquiv : CriticalIndex ≃ CriticalShell :=
  Equiv.ofBijective criticalToFun criticalToFun_bijective

@[simp] theorem criticalEquiv_apply (i : CriticalIndex) :
    (criticalEquiv i).1 = criticalVertex i := by
  rfl

end E7SixGenericSixSpecialData
end SRG266
