/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_e7_sixg_components.py`.
Do not edit it by hand.
-/
import SRG266.Certificates.E7SixGenericPositionBijective
import SRG266.Certificates.E7SixGenericComponentSide
import SRG266.Certificates.E7SixGenericComponentCross

/-!
# Checked negative components for the `6g × 6g` residual shell
-/

namespace SRG266

set_option maxRecDepth 100000


noncomputable def e7SixGenericPositionEquiv :
    E7SixGenericPosition ≃ E7SixGenericShell :=
  Equiv.ofBijective e7SixGenericPositionVertex
    e7SixGenericPositionVertex_bijective

noncomputable def e7SixGenericOwner
    (w : E7SixGenericShell) : E7SixGenericComponentIndex :=
  (e7SixGenericPositionEquiv.symm w).1

theorem e7SixGeneric_mem_iff_owner
    (k : E7SixGenericComponentIndex) (w : E7SixGenericShell) :
    w ∈ e7SixGenericComponent k ↔ e7SixGenericOwner w = k := by
  constructor
  · intro hw
    unfold e7SixGenericComponent at hw
    rw [Finset.mem_image] at hw
    obtain ⟨j, -, rfl⟩ := hw
    change (e7SixGenericPositionEquiv.symm
      (e7SixGenericPositionEquiv (k, j))).1 = k
    rw [Equiv.symm_apply_apply]
  · intro hw
    let p := e7SixGenericPositionEquiv.symm w
    have hp : p.1 = k := hw
    unfold e7SixGenericComponent
    rw [Finset.mem_image]
    refine ⟨p.2, Finset.mem_univ _, ?_⟩
    change e7SixGenericPositionEquiv (k, p.2) = w
    rw [← hp]
    exact e7SixGenericPositionEquiv.apply_symm_apply w

/-- The `6g × 6g` residual shell cannot contain the required packing. -/
theorem no_e7SixGenericSixGeneric_packing :
    IsEmpty
      (E7ShellPacking e7SixGenericProfile e7SixGenericProfile) := by
  apply no_e7ShellPacking_of_bipartite_components
    e7SixGenericComponent e7SixGenericOwner e7SixGenericSide
  · exact e7SixGeneric_mem_iff_owner
  · exact e7SixGenericComponent_side_card
  · exact e7SixGenericComponent_cross_negative
  · exact e7SixGenericComponentCount.le

end SRG266
