/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A10

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA10Reflection0Pairing : ∀ a,
    certA10ReflectPairing ⟨0, by decide⟩ a =
      adeSimplePairing (ADEType.A 10) (certA10Roots a) ⟨0, by decide⟩ := by
  decide +kernel

theorem certA10Reflection0ChangedBound : ∀ a,
    -6 ≤ certA10Roots a ⟨0, by decide⟩ -
        certA10ReflectPairing ⟨0, by decide⟩ a ∧
      certA10Roots a ⟨0, by decide⟩ -
        certA10ReflectPairing ⟨0, by decide⟩ a ≤ 6 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
