/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A13

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA13SimpleCheck : ∀ i j, certA13Roots (certA13Simple i) j =
    ((Pi.single i (1 : ℤ)) : Fin (ADEType.A 13).rank → ℤ) j := by
  decide +kernel

theorem certA13NegCheck : ∀ a j,
    certA13Roots (certA13Neg a) j = -certA13Roots a j := by
  decide +kernel

theorem certA13CoordinateBound : ∀ a i,
    -6 ≤ certA13Roots a i ∧ certA13Roots a i ≤ 6 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
