/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A1

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA1Reflection0Pairing : ∀ a,
    certA1ReflectPairing ⟨0, by decide⟩ a =
      adeSimplePairing (ADEType.A 1) (certA1Roots a) ⟨0, by decide⟩ := by
  decide +kernel

theorem certA1Reflection0ChangedBound : ∀ a,
    -6 ≤ certA1Roots a ⟨0, by decide⟩ -
        certA1ReflectPairing ⟨0, by decide⟩ a ∧
      certA1Roots a ⟨0, by decide⟩ -
        certA1ReflectPairing ⟨0, by decide⟩ a ≤ 6 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
