/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A2

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA2FingerprintEq : ∀ a : Fin 6,
    certA2Fingerprint a = rootVectorFingerprint (certA2Roots a) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
