/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A2

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA2Reflection1Fingerprint : ∀ a,
    certA2Fingerprint (certA2Reflect ⟨1, by decide⟩ a) =
      rootVectorFingerprint
        (adeCoordinateReflectionWithPairing ⟨1, by decide⟩
          (certA2ReflectPairing ⟨1, by decide⟩ a) (certA2Roots a)) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
