/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A4

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA4FingerprintEq : ∀ a : Fin 20,
    certA4Fingerprint a = rootVectorFingerprint (certA4Roots a) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
