/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.A6

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certA6Norm : ∀ a : Fin 42,
    Matrix.toBilin' (ADEType.A 6).gram (certA6Roots a) (certA6Roots a) = 2 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
