/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.D13

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certD13Reflection5Pairing : ∀ a,
    certD13ReflectPairing ⟨5, by decide⟩ a =
      adeSimplePairing (ADEType.D 13) (certD13Roots a) ⟨5, by decide⟩ := by
  decide +kernel

theorem certD13Reflection5ChangedBound : ∀ a,
    -6 ≤ certD13Roots a ⟨5, by decide⟩ -
        certD13ReflectPairing ⟨5, by decide⟩ a ∧
      certD13Roots a ⟨5, by decide⟩ -
        certD13ReflectPairing ⟨5, by decide⟩ a ≤ 6 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
