/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.D4

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certD4FingerprintEq : ∀ a : Fin 24,
    certD4Fingerprint a = rootVectorFingerprint (certD4Roots a) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
