/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.D4

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certD4Reflection1Fingerprint : ∀ a,
    certD4Fingerprint (certD4Reflect ⟨1, by decide⟩ a) =
      rootVectorFingerprint
        (adeCoordinateReflectionWithPairing ⟨1, by decide⟩
          (certD4ReflectPairing ⟨1, by decide⟩ a) (certD4Roots a)) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
