/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.D6

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certD6Norm : ∀ a : Fin 60,
    Matrix.toBilin' (ADEType.D 6).gram (certD6Roots a) (certD6Roots a) = 2 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
