/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.D7

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certD7Reflection2Fingerprint : ∀ a,
    certD7Fingerprint (certD7Reflect ⟨2, by decide⟩ a) =
      rootVectorFingerprint
        (adeCoordinateReflectionWithPairing ⟨2, by decide⟩
          (certD7ReflectPairing ⟨2, by decide⟩ a) (certD7Roots a)) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
