/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.E7

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certE7Reflection0Fingerprint : ∀ a,
    certE7Fingerprint (certE7Reflect ⟨0, by decide⟩ a) =
      rootVectorFingerprint
        (adeCoordinateReflectionWithPairing ⟨0, by decide⟩
          (certE7ReflectPairing ⟨0, by decide⟩ a) (certE7Roots a)) := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
