/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Data.E8

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

theorem certE8Norm : ∀ a : Fin 240,
    Matrix.toBilin' (ADEType.E8).gram (certE8Roots a) (certE8Roots a) = 2 := by
  decide +kernel

end ADERootOrbitData
end Lattice
end SRG266
