/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

Generated by `scripts/generate_e7_scalar_pair_data.py`.
Do not edit by hand.
-/
import SRG266.Hosts.E7ScalarPairFilter
import SRG266.Hosts.E7CentroidKeyCodes

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

theorem e7CodeBucketChecked : e7CodeBucketOk = true := by
  decide +kernel

theorem e7CandidatePairCheck019 : e7CandidatePairCheckAt 19 = true := by
  decide +kernel

theorem e7CandidatePairCheck020 : e7CandidatePairCheckAt 20 = true := by
  decide +kernel

theorem e7CandidatePairCheck021 : e7CandidatePairCheckAt 21 = true := by
  decide +kernel

theorem e7CandidatePairCheck022 : e7CandidatePairCheckAt 22 = true := by
  decide +kernel

theorem e7CandidatePairCheck023 : e7CandidatePairCheckAt 23 = true := by
  decide +kernel

theorem e7CandidatePairCheck024 : e7CandidatePairCheckAt 24 = true := by
  decide +kernel

theorem e7CandidatePairCheck025 : e7CandidatePairCheckAt 25 = true := by
  decide +kernel

theorem e7CandidatePairCheck026 : e7CandidatePairCheckAt 26 = true := by
  decide +kernel

theorem e7CandidatePairCheck027 : e7CandidatePairCheckAt 27 = true := by
  decide +kernel

theorem e7CandidatePairCheck028 : e7CandidatePairCheckAt 28 = true := by
  decide +kernel

end SRG266
