/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

Generated by `scripts/generate_e7_component_key_data.py`.
Do not edit by hand.
-/
import SRG266.Certificates.E7ComponentKeyData

namespace SRG266

set_option maxRecDepth 4000000

theorem e7CoverChunkEven0167 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨7, 6, -18, 164, [-10, -8], []⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0168 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨7, 5, -10, 228, [-10, -8], [8]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0169 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨7, 4, -2, 292, [-10, -8], [8, 8]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0170 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨7, 5, -26, 228, [-10, -8, -8], []⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0171 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨7, 4, -18, 292, [-10, -8, -8], [8]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0172 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨8, 6, -1, 181, [-10], [9]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0173 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨8, 5, 8, 262, [-10], [9, 9]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0174 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨8, 6, -19, 181, [-10, -9], []⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0175 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨8, 5, -10, 262, [-10, -9], [9]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0176 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨8, 5, -28, 262, [-10, -9, -9], []⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0177 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨9, 6, 0, 200, [-10], [10]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0178 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨9, 5, 10, 300, [-10], [10, 10]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0179 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨9, 6, -20, 200, [-10, -10], []⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0180 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨9, 5, -10, 300, [-10, -10], [10]⟩ : E7CoverState) = true := by
  decide +kernel

theorem e7CoverChunkEven0181 :
    e7CoverAuxState e7ProfileKeyListed 0
        (⟨9, 5, -30, 300, [-10, -10, -10], []⟩ : E7CoverState) = true := by
  decide +kernel

end SRG266
