/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG0B10P2A4 : List NearOrbitWitness := [
  { mask := 524237950988964, representativeIndex := 2, representative := 520941572011148, permutationCode := 16205392 },
  { mask := 524246272234148, representativeIndex := 4, representative := 522041075217556, permutationCode := 14599816 },
  { mask := 541675652428452, representativeIndex := 4, representative := 522041075217556, permutationCode := 16434768 },
  { mask := 541701018804900, representativeIndex := 2, representative := 520941572011148, permutationCode := 16434705 },
  { mask := 547327694484132, representativeIndex := 1, representative := 520941320360588, permutationCode := 12535376 },
  { mask := 547329573474980, representativeIndex := 3, representative := 521903393006220, permutationCode := 12535376 },
  { mask := 548288827634340, representativeIndex := 3, representative := 521903393006220, permutationCode := 12306056 },
  { mask := 548291646120612, representativeIndex := 1, representative := 520941320360588, permutationCode := 14599697 },
  { mask := 550196867289764, representativeIndex := 2, representative := 520941572011148, permutationCode := 14141064 },
  { mask := 550212972925604, representativeIndex := 1, representative := 520941320360588, permutationCode := 12306056 },
  { mask := 550213912421028, representativeIndex := 0, representative := 520939441369740, permutationCode := 12306056 },
  { mask := 1009115075451556, representativeIndex := 1, representative := 520941320360588, permutationCode := 6565181 },
  { mask := 1009130711339684, representativeIndex := 3, representative := 521903393006220, permutationCode := 2895340 },
  { mask := 1010083523244708, representativeIndex := 7, representative := 930927032754572, permutationCode := 2206652 },
  { mask := 1010091844489892, representativeIndex := 7, representative := 930927032754572, permutationCode := 10211859 },
  { mask := 1016605498192548, representativeIndex := 8, representative := 936556652745356, permutationCode := 12534466 },
  { mask := 1026552776891044, representativeIndex := 3, representative := 521903393006220, permutationCode := 4557301 },
  { mask := 1026560091533988, representativeIndex := 7, representative := 930927032754572, permutationCode := 14054425 },
  { mask := 1026584518415012, representativeIndex := 7, representative := 930927032754572, permutationCode := 13824643 },
  { mask := 1026585457910436, representativeIndex := 4, representative := 522041075217556, permutationCode := 13881497 },
  { mask := 1039672693797540, representativeIndex := 6, representative := 929966025429644, permutationCode := 13825049 },
  { mask := 1039681015042724, representativeIndex := 7, representative := 930927032754572, permutationCode := 10440857 },
  { mask := 1039695241687716, representativeIndex := 8, representative := 936556652745356, permutationCode := 16147152 },
  { mask := 1039697120678564, representativeIndex := 7, representative := 930927032754572, permutationCode := 2723630 },
  { mask := 1042564414493348, representativeIndex := 4, representative := 522041075217556, permutationCode := 11760840 },
  { mask := 1042581459624612, representativeIndex := 2, representative := 520941572011148, permutationCode := 10155033 },
  { mask := 1563268684192420, representativeIndex := 3, representative := 521903393006220, permutationCode := 2722237 },
  { mask := 1563275998835364, representativeIndex := 4, representative := 522041075217556, permutationCode := 11789008 },
  { mask := 1564237131985572, representativeIndex := 7, representative := 930927032754572, permutationCode := 10211418 },
  { mask := 1572758346846884, representativeIndex := 6, representative := 929966025429644, permutationCode := 15917594 },
  { mask := 1579280321794724, representativeIndex := 7, representative := 930927032754572, permutationCode := 16146970 },
  { mask := 1587326875480740, representativeIndex := 7, representative := 930927032754572, permutationCode := 4558127 },
  { mask := 1589219279248036, representativeIndex := 1, representative := 520941320360588, permutationCode := 6823733 },
  { mask := 1589234915136164, representativeIndex := 8, representative := 936556652745356, permutationCode := 12305601 },
  { mask := 1589251020772004, representativeIndex := 8, representative := 936556652745356, permutationCode := 14054600 },
  { mask := 1589251960267428, representativeIndex := 2, representative := 520941572011148, permutationCode := 10412570 },
  { mask := 1593826302538404, representativeIndex := 7, representative := 930927032754572, permutationCode := 10441739 },
  { mask := 1593848850428580, representativeIndex := 7, representative := 930927032754572, permutationCode := 15918147 },
  { mask := 1596709701989028, representativeIndex := 3, representative := 521903393006220, permutationCode := 4988844 },
  { mask := 1596735068365476, representativeIndex := 4, representative := 522041075217556, permutationCode := 14569681 },
  { mask := 1602347517399716, representativeIndex := 7, representative := 930927032754572, permutationCode := 4299764 },
  { mask := 2486836154604196, representativeIndex := 2, representative := 520941572011148, permutationCode := 6565181 },
  { mask := 2486867896128164, representativeIndex := 4, representative := 522041075217556, permutationCode := 2895340 },
  { mask := 2487797287754404, representativeIndex := 4, representative := 522041075217556, permutationCode := 4557301 },
  { mask := 2487812923642532, representativeIndex := 7, representative := 930927032754572, permutationCode := 6364463 },
  { mask := 2487827150287524, representativeIndex := 7, representative := 930927032754572, permutationCode := 2895207 },
  { mask := 2487829968773796, representativeIndex := 3, representative := 521903393006220, permutationCode := 15945937 },
  { mask := 2494326577345188, representativeIndex := 8, representative := 936556652745356, permutationCode := 10211481 },
  { mask := 2494334898590372, representativeIndex := 7, representative := 930927032754572, permutationCode := 15917265 },
  { mask := 2494349125235364, representativeIndex := 6, representative := 929966025429644, permutationCode := 12535376 },
  { mask := 2494351004226212, representativeIndex := 7, representative := 930927032754572, permutationCode := 2951669 },
  { mask := 2504303718576804, representativeIndex := 7, representative := 930927032754572, permutationCode := 12305601 },
  { mask := 2504305597567652, representativeIndex := 7, representative := 930927032754572, permutationCode := 6822333 },
  { mask := 2517416320840356, representativeIndex := 8, representative := 936556652745356, permutationCode := 12535376 },
  { mask := 2520301599281828, representativeIndex := 3, representative := 521903393006220, permutationCode := 13825112 },
  { mask := 2520302538777252, representativeIndex := 1, representative := 520941320360588, permutationCode := 13825049 },
  { mask := 2619752188523172, representativeIndex := 7, representative := 930927032754572, permutationCode := 13824202 },
  { mask := 2625374368045732, representativeIndex := 4, representative := 522041075217556, permutationCode := 2722237 },
  { mask := 2625404230578852, representativeIndex := 3, representative := 521903393006220, permutationCode := 15917720 },
  { mask := 2628257767496356, representativeIndex := 2, representative := 520941572011148, permutationCode := 6823733 },
  { mask := 2628273403384484, representativeIndex := 8, representative := 936556652745356, permutationCode := 14055041 },
  { mask := 2628289509020324, representativeIndex := 8, representative := 936556652745356, permutationCode := 12306056 },
  { mask := 2628290448515748, representativeIndex := 1, representative := 520941320360588, permutationCode := 15917594 },
  { mask := 2632864790786724, representativeIndex := 7, representative := 930927032754572, permutationCode := 6336302 },
  { mask := 2632887338676900, representativeIndex := 7, representative := 930927032754572, permutationCode := 6564341 },
  { mask := 2634811483968164, representativeIndex := 7, representative := 930927032754572, permutationCode := 12534466 },
  { mask := 2642841932018340, representativeIndex := 7, representative := 930927032754572, permutationCode := 5015997 },
  { mask := 2644766077309604, representativeIndex := 6, representative := 929966025429644, permutationCode := 12306056 },
  { mask := 2657878679573156, representativeIndex := 7, representative := 930927032754572, permutationCode := 4988774 },
  { mask := 2658837933732516, representativeIndex := 4, representative := 522041075217556, permutationCode := 4988844 },
  { mask := 2658840752218788, representativeIndex := 3, representative := 521903393006220, permutationCode := 10440857 },
  { mask := 2689013980600996, representativeIndex := 1, representative := 520941320360588, permutationCode := 4471614 },
  { mask := 2689021295243940, representativeIndex := 3, representative := 521903393006220, permutationCode := 572404 },
  { mask := 2695604607916708, representativeIndex := 2, representative := 520941572011148, permutationCode := 4471614 },
  { mask := 2695634470449828, representativeIndex := 4, representative := 522041075217556, permutationCode := 572404 },
  { mask := 2697526874217124, representativeIndex := 0, representative := 520939441369740, permutationCode := 860076 },
  { mask := 2697542510105252, representativeIndex := 1, representative := 520941320360588, permutationCode := 2207100 },
  { mask := 2697558615741092, representativeIndex := 2, representative := 520941572011148, permutationCode := 2207100 },
  { mask := 2705017296958116, representativeIndex := 1, representative := 520941320360588, permutationCode := 4300660 },
  { mask := 2705025618203300, representativeIndex := 3, representative := 521903393006220, permutationCode := 342972 },
  { mask := 2728107040453284, representativeIndex := 2, representative := 520941572011148, permutationCode := 4300660 },
  { mask := 2728108919444132, representativeIndex := 4, representative := 522041075217556, permutationCode := 342972 },
]

def nearOrbitMasksG0B10P2A4 : List ℕ :=
  nearOrbitWitnessesG0B10P2A4.map NearOrbitWitness.mask

end SRG266.Certificates
