/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG1B8P0E8 : List NearOrbitWitness := [
  { mask := 554855841767656, representativeIndex := 69, representative := 554587422900440, permutationCode := 14599816 },
  { mask := 554862284021992, representativeIndex := 68, representative := 554580980646104, permutationCode := 14599816 },
  { mask := 946442845397224, representativeIndex := 135, representative := 946442845397224, permutationCode := 16434824 },
  { mask := 969502726359272, representativeIndex := 162, representative := 969502726359272, permutationCode := 16434824 },
  { mask := 969510041002216, representativeIndex := 163, representative := 969510041002216, permutationCode := 16434824 },
  { mask := 969518362247400, representativeIndex := 167, representative := 969518362247400, permutationCode := 16434824 },
  { mask := 969532588892392, representativeIndex := 171, representative := 969526865939240, permutationCode := 16434817 },
  { mask := 976993149100264, representativeIndex := 183, representative := 976993149100264, permutationCode := 16434824 },
  { mask := 1368655310266600, representativeIndex := 131, representative := 944245717975256, permutationCode := 14599816 },
  { mask := 1368657189257448, representativeIndex := 130, representative := 944243838984408, permutationCode := 14599816 },
  { mask := 1391722505871592, representativeIndex := 149, representative := 960722286264536, permutationCode := 14599816 },
  { mask := 1399205613969640, representativeIndex := 181, representative := 976718287978712, permutationCode := 14599816 },
  { mask := 1507193523708136, representativeIndex := 86, representative := 805707504533720, permutationCode := 14599816 },
  { mask := 1523663649743080, representativeIndex := 94, representative := 828781142393048, permutationCode := 14599816 },
  { mask := 1523686197633256, representativeIndex := 97, representative := 828789646084888, permutationCode := 14599809 },
  { mask := 1576462630428904, representativeIndex := 41, representative := 522041635168660, permutationCode := 14570689 },
  { mask := 1593893889614056, representativeIndex := 218, representative := 1039471862005976, permutationCode := 14599816 },
  { mask := 1593900331868392, representativeIndex := 216, representative := 1039465419751640, permutationCode := 14599816 },
  { mask := 1602413225484520, representativeIndex := 206, representative := 1030952526135512, permutationCode := 14599816 },
  { mask := 1602415104475368, representativeIndex := 204, representative := 1030950647144664, permutationCode := 14599816 },
  { mask := 2631963930069224, representativeIndex := 53, representative := 538513508077908, permutationCode := 14570696 },
  { mask := 2631971244712168, representativeIndex := 57, representative := 538516704040020, permutationCode := 14570696 },
  { mask := 2631976747471080, representativeIndex := 51, representative := 538507070017748, permutationCode := 14570696 },
  { mask := 2631993792602344, representativeIndex := 59, representative := 538518203457940, permutationCode := 14570689 },
  { mask := 2632932377862376, representativeIndex := 221, representative := 1039678196585060, permutationCode := 16405704 },
  { mask := 2632938820116712, representativeIndex := 220, representative := 1039671754330724, permutationCode := 16405704 },
  { mask := 2634854644162792, representativeIndex := 203, representative := 1030884251243604, permutationCode := 14570696 },
  { mask := 2634862965407976, representativeIndex := 201, representative := 1030882120602196, permutationCode := 14570696 },
  { mask := 2649431494041832, representativeIndex := 280, representative := 2517209046794456, permutationCode := 14599816 },
  { mask := 2657944387657960, representativeIndex := 268, representative := 2508627878286420, permutationCode := 14570696 },
]

def nearOrbitMasksG1B8P0E8 : List ℕ :=
  nearOrbitWitnessesG1B8P0E8.map NearOrbitWitness.mask

end SRG266.Certificates
