/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG1B9P164 : List NearOrbitWitness := [
  { mask := 524236885696868, representativeIndex := 42, representative := 522042012644500, permutationCode := 14599809 },
  { mask := 524245206942052, representativeIndex := 40, representative := 522037879284052, permutationCode := 14599816 },
  { mask := 541674587136356, representativeIndex := 67, representative := 541674587136356, permutationCode := 16434824 },
  { mask := 547309584060772, representativeIndex := 53, representative := 538513508077908, permutationCode := 14599816 },
  { mask := 547310523556196, representativeIndex := 56, representative := 538516326564180, permutationCode := 14599816 },
  { mask := 547312402547044, representativeIndex := 54, representative := 538514447573332, permutationCode := 14599816 },
  { mask := 547326629192036, representativeIndex := 60, representative := 538518580933780, permutationCode := 14599809 },
  { mask := 548271656706404, representativeIndex := 64, representative := 541399726014804, permutationCode := 14599816 },
  { mask := 550195801997668, representativeIndex := 61, representative := 539475580723540, permutationCode := 14599816 },
  { mask := 939852218081636, representativeIndex := 126, representative := 939852218081636, permutationCode := 16434824 },
  { mask := 939860539326820, representativeIndex := 127, representative := 939854283713316, permutationCode := 16434817 },
  { mask := 956321471727972, representativeIndex := 143, representative := 956321471727972, permutationCode := 16434824 },
  { mask := 956328786370916, representativeIndex := 144, representative := 956328786370916, permutationCode := 16434824 },
  { mask := 963811894468964, representativeIndex := 154, representative := 963811894468964, permutationCode := 16434824 },
  { mask := 970402521784676, representativeIndex := 174, representative := 970402521784676, permutationCode := 16434824 },
  { mask := 970408964039012, representativeIndex := 175, representative := 970408964039012, permutationCode := 16434824 },
  { mask := 972333109330276, representativeIndex := 180, representative := 972333109330276, permutationCode := 16434824 },
  { mask := 1362064682951012, representativeIndex := 119, representative := 931064463343956, permutationCode := 14599816 },
  { mask := 1378527494343012, representativeIndex := 139, representative := 954122465315156, permutationCode := 14599816 },
  { mask := 1378541251240292, representativeIndex := 141, representative := 954131658948948, permutationCode := 14599816 },
  { mask := 1378543130231140, representativeIndex := 140, representative := 954129779958100, permutationCode := 14599816 },
  { mask := 1378557356876132, representativeIndex := 142, representative := 954133976231188, permutationCode := 14599809 },
  { mask := 1386017917084004, representativeIndex := 173, representative := 970134102917460, permutationCode := 14599816 },
  { mask := 1386024359338340, representativeIndex := 172, representative := 970127660663124, permutationCode := 14599816 },
  { mask := 1392614986654052, representativeIndex := 153, representative := 963537033347412, permutationCode := 14599816 },
  { mask := 1394539131945316, representativeIndex := 152, representative := 961612888056148, permutationCode := 14599816 },
  { mask := 1494005826822500, representativeIndex := 84, representative := 799118942849812, permutationCode := 14599809 },
  { mask := 1517079464681828, representativeIndex := 88, representative := 815593445507412, permutationCode := 14599816 },
  { mask := 1517095570317668, representativeIndex := 89, representative := 815595511139092, permutationCode := 14599809 },
  { mask := 1526478396825956, representativeIndex := 98, representative := 829673623175508, permutationCode := 14599816 },
  { mask := 1533075466396004, representativeIndex := 90, representative := 823076553605460, permutationCode := 14599816 },
  { mask := 1563274933543268, representativeIndex := 132, representative := 944246158363736, permutationCode := 14570696 },
  { mask := 1569872003113316, representativeIndex := 136, representative := 946443034135144, permutationCode := 16405704 },
  { mask := 1587309704552804, representativeIndex := 196, representative := 1026284165120340, permutationCode := 14599816 },
  { mask := 1589233849844068, representativeIndex := 193, representative := 1024360019829076, permutationCode := 14599816 },
  { mask := 1593825237246308, representativeIndex := 213, representative := 1039403209638228, permutationCode := 14599816 },
  { mask := 1593831679500644, representativeIndex := 212, representative := 1039396767383892, permutationCode := 14599816 },
  { mask := 1602344573116772, representativeIndex := 202, representative := 1030883873767764, permutationCode := 14599816 },
  { mask := 1602346452107620, representativeIndex := 200, representative := 1030881994776916, permutationCode := 14599816 },
  { mask := 2618782675437924, representativeIndex := 148, representative := 960719530690904, permutationCode := 14570696 },
  { mask := 2618789990080868, representativeIndex := 150, representative := 960722726653016, permutationCode := 14570696 },
  { mask := 2619751123231076, representativeIndex := 248, representative := 1884090241813096, permutationCode := 16405704 },
  { mask := 2625373302753636, representativeIndex := 166, representative := 969515606673768, permutationCode := 16405704 },
  { mask := 2625386120155492, representativeIndex := 162, representative := 969502726359272, permutationCode := 16405704 },
  { mask := 2625387059650916, representativeIndex := 164, representative := 969510229740136, permutationCode := 16405704 },
  { mask := 2625403165286756, representativeIndex := 170, representative := 969526677201320, permutationCode := 16405697 },
  { mask := 2628272338092388, representativeIndex := 242, representative := 1875294165830232, permutationCode := 14570696 },
  { mask := 2632863725494628, representativeIndex := 226, representative := 1039746911865448, permutationCode := 16405704 },
  { mask := 2632870167748964, representativeIndex := 224, representative := 1039740469611112, permutationCode := 16405704 },
  { mask := 2634785991795044, representativeIndex := 207, representative := 1030952966523992, permutationCode := 14570696 },
  { mask := 2634794313040228, representativeIndex := 205, representative := 1030950835882584, permutationCode := 14570696 },
  { mask := 2642840866726244, representativeIndex := 262, representative := 2504027792163156, permutationCode := 14599816 },
  { mask := 2649362841674084, representativeIndex := 278, representative := 2517140394426708, permutationCode := 14599816 },
  { mask := 2657875735290212, representativeIndex := 267, representative := 2508627500810580, permutationCode := 14599816 },
]

def nearOrbitMasksG1B9P164 : List ℕ :=
  nearOrbitWitnessesG1B9P164.map NearOrbitWitness.mask

end SRG266.Certificates
