/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG1B9P168 : List NearOrbitWitness := [
  { mask := 969515606673768, representativeIndex := 166, representative := 969515606673768, permutationCode := 16434824 },
  { mask := 969522921316712, representativeIndex := 169, representative := 969522921316712, permutationCode := 16434824 },
  { mask := 977006029414760, representativeIndex := 184, representative := 977006029414760, permutationCode := 16434824 },
  { mask := 1368661748326760, representativeIndex := 133, representative := 944248035257496, permutationCode := 14599809 },
  { mask := 1391721629288808, representativeIndex := 148, representative := 960719530690904, permutationCode := 14599816 },
  { mask := 1399212052029800, representativeIndex := 182, representative := 976731168293208, permutationCode := 14599816 },
  { mask := 1507199961768296, representativeIndex := 87, representative := 805709570165400, permutationCode := 14599809 },
  { mask := 1523676530057576, representativeIndex := 96, representative := 828787580453208, permutationCode := 14599816 },
  { mask := 1539672531771752, representativeIndex := 99, representative := 836270688551256, permutationCode := 14599816 },
  { mask := 2016044077261160, representativeIndex := 246, representative := 1883821630013784, permutationCode := 14599816 },
  { mask := 2024556970877288, representativeIndex := 243, representative := 1875308736397656, permutationCode := 14599816 },
  { mask := 3463207538067816, representativeIndex := 139, representative := 954122465315156, permutationCode := 14570696 },
  { mask := 3469798165383528, representativeIndex := 143, representative := 956321471727972, permutationCode := 16405704 },
  { mask := 3477288588124520, representativeIndex := 198, representative := 1026552776919652, permutationCode := 16405704 },
  { mask := 3479210854424936, representativeIndex := 192, representative := 1024355901148244, permutationCode := 14570696 },
]

def nearOrbitMasksG1B9P168 : List ℕ :=
  nearOrbitWitnessesG1B9P168.map NearOrbitWitness.mask

end SRG266.Certificates
