/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG2B12PC98 : List NearOrbitWitness := [
  { mask := 5369780332207256, representativeIndex := 737, representative := 5369780332207256, permutationCode := 16434824 },
  { mask := 5387218033646744, representativeIndex := 787, representative := 5387218033646744, permutationCode := 16434824 },
  { mask := 5387218973142168, representativeIndex := 789, representative := 5387218973142168, permutationCode := 16434824 },
  { mask := 5716126620785816, representativeIndex := 909, representative := 5716126620785816, permutationCode := 16434824 },
  { mask := 5716127560281240, representativeIndex := 910, representative := 5716127560281240, permutationCode := 16434824 },
  { mask := 5739200258645144, representativeIndex := 939, representative := 5739200258645144, permutationCode := 16434824 },
  { mask := 5739217303776408, representativeIndex := 942, representative := 5739217303776408, permutationCode := 16434824 },
  { mask := 5742086476582040, representativeIndex := 967, representative := 5741428750115240, permutationCode := 14596225 },
  { mask := 5742102582217880, representativeIndex := 963, representative := 5741403383738792, permutationCode := 14596225 },
  { mask := 5785395727506584, representativeIndex := 1031, representative := 5785395727506584, permutationCode := 16434824 },
  { mask := 5786357800152216, representativeIndex := 1040, representative := 5786357800152216, permutationCode := 16434824 },
  { mask := 5791992797076632, representativeIndex := 1047, representative := 5791992797076632, permutationCode := 16434824 },
  { mask := 5794879015013528, representativeIndex := 1058, representative := 5794879015013528, permutationCode := 16434824 },
  { mask := 5809430498516120, representativeIndex := 1094, representative := 5809430498516120, permutationCode := 16434824 },
  { mask := 5809447543647384, representativeIndex := 1098, representative := 5809447543647384, permutationCode := 16434824 },
  { mask := 5811355583302808, representativeIndex := 1092, representative := 5809421925620376, permutationCode := 2180990 },
  { mask := 5811371688938648, representativeIndex := 1129, representative := 5811371688938648, permutationCode := 16434824 },
  { mask := 5923933940948120, representativeIndex := 1064, representative := 5795158120641192, permutationCode := 14596225 },
  { mask := 5926818279894168, representativeIndex := 1055, representative := 5794198866481832, permutationCode := 14596225 },
  { mask := 5949884536003736, representativeIndex := 1127, representative := 5811361958450328, permutationCode := 2180990 },
  { mask := 5949885475499160, representativeIndex := 1096, representative := 5809437813159064, permutationCode := 2180990 },
  { mask := 5949890978258072, representativeIndex := 1126, representative := 5811359827808920, permutationCode := 2180990 },
  { mask := 5949893796744344, representativeIndex := 1095, representative := 5809437561508504, permutationCode := 2180990 },
  { mask := 5949908023389336, representativeIndex := 1143, representative := 5811634688930472, permutationCode := 2180990 },
  { mask := 5949909902380184, representativeIndex := 1143, representative := 5811634688930472, permutationCode := 14596225 },
  { mask := 6840910784044184, representativeIndex := 1073, representative := 5807428941320594, permutationCode := 2180990 },
  { mask := 6841871917194392, representativeIndex := 1100, representative := 5810315159257490, permutationCode := 2180990 },
  { mask := 6841872856689816, representativeIndex := 1079, representative := 5808391013966226, permutationCode := 2180990 },
  { mask := 6847507853614232, representativeIndex := 1074, representative := 5807430006641298, permutationCode := 2180990 },
  { mask := 6850394071551128, representativeIndex := 1080, representative := 5808391139791506, permutationCode := 2180990 },
  { mask := 6850410177186968, representativeIndex := 1106, representative := 5810590146204322, permutationCode := 2180990 },
  { mask := 6864962600184984, representativeIndex := 1067, representative := 5807292576080522, permutationCode := 2180990 },
  { mask := 6866886745476248, representativeIndex := 1066, representative := 5807291636585098, permutationCode := 2180990 },
  { mask := 9679866977668248, representativeIndex := 1163, representative := 5824745414300264, permutationCode := 2180990 },
  { mask := 9750081111903384, representativeIndex := 1091, representative := 5809420988222040, permutationCode := 2180990 },
  { mask := 9750097217539224, representativeIndex := 1140, representative := 5811619994634856, permutationCode := 2180990 },
  { mask := 9864581735849112, representativeIndex := 1149, representative := 5811770116772208, permutationCode := 2180990 },
  { mask := 9890557697281176, representativeIndex := 1142, representative := 5811632812036712, permutationCode := 2180990 },
  { mask := 10286794200718488, representativeIndex := 757, representative := 5372953977017000, permutationCode := 14596225 },
  { mask := 10289680418655384, representativeIndex := 746, representative := 5371992843866792, permutationCode := 14596225 },
  { mask := 10312747614260376, representativeIndex := 806, representative := 5389447590437544, permutationCode := 14596225 },
  { mask := 11342302815001752, representativeIndex := 1076, representative := 5807445017597202, permutationCode := 2180990 },
  { mask := 11345211580828824, representativeIndex := 1108, representative := 5810603026518818, permutationCode := 2180990 },
  { mask := 11368278776433816, representativeIndex := 1069, representative := 5807307712861706, permutationCode := 2180990 },
  { mask := 13619552701992088, representativeIndex := 471, representative := 1802677855166824, permutationCode := 14596225 },
  { mask := 13804267460172952, representativeIndex := 487, representative := 1855470519423592, permutationCode := 14596225 },
  { mask := 14674570645916824, representativeIndex := 408, representative := 1525610403799272, permutationCode := 342391 },
  { mask := 15766872978431128, representativeIndex := 440, representative := 1591175478617188, permutationCode := 342391 },
  { mask := 15766879420685464, representativeIndex := 439, representative := 1591175226966628, permutationCode := 342391 },
  { mask := 15774356086529176, representativeIndex := 406, representative := 1520945238746212, permutationCode := 342391 },
  { mask := 18669456875375768, representativeIndex := 1085, representative := 5809352272941652, permutationCode := 2180990 },
  { mask := 18669472981011608, representativeIndex := 1133, representative := 5811551279354468, permutationCode := 2180990 },
  { mask := 18686910682451096, representativeIndex := 1113, representative := 5811138987672140, permutationCode := 2180990 },
  { mask := 19223601223376024, representativeIndex := 1121, representative := 5811293306082580, permutationCode := 2180990 },
  { mask := 19223602162871448, representativeIndex := 1088, representative := 5809369160791316, permutationCode := 2180990 },
  { mask := 19223607665630360, representativeIndex := 1120, representative := 5811291175441172, permutationCode := 2180990 },
  { mask := 19223610484116632, representativeIndex := 1087, representative := 5809368909140756, permutationCode := 2180990 },
  { mask := 19223624710761624, representativeIndex := 1135, representative := 5811566036562724, permutationCode := 2180990 },
  { mask := 19223626589752472, representativeIndex := 1136, representative := 5811567915553572, permutationCode := 2180990 },
  { mask := 19226493883567256, representativeIndex := 1152, representative := 5812252308591380, permutationCode := 2180990 },
  { mask := 19249577184808088, representativeIndex := 1115, representative := 5811156001347084, permutationCode := 2180990 },
  { mask := 22609142599699608, representativeIndex := 518, representative := 2009472560767778, permutationCode := 342391 },
  { mask := 22625635273624728, representativeIndex := 510, representative := 2009060646561290, permutationCode := 342391 },
  { mask := 23648172326300824, representativeIndex := 433, representative := 1587330946016418, permutationCode := 342391 },
  { mask := 23648177829059736, representativeIndex := 437, representative := 1589252960666274, permutationCode := 342391 },
  { mask := 23648180647546008, representativeIndex := 432, representative := 1587328815375010, permutationCode := 342391 },
  { mask := 23648194874191000, representativeIndex := 427, representative := 1587056084894866, permutationCode := 342391 },
  { mask := 23654693361753240, representativeIndex := 403, representative := 1519984105596066, permutationCode := 342391 },
  { mask := 23655655434398872, representativeIndex := 399, representative := 1517100706145442, permutationCode := 342391 },
  { mask := 23664176649260184, representativeIndex := 398, representative := 1517097510183330, permutationCode := 342391 },
  { mask := 23680669323185304, representativeIndex := 393, representative := 1516685595976842, permutationCode := 342391 },
  { mask := 27103944003341464, representativeIndex := 517, representative := 2009464245813858, permutationCode := 342391 },
  { mask := 27103960108977304, representativeIndex := 513, representative := 2009189636342866, permutationCode := 342391 },
  { mask := 27588828442447000, representativeIndex := 431, representative := 1587326938481250, permutationCode := 342391 },
  { mask := 27588844548082840, representativeIndex := 426, representative := 1587052329010258, permutationCode := 342391 },
  { mask := 40818138590813336, representativeIndex := 376, representative := 1450714998877217, permutationCode := 342391 },
  { mask := 54117831239617688, representativeIndex := 373, representative := 1446385703429123, permutationCode := 342391 },
]

def nearOrbitMasksG2B12PC98 : List ℕ :=
  nearOrbitWitnessesG2B12PC98.map NearOrbitWitness.mask

end SRG266.Certificates
