/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG2B9P158 : List NearOrbitWitness := [
  { mask := 1802402994045272, representativeIndex := 467, representative := 1802402994045272, permutationCode := 16434824 },
  { mask := 1809886102143320, representativeIndex := 475, representative := 1809886102143320, permutationCode := 16434824 },
  { mask := 5161984514572632, representativeIndex := 671, representative := 5161984514572632, permutationCode := 16434824 },
  { mask := 5192534818275672, representativeIndex := 692, representative := 5192534818275672, permutationCode := 16434824 },
  { mask := 5716122487425368, representativeIndex := 905, representative := 5716122487425368, permutationCode := 16434824 },
  { mask := 5716138123313496, representativeIndex := 911, representative := 5716138123313496, permutationCode := 16434824 },
  { mask := 5739189683030360, representativeIndex := 936, representative := 5739189683030360, permutationCode := 16434824 },
  { mask := 5742088718369112, representativeIndex := 964, representative := 5741412302654056, permutationCode := 14596225 },
  { mask := 5748610693316952, representativeIndex := 983, representative := 5748610693316952, permutationCode := 16434824 },
  { mask := 5755201320632664, representativeIndex := 988, representative := 5748902725395048, permutationCode := 14596225 },
  { mask := 6201006926530904, representativeIndex := 156, representative := 1035211290284272, permutationCode := 2180990 },
  { mask := 6217018564133208, representativeIndex := 130, representative := 965942183563504, permutationCode := 2180990 },
  { mask := 6231557230233944, representativeIndex := 51, representative := 824108278989016, permutationCode := 2180990 },
  { mask := 6231572866122072, representativeIndex := 127, representative := 962646492430552, permutationCode := 2180990 },
  { mask := 6233495132422488, representativeIndex := 126, representative := 962643673944280, permutationCode := 2180990 },
  { mask := 6234456265572696, representativeIndex := 129, representative := 965529891881176, permutationCode := 2180990 },
  { mask := 9687336221917528, representativeIndex := 1354, representative := 9687336221917528, permutationCode := 16434824 },
  { mask := 36670657048854872, representativeIndex := 68, representative := 892343781396561, permutationCode := 2180990 },
]

def nearOrbitMasksG2B9P158 : List ℕ :=
  nearOrbitWitnessesG2B9P158.map NearOrbitWitness.mask

end SRG266.Certificates
