/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG3B12PC58 : List NearOrbitWitness := [
  { mask := 962678675311704, representativeIndex := 103, representative := 961648826881170, permutationCode := 14571088 },
  { mask := 964600941612120, representativeIndex := 114, representative := 964600941612120, permutationCode := 16434824 },
  { mask := 965562074762328, representativeIndex := 77, representative := 954165718783122, permutationCode := 14571088 },
  { mask := 971191568927832, representativeIndex := 108, representative := 963571093181586, permutationCode := 14571088 },
  { mask := 971198011182168, representativeIndex := 129, representative := 970168162751634, permutationCode := 14571088 },
  { mask := 1384891140181080, representativeIndex := 133, representative := 972358596268706, permutationCode := 16406096 },
  { mask := 1386806964227160, representativeIndex := 131, representative := 970442772222626, permutationCode := 16406096 },
  { mask := 1386813406481496, representativeIndex := 110, representative := 963845702652578, permutationCode := 16406096 },
  { mask := 1387774539631704, representativeIndex := 87, representative := 956362594554530, permutationCode := 16406096 },
  { mask := 1393404033797208, representativeIndex := 116, representative := 964875551083112, permutationCode := 14599816 },
  { mask := 1802422296611928, representativeIndex := 21, representative := 540463018676436, permutationCode := 14563906 },
  { mask := 1802428738866264, representativeIndex := 23, representative := 541708395319970, permutationCode := 16406096 },
  { mask := 1809905404709976, representativeIndex := 19, representative := 538550386398354, permutationCode := 14571088 },
  { mask := 1872658978737240, representativeIndex := 139, representative := 1026592834425506, permutationCode := 16406096 },
  { mask := 1879174511430744, representativeIndex := 146, representative := 1039711878943394, permutationCode := 16406096 },
  { mask := 1885771581000792, representativeIndex := 145, representative := 1039705436689058, permutationCode := 16406096 },
  { mask := 2017712724872280, representativeIndex := 142, representative := 1030917933601938, permutationCode := 14571088 },
  { mask := 2902216997964888, representativeIndex := 220, representative := 2520316357546658, permutationCode := 16406096 },
  { mask := 2918212999679064, representativeIndex := 213, representative := 2517432958096034, permutationCode := 16406096 },
  { mask := 2928167593020504, representativeIndex := 178, representative := 2487843787543202, permutationCode := 16406096 },
  { mask := 2928190140910680, representativeIndex := 194, representative := 2504336461468322, permutationCode := 16406096 },
  { mask := 2934689567968344, representativeIndex := 183, representative := 2494365762491042, permutationCode := 16406096 },
  { mask := 2941286637538392, representativeIndex := 182, representative := 2494359320236706, permutationCode := 16406096 },
  { mask := 2941302743174232, representativeIndex := 214, representative := 2517449063731874, permutationCode := 16406096 },
  { mask := 3464883500321880, representativeIndex := 202, representative := 2511522412205202, permutationCode := 14571088 },
  { mask := 3464889942576216, representativeIndex := 216, representative := 2518119481775250, permutationCode := 14571088 },
  { mask := 3495440246279256, representativeIndex := 181, representative := 2492168886719634, permutationCode := 14571088 },
  { mask := 3495456351915096, representativeIndex := 198, representative := 2508661560644754, permutationCode := 14571088 },
  { mask := 5389171105041496, representativeIndex := 252, representative := 5387246708099672, permutationCode := 16431233 },
  { mask := 5742114463190104, representativeIndex := 61, representative := 953956565717766, permutationCode := 14535178 },
  { mask := 5748629995883608, representativeIndex := 80, representative := 955881650504454, permutationCode := 14535178 },
  { mask := 5755227065453656, representativeIndex := 62, representative := 953957505213190, permutationCode := 14535178 },
  { mask := 5811383569910872, representativeIndex := 255, representative := 5388415866081954, permutationCode := 16406096 },
  { mask := 5949921783352408, representativeIndex := 250, representative := 5387178993130260, permutationCode := 14535178 },
  { mask := 6233514434989144, representativeIndex := 150, representative := 1043549969289828, permutationCode := 16398914 },
  { mask := 6850422058159192, representativeIndex := 347, representative := 6850422058159192, permutationCode := 16434824 },
  { mask := 6866914732084312, representativeIndex := 387, representative := 6866159493124770, permutationCode := 16406096 },
  { mask := 6874375292292184, representativeIndex := 323, representative := 6848705686049442, permutationCode := 16406096 },
  { mask := 6880972361862232, representativeIndex := 322, representative := 6848699243795106, permutationCode := 16406096 },
  { mask := 7920010409708632, representativeIndex := 434, representative := 7059389963408034, permutationCode := 16406096 },
  { mask := 9687355524484184, representativeIndex := 63, representative := 953959635854598, permutationCode := 16370186 },
  { mask := 9750109098511448, representativeIndex := 247, representative := 5386216859669138, permutationCode := 16373777 },
  { mask := 9890563135999064, representativeIndex := 250, representative := 5387178993130260, permutationCode := 14563906 },
  { mask := 9898046244097112, representativeIndex := 245, representative := 5385257857160338, permutationCode := 14571088 },
  { mask := 10312775600868440, representativeIndex := 257, representative := 5389445714512488, permutationCode := 14599816 },
  { mask := 10320258708966488, representativeIndex := 270, representative := 5402571134177896, permutationCode := 14596225 },
  { mask := 10734912908201048, representativeIndex := 147, representative := 1041350962877012, permutationCode := 14563906 },
  { mask := 11345217019546712, representativeIndex := 355, representative := 6850696667630184, permutationCode := 14599816 },
  { mask := 11368306763041880, representativeIndex := 380, representative := 6865884883653778, permutationCode := 14571088 },
  { mask := 11375767323249752, representativeIndex := 295, representative := 6839911740707986, permutationCode := 14571088 },
  { mask := 11375773765504088, representativeIndex := 311, representative := 6846508810278034, permutationCode := 14571088 },
  { mask := 11375789871139928, representativeIndex := 374, representative := 6863001484203154, permutationCode := 14571088 },
  { mask := 11837584566750296, representativeIndex := 438, representative := 7073669655925906, permutationCode := 14571088 },
  { mask := 11860651762355288, representativeIndex := 431, representative := 7050602460320914, permutationCode := 14571088 },
  { mask := 11860658204609624, representativeIndex := 433, representative := 7057199529890962, permutationCode := 14571088 },
  { mask := 11860674310245464, representativeIndex := 439, representative := 7073692203816082, permutationCode := 14571088 },
  { mask := 18662887792413784, representativeIndex := 303, representative := 6841900591647320, permutationCode := 16431233 },
  { mask := 18669484861983832, representativeIndex := 344, representative := 6850413485263448, permutationCode := 16431233 },
  { mask := 18693438096116824, representativeIndex := 382, representative := 6865885571498642, permutationCode := 16373777 },
  { mask := 19223638470724696, representativeIndex := 355, representative := 6850696667630184, permutationCode := 14596225 },
  { mask := 19239634472438872, representativeIndex := 371, representative := 6857225017725544, permutationCode := 14596225 },
  { mask := 19249589065780312, representativeIndex := 380, representative := 6865884883653778, permutationCode := 14538769 },
  { mask := 19256104598473816, representativeIndex := 375, representative := 6863963556848786, permutationCode := 14538769 },
  { mask := 19256111040728152, representativeIndex := 384, representative := 6865887702140050, permutationCode := 14538769 },
  { mask := 19256127146363992, representativeIndex := 286, representative := 6833383390612626, permutationCode := 14538769 },
  { mask := 19717921841974360, representativeIndex := 462, representative := 15774401774657048, permutationCode := 16431233 },
  { mask := 19724518911544408, representativeIndex := 465, representative := 15776600781069864, permutationCode := 14596225 },
  { mask := 19741956612983896, representativeIndex := 466, representative := 15799407342198296, permutationCode := 16431233 },
  { mask := 36279095790046296, representativeIndex := 352, representative := 6850628952660772, permutationCode := 16398914 },
  { mask := 36396482631928920, representativeIndex := 395, representative := 6866854080107284, permutationCode := 14535178 },
  { mask := 36419549827533912, representativeIndex := 301, representative := 6841832876677908, permutationCode := 14563906 },
  { mask := 36419556269788248, representativeIndex := 338, representative := 6850345770294036, permutationCode := 14563906 },
  { mask := 36419572375424088, representativeIndex := 289, representative := 6834349768579860, permutationCode := 14535178 },
  { mask := 36670676351421528, representativeIndex := 224, representative := 2521293596332644, permutationCode := 16398914 },
  { mask := 36881367071034456, representativeIndex := 442, representative := 7075616535748116, permutationCode := 14563906 },
  { mask := 36911917374737496, representativeIndex := 432, representative := 7052526792252948, permutationCode := 14563906 },
  { mask := 37263899599735896, representativeIndex := 184, representative := 2496004846424660, permutationCode := 14563906 },
  { mask := 37303579535903832, representativeIndex := 445, representative := 7077815542160932, permutationCode := 16398914 },
  { mask := 37334129839606872, representativeIndex := 435, representative := 7061322868235812, permutationCode := 16398914 },
  { mask := 38359088150187096, representativeIndex := 478, representative := 20349333223120404, permutationCode := 14563906 },
  { mask := 38359094592441432, representativeIndex := 481, representative := 20350544352219810, permutationCode := 16406096 },
  { mask := 38359110698077272, representativeIndex := 489, representative := 20373359486243986, permutationCode := 14571088 },
  { mask := 38366571258285144, representativeIndex := 471, representative := 20347386343298194, permutationCode := 14571088 },
  { mask := 38389661001780312, representativeIndex := 472, representative := 20347408891188370, permutationCode := 14571088 },
]

def nearOrbitMasksG3B12PC58 : List ℕ :=
  nearOrbitWitnessesG3B12PC58.map NearOrbitWitness.mask

end SRG266.Certificates
