/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG3B12P618 : List NearOrbitWitness := [
  { mask := 18701997614290456, representativeIndex := 306, representative := 6845400734175882, permutationCode := 16373777 },
  { mask := 36281058238649880, representativeIndex := 334, representative := 6850217038454284, permutationCode := 16370186 },
  { mask := 36285657947297304, representativeIndex := 332, representative := 6850211535695372, permutationCode := 16370186 },
  { mask := 36288541346747928, representativeIndex := 336, representative := 6850224353097228, permutationCode := 16370186 },
  { mask := 36294170840913432, representativeIndex := 335, representative := 6850219856940556, permutationCode := 16370186 },
  { mask := 36701273279682072, representativeIndex := 219, representative := 2519561181499632, permutationCode := 16398914 },
  { mask := 36703195545982488, representativeIndex := 210, representative := 2512964111929584, permutationCode := 16398914 },
  { mask := 36773425785853464, representativeIndex := 425, representative := 6937536340990640, permutationCode := 16398914 },
  { mask := 36911963999295000, representativeIndex := 447, representative := 7077996820732592, permutationCode := 14563906 },
  { mask := 38365656749692440, representativeIndex := 500, representative := 20382295804982448, permutationCode := 16398914 },
  { mask := 38366617882842648, representativeIndex := 494, representative := 20375767454887088, permutationCode := 14571088 },
  { mask := 38372247377008152, representativeIndex := 499, representative := 20382293674341040, permutationCode := 14563906 },
  { mask := 38389685078447640, representativeIndex := 483, representative := 20351713508104880, permutationCode := 14563906 },
  { mask := 40642881270306328, representativeIndex := 176, representative := 2487363220968966, permutationCode := 16370186 },
  { mask := 40850688590468632, representativeIndex := 432, representative := 7052526792252948, permutationCode := 14535178 },
  { mask := 45213542407984664, representativeIndex := 435, representative := 7061322868235812, permutationCode := 16370186 },
  { mask := 54124405277840920, representativeIndex := 471, representative := 20347386343298194, permutationCode := 14538769 },
  { mask := 54150355872896536, representativeIndex := 472, representative := 20347408891188370, permutationCode := 14538769 },
]

def nearOrbitMasksG3B12P618 : List ℕ :=
  nearOrbitWitnessesG3B12P618.map NearOrbitWitness.mask

end SRG266.Certificates
