/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG3B6P038 : List NearOrbitWitness := [
]

def nearOrbitMasksG3B6P038 : List ℕ :=
  nearOrbitWitnessesG3B6P038.map NearOrbitWitness.mask

end SRG266.Certificates
