/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG3B8P094 : List NearOrbitWitness := [
  { mask := 4763756151845268, representativeIndex := 37, representative := 823108482798226, permutationCode := 16431233 },
  { mask := 4763759096156820, representativeIndex := 38, representative := 823110235963794, permutationCode := 16431233 },
  { mask := 4772271989772948, representativeIndex := 44, representative := 829707305533842, permutationCode := 16431233 },
  { mask := 4772277366706580, representativeIndex := 43, representative := 829699110113938, permutationCode := 16431233 },
  { mask := 4894807138507924, representativeIndex := 92, representative := 957048740757906, permutationCode := 16431233 },
  { mask := 4894811257188756, representativeIndex := 91, representative := 957042743086226, permutationCode := 16431233 },
  { mask := 4897690160482708, representativeIndex := 77, representative := 954165718783122, permutationCode := 16431233 },
  { mask := 4897690537958548, representativeIndex := 76, representative := 954162522821010, permutationCode := 16431233 },
  { mask := 4897697475125652, representativeIndex := 74, representative := 954159343635602, permutationCode := 16431233 },
  { mask := 4897697852601492, representativeIndex := 73, representative := 954156147673490, permutationCode := 16431233 },
  { mask := 4902294365286804, representativeIndex := 108, representative := 963571093181586, permutationCode := 16431233 },
  { mask := 4902297561248916, representativeIndex := 107, representative := 963570715705746, permutationCode := 16431233 },
  { mask := 4904218510578068, representativeIndex := 103, representative := 961648826881170, permutationCode := 16431233 },
  { mask := 4904219827549332, representativeIndex := 102, representative := 961646570414482, permutationCode := 16431233 },
  { mask := 4910807258902932, representativeIndex := 129, representative := 970168162751634, permutationCode := 16431233 },
  { mask := 4910810454865044, representativeIndex := 128, representative := 970167785275794, permutationCode := 16431233 },
  { mask := 4910815580148116, representativeIndex := 114, representative := 964600941612120, permutationCode := 14538769 },
  { mask := 4910818776110228, representativeIndex := 112, representative := 964394795770956, permutationCode := 14538769 },
  { mask := 4966959644679316, representativeIndex := 136, representative := 1024393828012690, permutationCode := 16431233 },
  { mask := 4966966707671700, representativeIndex := 135, representative := 1024389583506578, permutationCode := 16431233 },
  { mask := 4974449815769748, representativeIndex := 142, representative := 1030917933601938, permutationCode := 16431233 },
  { mask := 4974450067420308, representativeIndex := 141, representative := 1030915802960530, permutationCode := 16431233 },
  { mask := 9257660956023956, representativeIndex := 95, representative := 957323601879458, permutationCode := 14596225 },
  { mask := 9257673395949972, representativeIndex := 94, representative := 957317352557218, permutationCode := 14596225 },
  { mask := 9260543977998740, representativeIndex := 87, representative := 956362594554530, permutationCode := 14596225 },
  { mask := 9260559991362708, representativeIndex := 86, representative := 956355154086306, permutationCode := 14596225 },
  { mask := 9265148182802836, representativeIndex := 116, representative := 964875551083112, permutationCode := 16373777 },
  { mask := 9265151378764948, representativeIndex := 111, representative := 964394544120396, permutationCode := 16373777 },
  { mask := 9265156504048020, representativeIndex := 131, representative := 970442772222626, permutationCode := 14596225 },
  { mask := 9265159700010132, representativeIndex := 130, representative := 970442646397346, permutationCode := 14596225 },
  { mask := 9267072328094100, representativeIndex := 133, representative := 972358596268706, permutationCode := 14596225 },
  { mask := 9267081966310548, representativeIndex := 132, representative := 970983292445260, permutationCode := 16373777 },
  { mask := 9273669397664148, representativeIndex := 110, representative := 963845702652578, permutationCode := 14596225 },
  { mask := 9273672593626260, representativeIndex := 109, representative := 963845576827298, permutationCode := 14596225 },
  { mask := 9468351675636884, representativeIndex := 139, representative := 1026592834425506, permutationCode := 14596225 },
  { mask := 9468367311525012, representativeIndex := 138, representative := 1026586459277986, permutationCode := 14596225 },
  { mask := 9475842098377876, representativeIndex := 145, representative := 1039705436689058, permutationCode := 14596225 },
  { mask := 9475850419623060, representativeIndex := 146, representative := 1039711878943394, permutationCode := 14596225 },
  { mask := 13619488106361236, representativeIndex := 22, representative := 541699954540770, permutationCode := 16370186 },
  { mask := 13619496427606420, representativeIndex := 20, representative := 539500948127954, permutationCode := 14535178 },
  { mask := 13691643556844180, representativeIndex := 150, representative := 1043549969289828, permutationCode := 16373777 },
  { mask := 13691652129739924, representativeIndex := 147, representative := 1041350962877012, permutationCode := 16373777 },
  { mask := 13830174707293332, representativeIndex := 140, representative := 1028234116107348, permutationCode := 14538769 },
  { mask := 13830182021936276, representativeIndex := 148, representative := 1041359535772756, permutationCode := 14538769 },
  { mask := 13830190343181460, representativeIndex := 143, representative := 1034762466202708, permutationCode := 14538769 },
  { mask := 18240676332051604, representativeIndex := 172, representative := 2479047711560338, permutationCode := 16431233 },
  { mask := 18240683395043988, representativeIndex := 171, representative := 2479043467054226, permutationCode := 16431233 },
  { mask := 18256679396758164, representativeIndex := 181, representative := 2492168886719634, permutationCode := 16431233 },
  { mask := 18256687969653908, representativeIndex := 180, representative := 2492160313823890, permutationCode := 16431233 },
  { mask := 18271233698747028, representativeIndex := 205, representative := 2511547778581650, permutationCode := 16431233 },
  { mask := 18271233950397588, representativeIndex := 204, representative := 2511545647940242, permutationCode := 16431233 },
  { mask := 18271256246637204, representativeIndex := 202, representative := 2511522412205202, permutationCode := 16431233 },
  { mask := 18271256498287764, representativeIndex := 201, representative := 2511520281563794, permutationCode := 16431233 },
  { mask := 18274117098197652, representativeIndex := 198, representative := 2508661560644754, permutationCode := 16431233 },
  { mask := 18274142716224660, representativeIndex := 197, representative := 2508636882113170, permutationCode := 16431233 },
  { mask := 18279755165258900, representativeIndex := 217, representative := 2518136275255954, permutationCode := 16431233 },
  { mask := 18279769140253332, representativeIndex := 216, representative := 2518119481775250, permutationCode := 16431233 },
  { mask := 18379214545493140, representativeIndex := 178, representative := 2487843787543202, permutationCode := 14596225 },
  { mask := 18379221860136084, representativeIndex := 177, representative := 2487830970141346, permutationCode := 14596225 },
  { mask := 18395217861850260, representativeIndex := 182, representative := 2494359320236706, permutationCode := 14596225 },
  { mask := 18395226183095444, representativeIndex := 183, representative := 2494365762491042, permutationCode := 14596225 },
  { mask := 18405165140548756, representativeIndex := 194, representative := 2504336461468322, permutationCode := 14596225 },
  { mask := 18405197821568148, representativeIndex := 192, representative := 2504307538430626, permutationCode := 14596225 },
  { mask := 18411694430139540, representativeIndex := 222, representative := 2520335281668770, permutationCode := 14596225 },
  { mask := 18411718857020564, representativeIndex := 220, representative := 2520316357546658, permutationCode := 14596225 },
  { mask := 18412655563289748, representativeIndex := 214, representative := 2517449063731874, permutationCode := 14596225 },
  { mask := 18412680929666196, representativeIndex := 213, representative := 2517432958096034, permutationCode := 14596225 },
  { mask := 22602506426700436, representativeIndex := 223, representative := 2521277490696804, permutationCode := 16373777 },
  { mask := 22602506678350996, representativeIndex := 207, representative := 2512481414713940, permutationCode := 16373777 },
  { mask := 22625566559313044, representativeIndex := 196, representative := 2505984806142548, permutationCode := 16373777 },
  { mask := 22625570677993876, representativeIndex := 212, representative := 2512994163200624, permutationCode := 16373777 },
  { mask := 22625596170195604, representativeIndex := 179, representative := 2488804920693348, permutationCode := 16373777 },
  { mask := 22625596421846164, representativeIndex := 173, representative := 2480008844710484, permutationCode := 16373777 },
  { mask := 22628449581287828, representativeIndex := 227, representative := 2522461814819440, permutationCode := 16373777 },
  { mask := 22628456895930772, representativeIndex := 230, representative := 2528990164914800, permutationCode := 16373777 },
  { mask := 22628457021756052, representativeIndex := 224, representative := 2521293596332644, permutationCode := 16373777 },
  { mask := 22628482639783060, representativeIndex := 184, representative := 2496004846424660, permutationCode := 16373777 },
  { mask := 22836257278925972, representativeIndex := 233, representative := 3134975116023314, permutationCode := 16431233 },
  { mask := 22836264593568916, representativeIndex := 232, representative := 3134968740875794, permutationCode := 16431233 },
  { mask := 27103891394665620, representativeIndex := 195, representative := 2505955195259988, permutationCode := 14538769 },
  { mask := 27103898709308564, representativeIndex := 218, representative := 2519080614925396, permutationCode := 14538769 },
  { mask := 27103907030553748, representativeIndex := 208, representative := 2512483545355348, permutationCode := 14538769 },
  { mask := 27129857625609364, representativeIndex := 209, representative := 2512506093245524, permutationCode := 14538769 },
  { mask := 27129874670740628, representativeIndex := 185, representative := 2496013419320404, permutationCode := 14538769 },
  { mask := 27199126732330132, representativeIndex := 234, representative := 3137167747288610, permutationCode := 14596225 },
]

def nearOrbitMasksG3B8P094 : List ℕ :=
  nearOrbitWitnessesG3B8P094.map NearOrbitWitness.mask

end SRG266.Certificates
