/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG3B8P091 : List NearOrbitWitness := [
  { mask := 261464325494929, representativeIndex := 6, representative := 261464325494929, permutationCode := 16434824 },
  { mask := 261473519128721, representativeIndex := 8, representative := 261473519128721, permutationCode := 16434824 },
  { mask := 262428277131409, representativeIndex := 8, representative := 261473519128721, permutationCode := 16431233 },
  { mask := 262432773288081, representativeIndex := 6, representative := 261464325494929, permutationCode := 16431233 },
  { mask := 268054952810641, representativeIndex := 12, representative := 268054952810641, permutationCode := 16434824 },
  { mask := 268070588698769, representativeIndex := 13, representative := 268070588698769, permutationCode := 16434824 },
  { mask := 270941170747537, representativeIndex := 13, representative := 268070588698769, permutationCode := 16431233 },
  { mask := 270953988149393, representativeIndex := 12, representative := 268054952810641, permutationCode := 16431233 },
  { mask := 275545375551633, representativeIndex := 14, representative := 275545375551633, permutationCode := 16434824 },
  { mask := 275553696796817, representativeIndex := 15, representative := 275553696796817, permutationCode := 16434824 },
  { mask := 277469520842897, representativeIndex := 15, representative := 275553696796817, permutationCode := 16431233 },
  { mask := 277475963097233, representativeIndex := 14, representative := 275545375551633, permutationCode := 16431233 },
  { mask := 4616765382203537, representativeIndex := 0, representative := 252812061511811, permutationCode := 16370186 },
  { mask := 4616768200689809, representativeIndex := 9, representative := 265924663775363, permutationCode := 16370186 },
  { mask := 4623294671794321, representativeIndex := 3, representative := 260296109105283, permutationCode := 16370186 },
  { mask := 4623296550785169, representativeIndex := 10, representative := 266886736420995, permutationCode := 16370186 },
  { mask := 4629877984467089, representativeIndex := 2, representative := 252814879998083, permutationCode := 16370186 },
  { mask := 4629885299110033, representativeIndex := 4, representative := 260297988096131, permutationCode := 16370186 },
  { mask := 4629893620355217, representativeIndex := 11, representative := 267864631595525, permutationCode := 16373777 },
  { mask := 4686034488924305, representativeIndex := 27, representative := 747317401131537, permutationCode := 16431233 },
  { mask := 4693524911665297, representativeIndex := 28, representative := 753839376079377, permutationCode := 16431233 },
  { mask := 4702046126526609, representativeIndex := 29, representative := 760430003395089, permutationCode := 16431233 },
  { mask := 4824572702365841, representativeIndex := 50, representative := 887780011514897, permutationCode := 16431233 },
  { mask := 4832063125106833, representativeIndex := 53, representative := 894301986462737, permutationCode := 16431233 },
  { mask := 4833987270398097, representativeIndex := 52, representative := 892379720162321, permutationCode := 16431233 },
  { mask := 4840576018722961, representativeIndex := 55, representative := 900899056032785, permutationCode := 16431233 },
  { mask := 4840584339968145, representativeIndex := 53, representative := 894301986462737, permutationCode := 14538769 },
  { mask := 9187426519881873, representativeIndex := 51, representative := 888054620985889, permutationCode := 14596225 },
  { mask := 9194916942622865, representativeIndex := 54, representative := 894576595933729, permutationCode := 16373777 },
  { mask := 9194925263868049, representativeIndex := 56, representative := 901173665503777, permutationCode := 14596225 },
  { mask := 9196841087914129, representativeIndex := 57, representative := 903089489549857, permutationCode := 14596225 },
  { mask := 9203438157484177, representativeIndex := 54, representative := 894576595933729, permutationCode := 14596225 },
  { mask := 18101175607675025, representativeIndex := 156, representative := 2339550495611921, permutationCode := 16431233 },
  { mask := 18114292706095249, representativeIndex := 159, representative := 2355552939580433, permutationCode := 16431233 },
  { mask := 18114301027340433, representativeIndex := 158, representative := 2355546497326097, permutationCode := 16431233 },
  { mask := 18124239984793745, representativeIndex := 161, representative := 2365523638557713, permutationCode := 16431233 },
  { mask := 18124242803280017, representativeIndex := 162, representative := 2365526457043985, permutationCode := 16431233 },
  { mask := 18130761959741585, representativeIndex := 162, representative := 2365526457043985, permutationCode := 14538769 },
  { mask := 18130769274384529, representativeIndex := 166, representative := 2372327537619489, permutationCode := 16373777 },
  { mask := 18130771153375377, representativeIndex := 164, representative := 2370130661848081, permutationCode := 14538769 },
  { mask := 18130793701265553, representativeIndex := 156, representative := 2339550495611921, permutationCode := 14538769 },
  { mask := 18131730407534737, representativeIndex := 165, representative := 2372045613505553, permutationCode := 16431233 },
  { mask := 18131755773911185, representativeIndex := 158, representative := 2355546497326097, permutationCode := 14538769 },
  { mask := 18133648177678481, representativeIndex := 164, representative := 2370130661848081, permutationCode := 16431233 },
  { mask := 18133654552826001, representativeIndex := 163, representative := 2370123347205137, permutationCode := 16431233 },
  { mask := 18140238804994193, representativeIndex := 166, representative := 2372327537619489, permutationCode := 14596225 },
  { mask := 18140251622396049, representativeIndex := 165, representative := 2372045613505553, permutationCode := 14538769 },
  { mask := 18140268667527313, representativeIndex := 159, representative := 2355552939580433, permutationCode := 14538769 },
]

def nearOrbitMasksG3B8P091 : List ℕ :=
  nearOrbitWitnessesG3B8P091.map NearOrbitWitness.mask

end SRG266.Certificates
