/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG3B9P0D8 : List NearOrbitWitness := [
  { mask := 824137202995416, representativeIndex := 33, representative := 815480629496458, permutationCode := 16406096 },
  { mask := 824140021481688, representativeIndex := 39, representative := 824140021481688, permutationCode := 16434824 },
  { mask := 830721455163608, representativeIndex := 41, representative := 828599606907530, permutationCode := 16406096 },
  { mask := 830737091051736, representativeIndex := 45, representative := 830737091051736, permutationCode := 16434824 },
  { mask := 833620490502360, representativeIndex := 35, representative := 815489823130250, permutationCode := 16406096 },
  { mask := 840136023195864, representativeIndex := 42, representative := 828608867648138, permutationCode := 16406096 },
  { mask := 962675416436952, representativeIndex := 67, representative := 954020973579402, permutationCode := 14571088 },
  { mask := 962676355932376, representativeIndex := 104, representative := 962676355932376, permutationCode := 16434824 },
  { mask := 964600501223640, representativeIndex := 113, representative := 964600501223640, permutationCode := 16434824 },
  { mask := 965561634373848, representativeIndex := 70, representative := 954028288222346, permutationCode := 14571088 },
  { mask := 971181934905560, representativeIndex := 122, representative := 969068659545226, permutationCode := 14571088 },
  { mask := 971188310053080, representativeIndex := 82, representative := 955943239879818, permutationCode := 14571088 },
  { mask := 971191128539352, representativeIndex := 106, representative := 963433662620810, permutationCode := 14571088 },
  { mask := 971197570793688, representativeIndex := 127, representative := 970030732190858, permutationCode := 14571088 },
  { mask := 978672357646552, representativeIndex := 123, representative := 969071478031498, permutationCode := 14571088 },
  { mask := 978674236637400, representativeIndex := 101, representative := 960550263170186, permutationCode := 14571088 },
  { mask := 1384875063904472, representativeIndex := 119, representative := 969060086649482, permutationCode := 16406096 },
  { mask := 1384882378547416, representativeIndex := 125, representative := 970022159295114, permutationCode := 16406096 },
  { mask := 1386797330204888, representativeIndex := 100, representative := 960547193033354, permutationCode := 16406096 },
  { mask := 1386803705352408, representativeIndex := 66, representative := 954018842937994, permutationCode := 16406096 },
  { mask := 1386806523838680, representativeIndex := 126, representative := 970030480540298, permutationCode := 16406096 },
  { mask := 1386812966093016, representativeIndex := 105, representative := 963433410970250, permutationCode := 16406096 },
  { mask := 1387765777998040, representativeIndex := 69, representative := 954026157580938, permutationCode := 16406096 },
  { mask := 1387774099243224, representativeIndex := 83, representative := 955950302872202, permutationCode := 16406096 },
  { mask := 1393403593408728, representativeIndex := 115, representative := 964875362345192, permutationCode := 14599816 },
  { mask := 1400886701506776, representativeIndex := 120, representative := 969062905135754, permutationCode := 16406096 },
  { mask := 4763823866814680, representativeIndex := 37, representative := 823108482798226, permutationCode := 16373777 },
  { mask := 4772345081675992, representativeIndex := 43, representative := 829699110113938, permutationCode := 16373777 },
  { mask := 4901400007610584, representativeIndex := 77, representative := 954165718783122, permutationCode := 14538769 },
  { mask := 4902362080256216, representativeIndex := 114, representative := 964600941612120, permutationCode := 16431233 },
  { mask := 4904286225547480, representativeIndex := 103, representative := 961648826881170, permutationCode := 14538769 },
  { mask := 4910867659229400, representativeIndex := 91, representative := 957042743086226, permutationCode := 14538769 },
  { mask := 4910874973872344, representativeIndex := 129, representative := 970168162751634, permutationCode := 14538769 },
  { mask := 4910883295117528, representativeIndex := 108, representative := 963571093181586, permutationCode := 14538769 },
  { mask := 4917396009324760, representativeIndex := 74, representative := 954159343635602, permutationCode := 14538769 },
  { mask := 5192551801463000, representativeIndex := 38, representative := 823110235963794, permutationCode := 16370186 },
  { mask := 5194475946754264, representativeIndex := 44, representative := 829707305533842, permutationCode := 16370186 },
  { mask := 5402280448430296, representativeIndex := 262, representative := 5402280448430296, permutationCode := 16434824 },
  { mask := 5403242521075928, representativeIndex := 267, representative := 5402298590338584, permutationCode := 16431233 },
  { mask := 5739214987462872, representativeIndex := 73, representative := 954156147673490, permutationCode := 14535178 },
  { mask := 5742098386913496, representativeIndex := 76, representative := 954162522821010, permutationCode := 14535178 },
  { mask := 5746705410203864, representativeIndex := 128, representative := 970167785275794, permutationCode := 14535178 },
  { mask := 5748626737008856, representativeIndex := 92, representative := 957048740757906, permutationCode := 14535178 },
  { mask := 5748627676504280, representativeIndex := 112, representative := 964394795770956, permutationCode := 16398914 },
  { mask := 5748629555495128, representativeIndex := 107, representative := 963570715705746, permutationCode := 14535178 },
  { mask := 5755226625065176, representativeIndex := 102, representative := 961646570414482, permutationCode := 14535178 },
  { mask := 5811367493634264, representativeIndex := 240, representative := 5385117356462730, permutationCode := 16406096 },
  { mask := 5818857916375256, representativeIndex := 241, representative := 5385118295958154, permutationCode := 16406096 },
  { mask := 6850405981882584, representativeIndex := 343, representative := 6850405981882584, permutationCode := 16434824 },
  { mask := 6856934331977944, representativeIndex := 363, representative := 6856934331977944, permutationCode := 16434824 },
  { mask := 6864960283871448, representativeIndex := 316, representative := 6848284133626506, permutationCode := 16406096 },
  { mask := 6866882550171864, representativeIndex := 290, representative := 6839771240010378, permutationCode := 16406096 },
  { mask := 6871488633966808, representativeIndex := 315, representative := 6848277758478986, permutationCode := 16406096 },
  { mask := 6874372033417432, representativeIndex := 281, representative := 6832281756764810, permutationCode := 16406096 },
  { mask := 6874372972912856, representativeIndex := 291, representative := 6839772179505802, permutationCode := 16406096 },
  { mask := 6874374851903704, representativeIndex := 319, representative := 6848293394367114, permutationCode := 16406096 },
  { mask := 6880001527582936, representativeIndex := 307, representative := 6846355492178570, permutationCode := 16406096 },
  { mask := 6880956285585624, representativeIndex := 306, representative := 6845400734175882, permutationCode := 16406096 },
  { mask := 6880963600228568, representativeIndex := 308, representative := 6846362806821514, permutationCode := 16406096 },
  { mask := 6880971921473752, representativeIndex := 317, representative := 6848286952112778, permutationCode := 16406096 },
  { mask := 9264253825126616, representativeIndex := 87, representative := 956362594554530, permutationCode := 16373777 },
  { mask := 9265208583129304, representativeIndex := 94, representative := 957317352557218, permutationCode := 16373777 },
  { mask := 9265215897772248, representativeIndex := 110, representative := 963845702652578, permutationCode := 16373777 },
  { mask := 9265224219017432, representativeIndex := 131, representative := 970442772222626, permutationCode := 16373777 },
  { mask := 9267140043063512, representativeIndex := 133, representative := 972358596268706, permutationCode := 16373777 },
  { mask := 9273737112633560, representativeIndex := 116, representative := 964875551083112, permutationCode := 14596225 },
  { mask := 9679862782363864, representativeIndex := 86, representative := 956355154086306, permutationCode := 16370186 },
  { mask := 9687352265609432, representativeIndex := 95, representative := 957323601879458, permutationCode := 16370186 },
  { mask := 9687353205104856, representativeIndex := 109, representative := 963845576827298, permutationCode := 16370186 },
  { mask := 9687355084095704, representativeIndex := 111, representative := 964394544120396, permutationCode := 14563906 },
  { mask := 9689277350396120, representativeIndex := 130, representative := 970442646397346, permutationCode := 16370186 },
  { mask := 9695874419966168, representativeIndex := 132, representative := 970983292445260, permutationCode := 14563906 },
  { mask := 9750093022234840, representativeIndex := 260, representative := 5389583956646320, permutationCode := 16370186 },
  { mask := 9756621372330200, representativeIndex := 261, representative := 5389585021967024, permutationCode := 16373777 },
  { mask := 9759507590267096, representativeIndex := 273, representative := 5403671448957360, permutationCode := 16370186 },
  { mask := 9766104659837144, representativeIndex := 272, representative := 5403658757380784, permutationCode := 16373777 },
  { mask := 18669468785707224, representativeIndex := 350, representative := 6850430498938392, permutationCode := 16431233 },
  { mask := 18676959208448216, representativeIndex := 368, representative := 6856952473886232, permutationCode := 16431233 },
  { mask := 18678883353739480, representativeIndex := 362, representative := 6855030207585816, permutationCode := 16431233 },
  { mask := 18686906487146712, representativeIndex := 398, representative := 6866923172863512, permutationCode := 16431233 },
  { mask := 18693434837242072, representativeIndex := 401, representative := 6867328649009840, permutationCode := 16373777 },
  { mask := 18693435776737496, representativeIndex := 409, representative := 6874407220456984, permutationCode := 16431233 },
  { mask := 18693437655728344, representativeIndex := 411, representative := 6874409099447832, permutationCode := 16431233 },
  { mask := 18696321055178968, representativeIndex := 407, representative := 6871522881510936, permutationCode := 16431233 },
  { mask := 18701950549344472, representativeIndex := 419, representative := 6881006169017880, permutationCode := 16431233 },
  { mask := 18701956991598808, representativeIndex := 417, representative := 6880997847772696, permutationCode := 16431233 },
  { mask := 18701973097234648, representativeIndex := 357, representative := 6850829532830384, permutationCode := 16373777 },
  { mask := 18702918124749016, representativeIndex := 413, representative := 6880035775127064, permutationCode := 16431233 },
  { mask := 36255057760162008, representativeIndex := 393, representative := 6866717027022348, permutationCode := 16398914 },
  { mask := 36256019832807640, representativeIndex := 391, representative := 6866710651874828, permutationCode := 16398914 },
  { mask := 36264541047668952, representativeIndex := 392, representative := 6866712530865676, permutationCode := 16398914 },
  { mask := 36279079713769688, representativeIndex := 334, representative := 6850217038454284, permutationCode := 16398914 },
  { mask := 36279087028412632, representativeIndex := 327, representative := 6849255905304076, permutationCode := 16398914 },
  { mask := 36279095349657816, representativeIndex := 312, representative := 6847333639003660, permutationCode := 16398914 },
  { mask := 36281011173703896, representativeIndex := 326, representative := 6849249463049740, permutationCode := 16398914 },
  { mask := 36281017615958232, representativeIndex := 297, representative := 6840736569433612, permutationCode := 16398914 },
  { mask := 36281033721594072, representativeIndex := 358, representative := 6850834909764016, permutationCode := 16370186 },
  { mask := 36285608063865048, representativeIndex := 336, representative := 6850224353097228, permutationCode := 16398914 },
  { mask := 36288494281801944, representativeIndex := 332, representative := 6850211535695372, permutationCode := 16398914 },
  { mask := 36295091351371992, representativeIndex := 335, representative := 6850219856940556, permutationCode := 16398914 },
]

def nearOrbitMasksG3B9P0D8 : List ℕ :=
  nearOrbitWitnessesG3B9P0D8.map NearOrbitWitness.mask

end SRG266.Certificates
