/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG4B12P409 : List NearOrbitWitness := [
  { mask := 4917276657050633, representativeIndex := 92, representative := 4917276657050633, permutationCode := 16434824 },
  { mask := 5376185134724105, representativeIndex := 3, representative := 521900574867523, permutationCode := 10296643 },
  { mask := 5402161096156169, representativeIndex := 13, representative := 936555774413059, permutationCode := 8890931 },
  { mask := 5798391157339145, representativeIndex := 69, representative := 4884765903268873, permutationCode := 14498113 },
  { mask := 5824367118771209, representativeIndex := 134, representative := 5471842305819426, permutationCode := 4408957 },
  { mask := 5938851637081097, representativeIndex := 53, representative := 4877202568974405, permutationCode := 8890931 },
  { mask := 5956314704897033, representativeIndex := 115, representative := 5369784576973073, permutationCode := 8890931 },
  { mask := 6856814979703817, representativeIndex := 117, representative := 5371580929920009, permutationCode := 5785549 },
  { mask := 10319168522413065, representativeIndex := 125, representative := 5441246314957218, permutationCode := 8745331 },
  { mask := 11358207010661385, representativeIndex := 120, representative := 5424769746668806, permutationCode := 8745331 },
  { mask := 18675877783528457, representativeIndex := 14, representative := 936558970375171, permutationCode := 8745331 },
  { mask := 19238544285885449, representativeIndex := 57, representative := 4877219205173509, permutationCode := 8890931 },
  { mask := 22615563507852297, representativeIndex := 96, representative := 5033180423659910, permutationCode := 14527233 },
  { mask := 36254938407887881, representativeIndex := 104, representative := 5191454489004553, permutationCode := 4408957 },
  { mask := 36261529035203593, representativeIndex := 137, representative := 5480054846112088, permutationCode := 12368258 },
  { mask := 36268051010151433, representativeIndex := 66, representative := 4884696810512645, permutationCode := 5902029 },
  { mask := 36393476621329417, representativeIndex := 116, representative := 5369787395459345, permutationCode := 8890931 },
  { mask := 36401989514945545, representativeIndex := 55, representative := 4877206387771653, permutationCode := 8890931 },
  { mask := 36409472623043593, representativeIndex := 26, representative := 1382754531910659, permutationCode := 13234473 },
  { mask := 40623352066860041, representativeIndex := 130, representative := 5464043208509784, permutationCode := 12368258 },
  { mask := 40824543393330185, representativeIndex := 39, representative := 4746233880431113, permutationCode := 13350953 },
  { mask := 40833081653322761, representativeIndex := 54, representative := 4877204508780805, permutationCode := 8890931 },
  { mask := 45118153470501897, representativeIndex := 121, representative := 5432466315250962, permutationCode := 8745331 },
  { mask := 45187422577222665, representativeIndex := 67, representative := 4884697187988485, permutationCode := 5902029 },
  { mask := 54124236042134537, representativeIndex := 114, representative := 5369656532978185, permutationCode := 5785549 },
]

def nearOrbitMasksG4B12P409 : List ℕ :=
  nearOrbitWitnessesG4B12P409.map NearOrbitWitness.mask

end SRG266.Certificates
