/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG4B10P021 : List NearOrbitWitness := [
  { mask := 5926146830343201, representativeIndex := 131, representative := 5471567696348434, permutationCode := 3426262 },
  { mask := 5932737457658913, representativeIndex := 124, representative := 5440781384271110, permutationCode := 3426262 },
  { mask := 5942142832057377, representativeIndex := 134, representative := 5471842305819426, permutationCode := 16147152 },
  { mask := 5950192204229665, representativeIndex := 73, representative := 4886627775534085, permutationCode := 3426262 },
  { mask := 5952114470530081, representativeIndex := 61, representative := 4882779487048707, permutationCode := 3426262 },
  { mask := 5956714179177505, representativeIndex := 132, representative := 5471808498663778, permutationCode := 5785549 },
  { mask := 5956726996579361, representativeIndex := 16, representative := 944046197154051, permutationCode := 10267523 },
  { mask := 5959597578628129, representativeIndex := 133, representative := 5471812254548386, permutationCode := 16147152 },
  { mask := 5965210027662369, representativeIndex := 101, representative := 5159856228516099, permutationCode := 3426262 },
  { mask := 5965239890195489, representativeIndex := 4, representative := 521902451761283, permutationCode := 10267523 },
  { mask := 7051909171883041, representativeIndex := 101, representative := 5159856228516099, permutationCode := 5785549 },
  { mask := 7058482754067489, representativeIndex := 133, representative := 5471812254548386, permutationCode := 16405704 },
  { mask := 7058499799198753, representativeIndex := 134, representative := 5471842305819426, permutationCode := 16405704 },
  { mask := 7060405020367905, representativeIndex := 132, representative := 5471808498663778, permutationCode := 3426262 },
  { mask := 7065004729015329, representativeIndex := 61, representative := 4882779487048707, permutationCode := 5785549 },
  { mask := 7065034591548449, representativeIndex := 4, representative := 521902451761283, permutationCode := 10296643 },
  { mask := 7067888128465953, representativeIndex := 73, representative := 4886627775534085, permutationCode := 5785549 },
  { mask := 7067905173597217, representativeIndex := 124, representative := 5440781384271110, permutationCode := 5785549 },
  { mask := 7090972369202209, representativeIndex := 131, representative := 5471567696348434, permutationCode := 5785549 },
  { mask := 7090985186604065, representativeIndex := 16, representative := 944046197154051, permutationCode := 10296643 },
  { mask := 9457769920175137, representativeIndex := 86, representative := 4904056778252549, permutationCode := 5443165 },
  { mask := 9458731053325345, representativeIndex := 64, representative := 4883810272877577, permutationCode := 13463905 },
  { mask := 9475207621614625, representativeIndex := 43, representative := 4756135738302725, permutationCode := 4408957 },
  { mask := 9475224666745889, representativeIndex := 109, representative := 5318939671216468, permutationCode := 4408957 },
  { mask := 9873385252559905, representativeIndex := 11, representative := 806546090475593, permutationCode := 8745331 },
  { mask := 9880868360657953, representativeIndex := 12, representative := 824138267607121, permutationCode := 8745331 },
  { mask := 9890839999130657, representativeIndex := 10, representative := 805516304957699, permutationCode := 8745331 },
  { mask := 10289000647859233, representativeIndex := 116, representative := 5369787395459345, permutationCode := 3542742 },
  { mask := 10319550951562273, representativeIndex := 97, representative := 5033212605572358, permutationCode := 4408957 },
  { mask := 10319580814095393, representativeIndex := 18, representative := 945084303917129, permutationCode := 9149483 },
  { mask := 11345493882678305, representativeIndex := 56, representative := 4877206765247493, permutationCode := 11334050 },
  { mask := 11358589439810593, representativeIndex := 107, representative := 5302446997291348, permutationCode := 3426262 },
  { mask := 11358619302343713, representativeIndex := 20, representative := 1070428822799430, permutationCode := 8745331 },
  { mask := 11414745944267809, representativeIndex := 40, representative := 4746371122253969, permutationCode := 5785549 },
  { mask := 11427858546531361, representativeIndex := 72, representative := 4886619076813061, permutationCode := 5443165 },
  { mask := 11553284157709345, representativeIndex := 107, representative := 5302446997291348, permutationCode := 8745331 },
  { mask := 11553301202840609, representativeIndex := 106, representative := 5300318773887750, permutationCode := 8745331 },
  { mask := 11569280159423521, representativeIndex := 109, representative := 5318939671216468, permutationCode := 8745331 },
  { mask := 13813070976883745, representativeIndex := 96, representative := 5033180423659910, permutationCode := 11508770 },
  { mask := 13819592951831585, representativeIndex := 87, representative := 4904082522104837, permutationCode := 5443165 },
  { mask := 13837047698402337, representativeIndex := 133, representative := 5471812254548386, permutationCode := 5785549 },
  { mask := 15776568975924257, representativeIndex := 76, representative := 4887108342108321, permutationCode := 5785549 },
  { mask := 15776586021055521, representativeIndex := 124, representative := 5440781384271110, permutationCode := 3313310 },
  { mask := 15783159603239969, representativeIndex := 126, representative := 5443184217145700, permutationCode := 3426262 },
  { mask := 18394583385087009, representativeIndex := 109, representative := 5318939671216468, permutationCode := 2279102 },
  { mask := 18394600430218273, representativeIndex := 86, representative := 4904056778252549, permutationCode := 3313310 },
  { mask := 18395561563368481, representativeIndex := 64, representative := 4883810272877577, permutationCode := 11334050 },
  { mask := 18412038131657761, representativeIndex := 43, representative := 4756135738302725, permutationCode := 2279102 },
  { mask := 18880446002474017, representativeIndex := 12, representative := 824138267607121, permutationCode := 8974763 },
  { mask := 18886950932290593, representativeIndex := 10, representative := 805516304957699, permutationCode := 8974763 },
  { mask := 18886967977421857, representativeIndex := 11, representative := 806546090475593, permutationCode := 8974763 },
  { mask := 19225831157902369, representativeIndex := 72, representative := 4886619076813061, permutationCode := 3313310 },
  { mask := 19256381461605409, representativeIndex := 40, representative := 4746371122253969, permutationCode := 3426262 },
  { mask := 19296061397773345, representativeIndex := 107, representative := 5302446997291348, permutationCode := 5785549 },
  { mask := 19309156954905633, representativeIndex := 56, representative := 4877206765247493, permutationCode := 13463905 },
  { mask := 19309186817438753, representativeIndex := 20, representative := 1070428822799430, permutationCode := 8974763 },
  { mask := 19434599611214881, representativeIndex := 109, representative := 5318939671216468, permutationCode := 8974763 },
  { mask := 19449617434647585, representativeIndex := 106, representative := 5300318773887750, permutationCode := 8974763 },
  { mask := 19467072181218337, representativeIndex := 107, representative := 5302446997291348, permutationCode := 8974763 },
  { mask := 20351576454310945, representativeIndex := 97, representative := 5033212605572358, permutationCode := 2279102 },
  { mask := 20364689056574497, representativeIndex := 116, representative := 5369787395459345, permutationCode := 5902029 },
  { mask := 20364701873976353, representativeIndex := 18, representative := 945084303917129, permutationCode := 8890931 },
  { mask := 22819153548516385, representativeIndex := 133, representative := 5471812254548386, permutationCode := 3426262 },
  { mask := 22819170593647649, representativeIndex := 87, representative := 4904082522104837, permutationCode := 3313310 },
  { mask := 22826653701745697, representativeIndex := 96, representative := 5033180423659910, permutationCode := 13609505 },
  { mask := 23657884429429793, representativeIndex := 126, representative := 5443184217145700, permutationCode := 5785549 },
  { mask := 23663496878464033, representativeIndex := 124, representative := 5440781384271110, permutationCode := 5443165 },
  { mask := 23680951625034785, representativeIndex := 76, representative := 4887108342108321, permutationCode := 3426262 },
  { mask := 28158298282105889, representativeIndex := 105, representative := 5300312331633414, permutationCode := 8974763 },
  { mask := 29284060623645729, representativeIndex := 105, representative := 5300312331633414, permutationCode := 8745331 },
  { mask := 36396759495060513, representativeIndex := 49, representative := 4870616137931781, permutationCode := 11334050 },
  { mask := 36402371944094753, representativeIndex := 106, representative := 5300318773887750, permutationCode := 3426262 },
  { mask := 36402401806627873, representativeIndex := 6, representative := 522865463902277, permutationCode := 8890931 },
  { mask := 36409884914725921, representativeIndex := 22, representative := 1101215134876754, permutationCode := 8745331 },
  { mask := 36419826690665505, representativeIndex := 36, representative := 4746165165150725, permutationCode := 3426262 },
  { mask := 36466011556650017, representativeIndex := 36, representative := 4746165165150725, permutationCode := 5785549 },
  { mask := 36466028601781281, representativeIndex := 106, representative := 5300318773887750, permutationCode := 5785549 },
  { mask := 36472602183965729, representativeIndex := 49, representative := 4870616137931781, permutationCode := 13463905 },
  { mask := 36472632046498849, representativeIndex := 22, representative := 1101215134876754, permutationCode := 8974763 },
  { mask := 36479154021446689, representativeIndex := 6, representative := 522865463902277, permutationCode := 9149483 },
  { mask := 40820351480208417, representativeIndex := 134, representative := 5471842305819426, permutationCode := 3426262 },
  { mask := 40820368525339681, representativeIndex := 73, representative := 4886627775534085, permutationCode := 3313310 },
  { mask := 40833464082471969, representativeIndex := 73, representative := 4886627775534085, permutationCode := 5443165 },
  { mask := 40833493945005089, representativeIndex := 1, representative := 520940379115651, permutationCode := 10296643 },
  { mask := 40834455078155297, representativeIndex := 21, representative := 1101189391024466, permutationCode := 8974763 },
  { mask := 40850918829042721, representativeIndex := 134, representative := 5471842305819426, permutationCode := 5785549 },
  { mask := 40850931646444577, representativeIndex := 13, representative := 936555774413059, permutationCode := 10296643 },
  { mask := 45321743511165985, representativeIndex := 108, representative := 5309044062667096, permutationCode := 8745331 },
  { mask := 54335326236027937, representativeIndex := 108, representative := 5309044062667096, permutationCode := 8974763 },
]

def nearOrbitMasksG4B10P021 : List ℕ :=
  nearOrbitWitnessesG4B10P021.map NearOrbitWitness.mask

end SRG266.Certificates
