/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG4B8P08A : List NearOrbitWitness := [
  { mask := 5023301986067082, representativeIndex := 58, representative := 4880088786911301, permutationCode := 11508770 },
  { mask := 5023303865057930, representativeIndex := 5, representative := 521904330752131, permutationCode := 12426498 },
  { mask := 5023304116708490, representativeIndex := 59, representative := 4880089787222277, permutationCode := 11508770 },
  { mask := 5023310307312266, representativeIndex := 59, representative := 4880089787222277, permutationCode := 7802452 },
  { mask := 5023310558962826, representativeIndex := 74, representative := 4886687729180809, permutationCode := 15946840 },
  { mask := 5023312437953674, representativeIndex := 58, representative := 4880088786911301, permutationCode := 7802452 },
  { mask := 5437951001300106, representativeIndex := 57, representative := 4877219205173509, permutationCode := 16405704 },
  { mask := 5437963441226122, representativeIndex := 56, representative := 4877206765247493, permutationCode := 16405704 },
  { mask := 5445438228078986, representativeIndex := 27, representative := 4737706040868995, permutationCode := 13350953 },
  { mask := 5445441172390538, representativeIndex := 19, representative := 971434373253217, permutationCode := 10991666 },
  { mask := 5445441424041098, representativeIndex := 33, representative := 4746158597071109, permutationCode := 14498113 },
  { mask := 5508179110529674, representativeIndex := 65, representative := 4884693992026373, permutationCode := 16405704 },
  { mask := 5508188304163466, representativeIndex := 10, representative := 805516304957699, permutationCode := 12368258 },
  { mask := 5508194746417802, representativeIndex := 67, representative := 4884697187988485, permutationCode := 16405704 },
  { mask := 5860169463841162, representativeIndex := 49, representative := 4870616137931781, permutationCode := 16405704 },
  { mask := 5867652571939210, representativeIndex := 35, representative := 4746164099830021, permutationCode := 7886284 },
  { mask := 5867653637259914, representativeIndex := 68, representative := 4884703252766981, permutationCode := 14498113 },
  { mask := 5867653888910474, representativeIndex := 66, representative := 4884696810512645, permutationCode := 14498113 },
  { mask := 5992104610040970, representativeIndex := 30, representative := 4738680991731973, permutationCode := 16405704 },
  { mask := 6008116247643274, representativeIndex := 94, representative := 4917675690942625, permutationCode := 15946840 },
  { mask := 6062334849911946, representativeIndex := 35, representative := 4746164099830021, permutationCode := 16405704 },
  { mask := 6062342164554890, representativeIndex := 36, representative := 4746165165150725, permutationCode := 16405704 },
  { mask := 6062348606809226, representativeIndex := 34, representative := 4746158722896389, permutationCode := 16405704 },
  { mask := 6070863379416202, representativeIndex := 73, representative := 4886627775534085, permutationCode := 16405704 },
  { mask := 6078344608523402, representativeIndex := 6, representative := 522865463902277, permutationCode := 14498113 },
  { mask := 6078346487514250, representativeIndex := 1, representative := 520940379115651, permutationCode := 13350953 },
  { mask := 6985900189682314, representativeIndex := 82, representative := 4901170560315653, permutationCode := 16405704 },
  { mask := 6985931931206282, representativeIndex := 17, representative := 944054518399235, permutationCode := 12368258 },
  { mask := 7117849906449546, representativeIndex := 45, representative := 4763825868824721, permutationCode := 15946840 },
  { mask := 7117879768982666, representativeIndex := 38, representative := 4746233691693193, permutationCode := 15946840 },
  { mask := 7126362800065674, representativeIndex := 89, representative := 4909691775176965, permutationCode := 16405704 },
  { mask := 7133853222806666, representativeIndex := 84, representative := 4901264579059849, permutationCode := 15946840 },
  { mask := 7133861544051850, representativeIndex := 88, representative := 4904563088679073, permutationCode := 15946840 },
  { mask := 7133875770696842, representativeIndex := 70, representative := 4884771905134729, permutationCode := 15946840 },
  { mask := 9526626735211658, representativeIndex := 51, representative := 4871584208249093, permutationCode := 11508770 },
  { mask := 9808300366840202, representativeIndex := 61, representative := 4882779487048707, permutationCode := 13234473 },
  { mask := 9808303562802314, representativeIndex := 72, representative := 4886619076813061, permutationCode := 14498113 },
  { mask := 10002982644812938, representativeIndex := 60, representative := 4882766229258371, permutationCode := 13350953 },
  { mask := 10002998280701066, representativeIndex := 62, representative := 4883797015087241, permutationCode := 13350953 },
  { mask := 10018994282415242, representativeIndex := 2, representative := 520943197601923, permutationCode := 13350953 },
  { mask := 11480703723965578, representativeIndex := 78, representative := 4894642210220293, permutationCode := 6509692 },
  { mask := 11496715361567882, representativeIndex := 79, representative := 4894673951744261, permutationCode := 6509692 },
  { mask := 13740502983065994, representativeIndex := 50, representative := 4871578210577413, permutationCode := 11508770 },
  { mask := 13872438129265802, representativeIndex := 32, representative := 4739643064377605, permutationCode := 11508770 },
  { mask := 14162640290398602, representativeIndex := 100, representative := 5041862929749076, permutationCode := 10296643 },
  { mask := 14232871595590282, representativeIndex := 48, representative := 4870615760455941, permutationCode := 14498113 },
  { mask := 14357322568371338, representativeIndex := 99, representative := 5040902736094354, permutationCode := 9149483 },
  { mask := 14364812991112330, representativeIndex := 29, representative := 4738668174330117, permutationCode := 14498113 },
  { mask := 14373334205973642, representativeIndex := 98, representative := 5040876992242066, permutationCode := 9149483 },
  { mask := 14787025455981706, representativeIndex := 55, representative := 4877206387771653, permutationCode := 14498113 },
  { mask := 14787027334972554, representativeIndex := 54, representative := 4877204508780805, permutationCode := 14498113 },
  { mask := 15842526755622026, representativeIndex := 91, representative := 4910653847822597, permutationCode := 6509692 },
  { mask := 15842556618155146, representativeIndex := 97, representative := 5033212605572358, permutationCode := 10296643 },
  { mask := 36531976650990730, representativeIndex := 76, representative := 4887108342108321, permutationCode := 13350953 },
  { mask := 36531984972235914, representativeIndex := 63, representative := 4883809832489097, permutationCode := 13350953 },
  { mask := 36531999198880906, representativeIndex := 47, representative := 4869653626994819, permutationCode := 13350953 },
  { mask := 36540497865852042, representativeIndex := 122, representative := 5434388141162836, permutationCode := 7802452 },
  { mask := 40761858287125130, representativeIndex := 83, representative := 4901195926692101, permutationCode := 14498113 },
  { mask := 40886309259906186, representativeIndex := 107, representative := 5302446997291348, permutationCode := 7802452 },
  { mask := 40886339122439306, representativeIndex := 62, representative := 4883797015087241, permutationCode := 10267523 },
  { mask := 40893799682647178, representativeIndex := 40, representative := 4746371122253969, permutationCode := 13350953 },
  { mask := 40902320897508490, representativeIndex := 126, representative := 5443184217145700, permutationCode := 7802452 },
  { mask := 45256661821408394, representativeIndex := 90, representative := 4909708820308229, permutationCode := 14498113 },
]

def nearOrbitMasksG4B8P08A : List ℕ :=
  nearOrbitWitnessesG4B8P08A.map NearOrbitWitness.mask

end SRG266.Certificates
