/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B10P124 : List NearOrbitWitness := [
  { mask := 13952579645283620, representativeIndex := 381, representative := 7970727331826954, permutationCode := 8942493 },
  { mask := 13953541717929252, representativeIndex := 91, representative := 4746371122507921, permutationCode := 14527233 },
  { mask := 13960070068024612, representativeIndex := 141, representative := 4954178442670225, permutationCode := 14527233 },
  { mask := 13970034391854372, representativeIndex := 382, representative := 7971826835033362, permutationCode := 8942493 },
  { mask := 13986020663080228, representativeIndex := 384, representative := 7972872726187096, permutationCode := 8942493 },
  { mask := 13986046029456676, representativeIndex := 383, representative := 7971842940669202, permutationCode := 8942493 },
  { mask := 14375685400409380, representativeIndex := 284, representative := 5754129564511241, permutationCode := 8942493 },
  { mask := 14783810372967716, representativeIndex := 359, representative := 6848293771387907, permutationCode := 9117227 },
  { mask := 14784772445613348, representativeIndex := 194, representative := 5161986517805329, permutationCode := 14527233 },
  { mask := 14791300795708708, representativeIndex := 222, representative := 5369793837967633, permutationCode := 14527233 },
  { mask := 14797885047876900, representativeIndex := 200, representative := 5231255750351377, permutationCode := 14527233 },
  { mask := 14799806374681892, representativeIndex := 325, representative := 5863472539074914, permutationCode := 16333121 },
  { mask := 14799807314177316, representativeIndex := 326, representative := 5863474415968674, permutationCode := 16333121 },
  { mask := 14799813689324836, representativeIndex := 327, representative := 5863474604706594, permutationCode := 16333121 },
  { mask := 14814377721802020, representativeIndex := 242, representative := 5440781384525062, permutationCode := 9117227 },
  { mask := 14814390539203876, representativeIndex := 192, representative := 5159856228770051, permutationCode := 9117227 },
  { mask := 14817245015616804, representativeIndex := 393, representative := 13688834752453649, permutationCode := 11297748 },
  { mask := 14817261121252644, representativeIndex := 378, representative := 7411076156722450, permutationCode := 9117227 },
  { mask := 14817276757140772, representativeIndex := 377, representative := 7411071960449362, permutationCode := 9117227 },
  { mask := 14938345527618852, representativeIndex := 243, representative := 5441261951099298, permutationCode := 16333121 },
  { mask := 14938351902766372, representativeIndex := 244, representative := 5441262139837218, permutationCode := 16333121 },
  { mask := 14954838201543972, representativeIndex := 197, representative := 5231118319790601, permutationCode := 5300715 },
  { mask := 15840303607786788, representativeIndex := 78, representative := 4738674616838405, permutationCode := 7664034 },
  { mask := 15853416210050340, representativeIndex := 341, representative := 6034517381326114, permutationCode := 8942493 },
  { mask := 15853429027452196, representativeIndex := 361, representative := 6849736471423265, permutationCode := 7664034 },
  { mask := 15855321431219492, representativeIndex := 398, representative := 14250446602019218, permutationCode := 5300715 },
  { mask := 15855338476350756, representativeIndex := 398, representative := 14250446602019218, permutationCode := 436023 },
  { mask := 15872776177790244, representativeIndex := 391, representative := 13672342078528529, permutationCode := 11297748 },
  { mask := 16063128751381796, representativeIndex := 318, representative := 5860178225728778, permutationCode := 8942493 },
  { mask := 16064090824027428, representativeIndex := 331, representative := 5877770402860306, permutationCode := 8942493 },
  { mask := 16064097199174948, representativeIndex := 337, representative := 5894796190092376, permutationCode := 8942493 },
  { mask := 16064106929663268, representativeIndex := 334, representative := 5893782040462610, permutationCode := 8942493 },
  { mask := 16080583497952548, representativeIndex := 320, representative := 5861277728935186, permutationCode := 8942493 },
  { mask := 22889410155326756, representativeIndex := 385, representative := 7974021645173090, permutationCode := 2185463 },
  { mask := 23720640883010852, representativeIndex := 386, representative := 7974055703979298, permutationCode := 9117227 },
  { mask := 23736620779089188, representativeIndex := 386, representative := 7974055703979298, permutationCode := 16333121 },
  { mask := 23736636884725028, representativeIndex := 385, representative := 7974021645173090, permutationCode := 16333121 },
  { mask := 23736652520613156, representativeIndex := 385, representative := 7974021645173090, permutationCode := 9117227 },
  { mask := 23944428099251492, representativeIndex := 316, representative := 5846984090782982, permutationCode := 8942493 },
  { mask := 23944434474399012, representativeIndex := 294, representative := 5792761292243203, permutationCode := 9117227 },
  { mask := 23944444204887332, representativeIndex := 323, representative := 5862995728385286, permutationCode := 9117227 },
  { mask := 27252246927711524, representativeIndex := 382, representative := 7971826835033362, permutationCode := 2185463 },
  { mask := 27252263972842788, representativeIndex := 385, representative := 7974021645173090, permutationCode := 8942493 },
  { mask := 27253209000357156, representativeIndex := 109, representative := 4772347083939985, permutationCode := 14527233 },
  { mask := 27259737350452516, representativeIndex := 159, representative := 4980154404102289, permutationCode := 14527233 },
  { mask := 27259762716828964, representativeIndex := 155, representative := 4980129037725841, permutationCode := 14527233 },
  { mask := 27269701674282276, representativeIndex := 381, representative := 7970727331826954, permutationCode := 2185463 },
  { mask := 27285713311884580, representativeIndex := 387, representative := 7976168039844208, permutationCode := 8942493 },
  { mask := 27675346307689764, representativeIndex := 282, representative := 5741428876454177, permutationCode := 8942493 },
  { mask := 27675362413325604, representativeIndex := 285, representative := 5757440514056481, permutationCode := 8942493 },
  { mask := 27675378049213732, representativeIndex := 132, representative := 4910198148770081, permutationCode := 7664034 },
  { mask := 27691838981614884, representativeIndex := 279, representative := 5724936202529057, permutationCode := 8942493 },
  { mask := 28222032913968420, representativeIndex := 338, representative := 5897869252272484, permutationCode := 8942493 },
  { mask := 28238012810046756, representativeIndex := 332, representative := 5881889356194148, permutationCode := 8942493 },
  { mask := 28238044551570724, representativeIndex := 339, representative := 5897885357908324, permutationCode := 8942493 },
  { mask := 28254505483971876, representativeIndex := 202, representative := 5232216757676305, permutationCode := 5300715 },
  { mask := 28292247048203556, representativeIndex := 196, representative := 5194490829332753, permutationCode := 14527233 },
  { mask := 28298769023151396, representativeIndex := 233, representative := 5402298526970897, permutationCode := 14527233 },
  { mask := 28298775398298916, representativeIndex := 232, representative := 5402298149495057, permutationCode := 14527233 },
  { mask := 28298785128787236, representativeIndex := 230, representative := 5402264468164689, permutationCode := 14527233 },
  { mask := 28307280977272100, representativeIndex := 293, representative := 5792748852317187, permutationCode := 9117227 },
  { mask := 28307281916767524, representativeIndex := 315, representative := 5846979894509894, permutationCode := 8942493 },
  { mask := 28307313658291492, representativeIndex := 321, representative := 5862975896224070, permutationCode := 9117227 },
  { mask := 28308243049917732, representativeIndex := 20, representative := 832659482722385, permutationCode := 14527233 },
  { mask := 28324735723842852, representativeIndex := 329, representative := 5865121821147476, permutationCode := 8942493 },
  { mask := 28324751359730980, representativeIndex := 328, representative := 5865106185259348, permutationCode := 8942493 },
  { mask := 29347778210376996, representativeIndex := 92, representative := 4746371185420561, permutationCode := 7664034 },
  { mask := 29354300185324836, representativeIndex := 327, representative := 5863474604706594, permutationCode := 8942493 },
  { mask := 29362813078940964, representativeIndex := 325, representative := 5863472539074914, permutationCode := 8942493 },
  { mask := 29363774212091172, representativeIndex := 257, representative := 5508334370786578, permutationCode := 11508770 },
  { mask := 29363789847979300, representativeIndex := 123, representative := 4887108405274913, permutationCode := 7664034 },
  { mask := 31614087004499236, representativeIndex := 386, representative := 7974055703979298, permutationCode := 8942493 },
  { mask := 32653125052345636, representativeIndex := 322, representative := 5862993849394438, permutationCode := 9117227 },
  { mask := 40906594358244644, representativeIndex := 341, representative := 6034517381326114, permutationCode := 16333121 },
  { mask := 45253444859403556, representativeIndex := 399, representative := 14250478783931666, permutationCode := 5300715 },
  { mask := 45253461904534820, representativeIndex := 398, representative := 14250446602019218, permutationCode := 7802452 },
  { mask := 45254406932049188, representativeIndex := 362, representative := 6850424060423185, permutationCode := 14527233 },
  { mask := 45254423037685028, representativeIndex := 318, representative := 5860178225728778, permutationCode := 11508770 },
  { mask := 45254438673573156, representativeIndex := 113, representative := 4877212830279941, permutationCode := 7664034 },
  { mask := 45260935282144548, representativeIndex := 375, representative := 7058231380585489, permutationCode := 14527233 },
  { mask := 45267525909460260, representativeIndex := 342, representative := 6035531090567400, permutationCode := 8942493 },
  { mask := 45267548457350436, representativeIndex := 331, representative := 5877770402860306, permutationCode := 11508770 },
  { mask := 45267551275836708, representativeIndex := 340, representative := 6034501305049506, permutationCode := 8942493 },
  { mask := 45269473542137124, representativeIndex := 335, representative := 5894024719671714, permutationCode := 16333121 },
  { mask := 45284025025639716, representativeIndex := 396, representative := 14096669693552929, permutationCode := 9117227 },
  { mask := 45286911243576612, representativeIndex := 388, representative := 13665745008958481, permutationCode := 11297748 },
  { mask := 45392000117976356, representativeIndex := 335, representative := 5894024719671714, permutationCode := 8942493 },
  { mask := 45407986389202212, representativeIndex := 249, representative := 5471842306073378, permutationCode := 16333121 },
  { mask := 45408011755578660, representativeIndex := 248, representative := 5471812254802338, permutationCode := 16333121 },
  { mask := 45462214252211492, representativeIndex := 330, representative := 5877738220947858, permutationCode := 8942493 },
  { mask := 45462220627359012, representativeIndex := 336, representative := 5894764008179928, permutationCode := 8942493 },
  { mask := 45462230357847332, representativeIndex := 333, representative := 5893749858550162, permutationCode := 8942493 },
  { mask := 45468742602306852, representativeIndex := 317, representative := 5860163214772874, permutationCode := 8942493 },
  { mask := 45477255495922980, representativeIndex := 183, representative := 5049698560680610, permutationCode := 16333121 },
  { mask := 45478216629073188, representativeIndex := 46, representative := 1110010959463010, permutationCode := 16333121 },
  { mask := 45478241995449636, representativeIndex := 45, representative := 1109980908191970, permutationCode := 16333121 },
  { mask := 45494718563738916, representativeIndex := 319, representative := 5861261652658578, permutationCode := 8942493 },
  { mask := 54414094327211300, representativeIndex := 324, representative := 5863460659071394, permutationCode := 8942493 },
  { mask := 63122759538781476, representativeIndex := 326, representative := 5863474415968674, permutationCode := 8942493 },
]

def nearOrbitMasksG5B10P124 : List ℕ :=
  nearOrbitWitnessesG5B10P124.map NearOrbitWitness.mask

end SRG266.Certificates
