/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B7P052 : List NearOrbitWitness := [
  { mask := 1084721144234322, representativeIndex := 42, representative := 1084721144234322, permutationCode := 16434824 },
  { mask := 1109710606139730, representativeIndex := 43, representative := 1109710606139730, permutationCode := 16434824 },
  { mask := 1109736349992018, representativeIndex := 44, representative := 1109736349992018, permutationCode := 16434824 },
  { mask := 2772197553701970, representativeIndex := 10, representative := 555857224900705, permutationCode := 14570696 },
  { mask := 2773158686852178, representativeIndex := 63, representative := 1610891274461281, permutationCode := 14570696 },
  { mask := 3047326662492498, representativeIndex := 58, representative := 1395570983667809, permutationCode := 14570696 },
  { mask := 3047352406344786, representativeIndex := 59, representative := 1395600846200929, permutationCode := 14570696 },
  { mask := 3056732036890962, representativeIndex := 37, representative := 1043595200923745, permutationCode := 14570696 },
  { mask := 3079824976348242, representativeIndex := 71, representative := 2521346142609505, permutationCode := 14570696 },
  { mask := 3187812886086738, representativeIndex := 53, representative := 1387087952584801, permutationCode := 14570696 },
  { mask := 3258043125957714, representativeIndex := 10, representative := 555857224900705, permutationCode := 2185463 },
  { mask := 3603428281386066, representativeIndex := 27, representative := 971472557285473, permutationCode := 14570696 },
  { mask := 3610018908701778, representativeIndex := 57, representative := 1393678579900513, permutationCode := 14570696 },
  { mask := 3617502016799826, representativeIndex := 62, representative := 1604369299513441, permutationCode := 14570696 },
  { mask := 3633978585089106, representativeIndex := 72, representative := 2659884356051041, permutationCode := 14570696 },
  { mask := 5049389892403410, representativeIndex := 80, representative := 4738676495829253, permutationCode := 7802452 },
  { mask := 5300522854351186, representativeIndex := 211, representative := 5300522854351186, permutationCode := 16434824 },
  { mask := 5331073158054226, representativeIndex := 215, representative := 5331073158054226, permutationCode := 16434824 },
  { mask := 5439061067792722, representativeIndex := 238, representative := 5439061067792722, permutationCode := 16434824 },
  { mask := 5471533637796178, representativeIndex := 245, representative := 5471533637796178, permutationCode := 16434824 },
  { mask := 5508330174513490, representativeIndex := 94, representative := 4768269225140483, permutationCode := 5475421 },
  { mask := 5541763877667154, representativeIndex := 268, representative := 5541763877667154, permutationCode := 16434824 },
  { mask := 5854676463092050, representativeIndex := 16, representative := 828583500816643, permutationCode := 11297748 },
  { mask := 5893739660411218, representativeIndex := 43, representative := 1109710606139730, permutationCode := 11297748 },
  { mask := 6088460122162258, representativeIndex := 348, representative := 6088460122162258, permutationCode := 16434824 },
  { mask := 6355556903911762, representativeIndex := 328, representative := 5865106185259348, permutationCode := 16333121 },
  { mask := 6370111205900626, representativeIndex := 254, representative := 5508194746671754, permutationCode := 9117227 },
  { mask := 6987005948756178, representativeIndex := 294, representative := 5792761292243203, permutationCode := 7664034 },
  { mask := 6988928215056594, representativeIndex := 316, representative := 5846984090782982, permutationCode := 7802452 },
  { mask := 6988934653116754, representativeIndex := 24, representative := 936571410555139, permutationCode := 11297748 },
  { mask := 6988960396969042, representativeIndex := 288, representative := 5776752850603011, permutationCode := 7802452 },
  { mask := 6993534361764178, representativeIndex := 58, representative := 1395570983667809, permutationCode := 7802452 },
  { mask := 7019510700672082, representativeIndex := 300, representative := 5794190552041569, permutationCode := 7802452 },
  { mask := 7127498610410578, representativeIndex := 299, representative := 5793795274034185, permutationCode := 7664034 },
  { mask := 7196767717131346, representativeIndex := 53, representative := 1387087952584801, permutationCode := 2185463 },
  { mask := 7409149694148946, representativeIndex := 314, representative := 5827670753927457, permutationCode := 7664034 },
  { mask := 7411071960449362, representativeIndex := 377, representative := 7411071960449362, permutationCode := 16434824 },
  { mask := 8041111047078994, representativeIndex := 169, representative := 5015751169544838, permutationCode := 9117227 },
  { mask := 8058548748518482, representativeIndex := 256, representative := 5508332177232530, permutationCode := 9117227 },
  { mask := 9801914885308754, representativeIndex := 300, representative := 5794190552041569, permutationCode := 14570696 },
  { mask := 9825874561696082, representativeIndex := 334, representative := 5893782040462610, permutationCode := 5475421 },
  { mask := 11481839534310482, representativeIndex := 297, representative := 5793786952789001, permutationCode := 7802452 },
  { mask := 11490352427926610, representativeIndex := 236, representative := 5438856987583238, permutationCode := 11508770 },
  { mask := 11496874402874450, representativeIndex := 164, representative := 4980427388330081, permutationCode := 14570696 },
  { mask := 11514312104313938, representativeIndex := 301, representative := 5794198866995489, permutationCode := 7802452 },
  { mask := 11982719975130194, representativeIndex := 313, representative := 5827654117728353, permutationCode := 14570696 },
  { mask := 11999196543419474, representativeIndex := 365, representative := 6883169174265953, permutationCode := 14570696 },
  { mask := 18807991018881234, representativeIndex := 376, representative := 7060430386998305, permutationCode := 436023 },
  { mask := 18807997456941394, representativeIndex := 215, representative := 5331073158054226, permutationCode := 5475421 },
  { mask := 18808023200793682, representativeIndex := 375, representative := 7058231380585489, permutationCode := 436023 },
  { mask := 18815480565039442, representativeIndex := 217, representative := 5331106965209874, permutationCode := 5475421 },
  { mask := 19362176809534546, representativeIndex := 368, representative := 6919669679758353, permutationCode := 7802452 },
  { mask := 19378172811248722, representativeIndex := 369, representative := 6919944289229345, permutationCode := 7802452 },
  { mask := 19863057250354258, representativeIndex := 317, representative := 5860163214772874, permutationCode := 9117227 },
  { mask := 20496434999559250, representativeIndex := 52, representative := 1382762853409795, permutationCode := 2185463 },
  { mask := 20503918107657298, representativeIndex := 61, representative := 1593453573022723, permutationCode := 2185463 },
  { mask := 20918572306891858, representativeIndex := 374, representative := 7056101091550211, permutationCode := 436023 },
  { mask := 36541618040308818, representativeIndex := 198, representative := 5231120198781449, permutationCode := 7802452 },
  { mask := 36558094608598098, representativeIndex := 201, representative := 5231257503516945, permutationCode := 7802452 },
  { mask := 36809195388633426, representativeIndex := 395, representative := 13766556415374612, permutationCode := 2185463 },
  { mask := 36823269124047186, representativeIndex := 373, representative := 6993568546395666, permutationCode := 5475421 },
  { mask := 38495710664950866, representativeIndex := 306, representative := 5794891581278481, permutationCode := 7664034 },
  { mask := 38497632931251282, representativeIndex := 352, representative := 6339565098470674, permutationCode := 7802452 },
  { mask := 38510745533514834, representativeIndex := 355, representative := 6374440501348720, permutationCode := 7802452 },
  { mask := 38511706666665042, representativeIndex := 353, representative := 6353636703243026, permutationCode := 11508770 },
]

def nearOrbitMasksG5B7P052 : List ℕ :=
  nearOrbitWitnessesG5B7P052.map NearOrbitWitness.mask

end SRG266.Certificates
