/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B8P094 : List NearOrbitWitness := [
  { mask := 13735975808749972, representativeIndex := 71, representative := 2521346142609505, permutationCode := 9117227 },
  { mask := 13742560060918164, representativeIndex := 184, representative := 5050214532391116, permutationCode := 7802452 },
  { mask := 13742564557074836, representativeIndex := 125, representative := 4908755448734723, permutationCode := 11508770 },
  { mask := 13742572878320020, representativeIndex := 374, representative := 7056101091550211, permutationCode := 7664034 },
  { mask := 13760027624890772, representativeIndex := 134, representative := 4945519803539587, permutationCode := 7664034 },
  { mask := 13761920028658068, representativeIndex := 168, representative := 5015751043719558, permutationCode := 7802452 },
  { mask := 13766524233462164, representativeIndex := 378, representative := 7411076156722450, permutationCode := 5300715 },
  { mask := 13775039006069140, representativeIndex := 37, representative := 1043595200923745, permutationCode := 9117227 },
  { mask := 13775045448323476, representativeIndex := 377, representative := 7411071960449362, permutationCode := 5300715 },
  { mask := 13775062493454740, representativeIndex := 379, representative := 7412102746278232, permutationCode := 5300715 },
  { mask := 13944745579033748, representativeIndex := 123, representative := 4887108405274913, permutationCode := 14527233 },
  { mask := 13953251158006932, representativeIndex := 94, representative := 4768269225140483, permutationCode := 11508770 },
  { mask := 13953258472649876, representativeIndex := 124, representative := 4908729704882435, permutationCode := 11508770 },
  { mask := 13953266793895060, representativeIndex := 257, representative := 5508334370786578, permutationCode := 16333121 },
  { mask := 13959780447597716, representativeIndex := 176, representative := 5023447612301714, permutationCode := 16333121 },
  { mask := 13969727726296212, representativeIndex := 332, representative := 5881889356194148, permutationCode := 436023 },
  { mask := 13969759467820180, representativeIndex := 20, representative := 832659482722385, permutationCode := 9117227 },
  { mask := 13977218149037204, representativeIndex := 339, representative := 5897885357908324, permutationCode := 436023 },
  { mask := 22748642632550804, representativeIndex := 186, representative := 5050351962951892, permutationCode := 7802452 },
  { mask := 22748643010026644, representativeIndex := 309, representative := 5811660181645857, permutationCode := 436023 },
  { mask := 22748647128707476, representativeIndex := 308, representative := 5811659116325153, permutationCode := 9117227 },
  { mask := 22748672495083924, representativeIndex := 332, representative := 5881889356194148, permutationCode := 9117227 },
  { mask := 22748672620909204, representativeIndex := 53, representative := 1387087952584801, permutationCode := 9117227 },
  { mask := 22748672872559764, representativeIndex := 282, representative := 5741428876454177, permutationCode := 9117227 },
  { mask := 22751526032001428, representativeIndex := 169, representative := 5015751169544838, permutationCode := 7802452 },
  { mask := 22751533346644372, representativeIndex := 117, representative := 4883809832743049, permutationCode := 11297748 },
  { mask := 22751559090496660, representativeIndex := 109, representative := 4772347083939985, permutationCode := 436023 },
  { mask := 22756130236805524, representativeIndex := 164, representative := 4980427388330081, permutationCode := 14527233 },
  { mask := 22756133055291796, representativeIndex := 167, representative := 4980435829109281, permutationCode := 14527233 },
  { mask := 22756133432767636, representativeIndex := 166, representative := 4980429453961761, permutationCode := 14527233 },
  { mask := 22782106198237588, representativeIndex := 355, representative := 6374440501348720, permutationCode := 9117227 },
  { mask := 22782109394199700, representativeIndex := 106, representative := 4772141126836741, permutationCode := 436023 },
  { mask := 22890097303938196, representativeIndex := 107, representative := 4772345207046225, permutationCode := 436023 },
  { mask := 22896593912509588, representativeIndex := 313, representative := 5827654117728353, permutationCode := 436023 },
  { mask := 22959333729639572, representativeIndex := 53, representative := 1387087952584801, permutationCode := 436023 },
  { mask := 22959341044282516, representativeIndex := 59, representative := 1395600846200929, permutationCode := 436023 },
  { mask := 22959366410658964, representativeIndex := 20, representative := 832659482722385, permutationCode := 436023 },
  { mask := 22966824152380564, representativeIndex := 10, representative := 555857224900705, permutationCode := 14527233 },
  { mask := 27243444413668500, representativeIndex := 308, representative := 5811659116325153, permutationCode := 436023 },
  { mask := 27243476155192468, representativeIndex := 59, representative := 1395600846200929, permutationCode := 9117227 },
  { mask := 27244438227838100, representativeIndex := 108, representative := 4772346207357201, permutationCode := 436023 },
  { mask := 27252951121454228, representativeIndex := 110, representative := 4772353522000145, permutationCode := 436023 },
  { mask := 27259456051270804, representativeIndex := 314, representative := 5827670753927457, permutationCode := 436023 },
  { mask := 27259472156906644, representativeIndex := 58, representative := 1395570983667809, permutationCode := 9117227 },
  { mask := 27259473096402068, representativeIndex := 208, representative := 5264721069203729, permutationCode := 436023 },
  { mask := 27276910797841556, representativeIndex := 105, representative := 4772140061516037, permutationCode := 436023 },
  { mask := 31668014577097876, representativeIndex := 282, representative := 5741428876454177, permutationCode := 436023 },
  { mask := 31675504999838868, representativeIndex := 132, representative := 4910198148770081, permutationCode := 14527233 },
  { mask := 31684026214700180, representativeIndex := 285, representative := 5757440514056481, permutationCode := 436023 },
  { mask := 31684043259831444, representativeIndex := 196, representative := 5194490829332753, permutationCode := 436023 },
]

def nearOrbitMasksG5B8P094 : List ℕ :=
  nearOrbitWitnessesG5B8P094.map NearOrbitWitness.mask

end SRG266.Certificates
