/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B8P0E8 : List NearOrbitWitness := [
  { mask := 5871980867330280, representativeIndex := 259, representative := 5509293373295378, permutationCode := 14527233 },
  { mask := 5895070610825448, representativeIndex := 249, representative := 5471842306073378, permutationCode := 9117227 },
  { mask := 6012441347072232, representativeIndex := 310, representative := 5824335125850633, permutationCode := 11297748 },
  { mask := 6035531090567400, representativeIndex := 342, representative := 6035531090567400, permutationCode := 16434824 },
  { mask := 6082671586943208, representativeIndex := 42, representative := 1084721144234322, permutationCode := 14527233 },
  { mask := 6105738782548200, representativeIndex := 271, representative := 5541797684822802, permutationCode := 9117227 },
  { mask := 6105745224802536, representativeIndex := 351, representative := 6104747621197090, permutationCode := 406910 },
  { mask := 6105761330438376, representativeIndex := 217, representative := 5331106965209874, permutationCode := 9117227 },
  { mask := 7138186643480808, representativeIndex := 210, representative := 5300320653132550, permutationCode := 7664034 },
  { mask := 7161276386975976, representativeIndex := 213, representative := 5300526610235794, permutationCode := 7664034 },
  { mask := 9561502138343656, representativeIndex := 67, representative := 2165045009023586, permutationCode := 406910 },
  { mask := 9812628662231272, representativeIndex := 266, representative := 5512178840474708, permutationCode := 14570696 },
  { mask := 9835688543193320, representativeIndex := 363, representative := 6855030144218129, permutationCode := 2214590 },
  { mask := 9835718405726440, representativeIndex := 349, representative := 6088461999056018, permutationCode := 406910 },
  { mask := 9951166875672808, representativeIndex := 17, representative := 828608993018371, permutationCode := 7664034 },
  { mask := 10020435982393576, representativeIndex := 178, representative := 5027294401369172, permutationCode := 14570696 },
  { mask := 10046379262806248, representativeIndex := 369, representative := 6919944289229345, permutationCode := 11508770 },
  { mask := 10046386577449192, representativeIndex := 350, representative := 6104732610241186, permutationCode := 406910 },
  { mask := 10046394898694376, representativeIndex := 246, representative := 5471537393680786, permutationCode := 7664034 },
  { mask := 10373379340542184, representativeIndex := 263, representative := 5511217770237202, permutationCode := 14527233 },
  { mask := 10375303485833448, representativeIndex := 261, representative := 5510254443532884, permutationCode := 14570696 },
  { mask := 10389872014467304, representativeIndex := 348, representative := 6088460122162258, permutationCode := 406910 },
  { mask := 11498149746903272, representativeIndex := 187, representative := 5050358401012052, permutationCode := 14570696 },
  { mask := 11498162564305128, representativeIndex := 186, representative := 5050351962951892, permutationCode := 14570696 },
  { mask := 11498179609436392, representativeIndex := 188, representative := 5050384144864340, permutationCode := 14570696 },
  { mask := 11501033146353896, representativeIndex := 198, representative := 5231120198781449, permutationCode := 11508770 },
  { mask := 11501040460996840, representativeIndex := 224, representative := 5371580678523401, permutationCode := 11508770 },
  { mask := 11501048782242024, representativeIndex := 241, representative := 5440781132874502, permutationCode := 7664034 },
  { mask := 11524130204492008, representativeIndex := 227, representative := 5371992970205729, permutationCode := 11508770 },
  { mask := 13775404130050280, representativeIndex := 79, representative := 4738674742663685, permutationCode := 11508770 },
  { mask := 13960121706717416, representativeIndex := 175, representative := 5023446672806290, permutationCode := 14527233 },
  { mask := 14408209609105640, representativeIndex := 340, representative := 6034501305049506, permutationCode := 406910 },
  { mask := 14830422073975016, representativeIndex := 341, representative := 6034517381326114, permutationCode := 406910 },
  { mask := 15855373069912296, representativeIndex := 197, representative := 5231118319790601, permutationCode := 11508770 },
  { mask := 15885953236148456, representativeIndex := 200, representative := 5231255750351377, permutationCode := 11508770 },
  { mask := 18957249447305448, representativeIndex := 217, representative := 5331106965209874, permutationCode := 7664034 },
  { mask := 19379455469920488, representativeIndex := 271, representative := 5541797684822802, permutationCode := 14527233 },
  { mask := 19379461912174824, representativeIndex := 272, representative := 5541797936473362, permutationCode := 14527233 },
  { mask := 19379478017810664, representativeIndex := 268, representative := 5541763877667154, permutationCode := 14527233 },
  { mask := 27259788989145320, representativeIndex := 138, representative := 4949368280762885, permutationCode := 11508770 },
  { mask := 27674435873736936, representativeIndex := 370, representative := 6919967776614945, permutationCode := 11508770 },
  { mask := 27681926296477928, representativeIndex := 342, representative := 6035531090567400, permutationCode := 406910 },
  { mask := 36549422673928424, representativeIndex := 62, representative := 1604369299513441, permutationCode := 406910 },
  { mask := 36552306073379048, representativeIndex := 63, representative := 1610891274461281, permutationCode := 16333121 },
  { mask := 36575395816874216, representativeIndex := 61, representative := 1593453573022723, permutationCode := 406910 },
  { mask := 40906645996937448, representativeIndex := 296, representative := 5793784822147593, permutationCode := 11508770 },
  { mask := 45260986920837352, representativeIndex := 297, representative := 5793786952789001, permutationCode := 11297748 },
  { mask := 45266621917761768, representativeIndex := 309, representative := 5811660181645857, permutationCode := 11508770 },
  { mask := 45267583990407400, representativeIndex := 287, representative := 5776750719961603, permutationCode := 11508770 },
  { mask := 45269508135698664, representativeIndex := 237, representative := 5438859118224646, permutationCode := 7802452 },
  { mask := 45284076664332520, representativeIndex := 304, representative := 5794205435075105, permutationCode := 11508770 },
]

def nearOrbitMasksG5B8P0E8 : List ℕ :=
  nearOrbitWitnessesG5B8P0E8.map NearOrbitWitness.mask

end SRG266.Certificates
