/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B8P091 : List NearOrbitWitness := [
  { mask := 4746371122507921, representativeIndex := 91, representative := 4746371122507921, permutationCode := 16434824 },
  { mask := 4746373001498769, representativeIndex := 72, representative := 2659884356051041, permutationCode := 9117227 },
  { mask := 4769431003469969, representativeIndex := 99, representative := 4769431003469969, permutationCode := 16434824 },
  { mask := 4769462744993937, representativeIndex := 27, representative := 971472557285473, permutationCode := 9117227 },
  { mask := 4770424817639569, representativeIndex := 103, representative := 4770424817639569, permutationCode := 16434824 },
  { mask := 4772317221406865, representativeIndex := 102, representative := 4770399514175761, permutationCode := 2214590 },
  { mask := 4772347083939985, representativeIndex := 109, representative := 4772347083939985, permutationCode := 16434824 },
  { mask := 4776921426210961, representativeIndex := 18, representative := 830705474898001, permutationCode := 2214590 },
  { mask := 4954178442670225, representativeIndex := 141, representative := 4954178442670225, permutationCode := 16434824 },
  { mask := 4955139575820433, representativeIndex := 143, representative := 4955139575820433, permutationCode := 16434824 },
  { mask := 4957063721111697, representativeIndex := 70, representative := 2519149015187537, permutationCode := 9117227 },
  { mask := 4980121723082897, representativeIndex := 152, representative := 4980121723082897, permutationCode := 16434824 },
  { mask := 4980124541569169, representativeIndex := 153, representative := 4980124541569169, permutationCode := 16434824 },
  { mask := 4980129037725841, representativeIndex := 155, representative := 4980129037725841, permutationCode := 16434824 },
  { mask := 4980130916716689, representativeIndex := 36, representative := 1041427936034897, permutationCode := 9117227 },
  { mask := 4980153464606865, representativeIndex := 19, representative := 830737216421969, permutationCode := 9117227 },
  { mask := 4980154404102289, representativeIndex := 159, representative := 4980154404102289, permutationCode := 16434824 },
  { mask := 4987612145823889, representativeIndex := 35, representative := 1041396194510929, permutationCode := 2214590 },
  { mask := 13672326002251921, representativeIndex := 93, representative := 4768262787080323, permutationCode := 11508770 },
  { mask := 13672328820738193, representativeIndex := 185, representative := 5050246714303564, permutationCode := 7802452 },
  { mask := 13678855291842705, representativeIndex := 381, representative := 7970727331826954, permutationCode := 5300715 },
  { mask := 13678857170833553, representativeIndex := 9, representative := 548822501466181, permutationCode := 9117227 },
  { mask := 13688802570541201, representativeIndex := 386, representative := 7974055703979298, permutationCode := 5300715 },
  { mask := 13696292993282193, representativeIndex := 385, representative := 7974021645173090, permutationCode := 406910 },
  { mask := 13704801390741649, representativeIndex := 189, representative := 5050658628510052, permutationCode := 7802452 },
  { mask := 13704807765889169, representativeIndex := 35, representative := 1041396194510929, permutationCode := 9117227 },
  { mask := 13704814208143505, representativeIndex := 385, representative := 7974021645173090, permutationCode := 5300715 },
  { mask := 13704830313779345, representativeIndex := 18, representative := 830705474898001, permutationCode := 9117227 },
  { mask := 13704831253274769, representativeIndex := 382, representative := 7971826835033362, permutationCode := 406910 },
  { mask := 18253838410455185, representativeIndex := 252, representative := 5473457780990292, permutationCode := 2214590 },
  { mask := 18253841228941457, representativeIndex := 187, representative := 5050358401012052, permutationCode := 7802452 },
  { mask := 18253845725098129, representativeIndex := 383, representative := 7971842940669202, permutationCode := 5300715 },
  { mask := 18253847604088977, representativeIndex := 62, representative := 1604369299513441, permutationCode := 9117227 },
  { mask := 18253870151979153, representativeIndex := 57, representative := 1393678579900513, permutationCode := 9117227 },
  { mask := 18253871091474577, representativeIndex := 384, representative := 7972872726187096, permutationCode := 5300715 },
  { mask := 18254832224624785, representativeIndex := 135, representative := 4945526367425027, permutationCode := 7664034 },
  { mask := 18256724628392081, representativeIndex := 170, representative := 5015757607604998, permutationCode := 7802452 },
  { mask := 18279821686530193, representativeIndex := 387, representative := 7976168039844208, permutationCode := 5300715 },
  { mask := 18287304794628241, representativeIndex := 9, representative := 548822501466181, permutationCode := 2214590 },
  { mask := 22615668756754577, representativeIndex := 382, representative := 7971826835033362, permutationCode := 5300715 },
  { mask := 22641644718186641, representativeIndex := 381, representative := 7970727331826954, permutationCode := 406910 },
  { mask := 22678408573884561, representativeIndex := 307, representative := 5809463305874449, permutationCode := 9117227 },
  { mask := 22678411392370833, representativeIndex := 188, representative := 5050384144864340, permutationCode := 7802452 },
  { mask := 22685898996625553, representativeIndex := 189, representative := 5050658628510052, permutationCode := 14527233 },
]

def nearOrbitMasksG5B8P091 : List ℕ :=
  nearOrbitWitnessesG5B8P091.map NearOrbitWitness.mask

end SRG266.Certificates
