/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B9P103 : List NearOrbitWitness := [
  { mask := 798025882470659, representativeIndex := 12, representative := 798025882470659, permutationCode := 16434824 },
  { mask := 805516305211651, representativeIndex := 13, representative := 805516305211651, permutationCode := 16434824 },
  { mask := 828583500816643, representativeIndex := 16, representative := 828583500816643, permutationCode := 16434824 },
  { mask := 936564095912195, representativeIndex := 22, representative := 936564095912195, permutationCode := 16434824 },
  { mask := 936571410555139, representativeIndex := 24, representative := 936571410555139, permutationCode := 16434824 },
  { mask := 944054518653187, representativeIndex := 25, representative := 944054518653187, permutationCode := 16434824 },
  { mask := 1352179491211523, representativeIndex := 22, representative := 936564095912195, permutationCode := 14570696 },
  { mask := 1352186805854467, representativeIndex := 23, representative := 936567291874307, permutationCode := 14570696 },
  { mask := 1358770118527235, representativeIndex := 48, representative := 1358770118527235, permutationCode := 16434824 },
  { mask := 1366260541268227, representativeIndex := 49, representative := 1366260541268227, permutationCode := 16434824 },
  { mask := 1368182807568643, representativeIndex := 30, representative := 1006797531745283, permutationCode := 14570696 },
  { mask := 1368191128813827, representativeIndex := 29, representative := 1006795401103875, permutationCode := 14570696 },
  { mask := 1382737109557507, representativeIndex := 51, representative := 1382737109557507, permutationCode := 16434824 },
  { mask := 1391258324418819, representativeIndex := 55, representative := 1391258324418819, permutationCode := 16434824 },
  { mask := 4737711606794499, representativeIndex := 73, representative := 4737711606794499, permutationCode := 16434824 },
  { mask := 4737718921437443, representativeIndex := 76, representative := 4737718921437443, permutationCode := 16434824 },
  { mask := 4768269225140483, representativeIndex := 94, representative := 4768269225140483, permutationCode := 16434824 },
  { mask := 4876257134878979, representativeIndex := 112, representative := 4876257134878979, permutationCode := 16434824 },
  { mask := 4882779109826819, representativeIndex := 110, representative := 4772353522000145, permutationCode := 5475421 },
  { mask := 4908729704882435, representativeIndex := 124, representative := 4908729704882435, permutationCode := 16434824 },
  { mask := 5159856228770051, representativeIndex := 192, representative := 5159856228770051, permutationCode := 16434824 },
  { mask := 5367663548932355, representativeIndex := 76, representative := 4737718921437443, permutationCode := 5475421 },
  { mask := 5368624682082563, representativeIndex := 220, representative := 5368624682082563, permutationCode := 16434824 },
  { mask := 5714009837510915, representativeIndex := 205, representative := 5261805928229137, permutationCode := 11297748 },
  { mask := 5720600464826627, representativeIndex := 273, representative := 5542726887711060, permutationCode := 11297748 },
  { mask := 5776749654640899, representativeIndex := 286, representative := 5776749654640899, permutationCode := 16434824 },
  { mask := 5784240077381891, representativeIndex := 207, representative := 5261837669753105, permutationCode := 11297748 },
  { mask := 5789862256904451, representativeIndex := 87, representative := 4746233880685065, permutationCode := 5475421 },
  { mask := 5789869571547395, representativeIndex := 86, representative := 4746231815053385, permutationCode := 5475421 },
  { mask := 5792752970998019, representativeIndex := 232, representative := 5402298149495057, permutationCode := 11297748 },
  { mask := 5792761292243203, representativeIndex := 294, representative := 5792761292243203, permutationCode := 16434824 },
  { mask := 5807307272986883, representativeIndex := 258, representative := 5509293184557458, permutationCode := 9117227 },
  { mask := 6845377313442051, representativeIndex := 92, representative := 4746371185420561, permutationCode := 5475421 },
  { mask := 6846345761235203, representativeIndex := 260, representative := 5510254317707604, permutationCode := 11297748 },
  { mask := 6848260712892675, representativeIndex := 327, representative := 5863474604706594, permutationCode := 7802452 },
  { mask := 6848268027535619, representativeIndex := 222, representative := 5369793837967633, permutationCode := 11297748 },
  { mask := 9239103637752067, representativeIndex := 87, representative := 4746233880685065, permutationCode := 7802452 },
  { mask := 9239119273640195, representativeIndex := 121, representative := 4886696491068425, permutationCode := 7802452 },
  { mask := 9245632927342851, representativeIndex := 107, representative := 4772345207046225, permutationCode := 5475421 },
  { mask := 9245641248588035, representativeIndex := 108, representative := 4772346207357201, permutationCode := 5475421 },
  { mask := 9255580206041347, representativeIndex := 92, representative := 4746371185420561, permutationCode := 7802452 },
  { mask := 9263070628782339, representativeIndex := 257, representative := 5508334370786578, permutationCode := 11297748 },
  { mask := 9271591843643651, representativeIndex := 123, representative := 4887108405274913, permutationCode := 7802452 },
  { mask := 9661240945084675, representativeIndex := 286, representative := 5776749654640899, permutationCode := 14570696 },
  { mask := 9661248259727619, representativeIndex := 288, representative := 5776752850603011, permutationCode := 14570696 },
  { mask := 9661256580972803, representativeIndex := 287, representative := 5776750719961603, permutationCode := 14570696 },
  { mask := 9730510051805443, representativeIndex := 73, representative := 4737711606794499, permutationCode := 14570696 },
  { mask := 9730525687693571, representativeIndex := 73, representative := 4737711606794499, permutationCode := 5475421 },
  { mask := 9731478499598595, representativeIndex := 293, representative := 5792748852317187, permutationCode := 14570696 },
  { mask := 9731486820843779, representativeIndex := 292, representative := 5792746721675779, permutationCode := 14570696 },
  { mask := 9747947753244931, representativeIndex := 327, representative := 5863474604706594, permutationCode := 5475421 },
  { mask := 9747955067887875, representativeIndex := 325, representative := 5863472539074914, permutationCode := 5475421 },
  { mask := 18667323516717315, representativeIndex := 212, representative := 5300524919982866, permutationCode := 5475421 },
  { mask := 18667330831360259, representativeIndex := 211, representative := 5300522854351186, permutationCode := 5475421 },
  { mask := 36246384141076739, representativeIndex := 212, representative := 5300524919982866, permutationCode := 7802452 },
  { mask := 36246391455719683, representativeIndex := 226, representative := 5371992844380449, permutationCode := 11297748 },
  { mask := 36253874563817731, representativeIndex := 201, representative := 5231257503516945, permutationCode := 11297748 },
  { mask := 36259504057983235, representativeIndex := 89, representative := 4746369245614161, permutationCode := 5475421 },
  { mask := 36259512379228419, representativeIndex := 90, representative := 4746370245925137, permutationCode := 5475421 },
  { mask := 36260465191133443, representativeIndex := 265, representative := 5512178462998868, permutationCode := 11297748 },
  { mask := 36262395778679043, representativeIndex := 244, representative := 5441262139837218, permutationCode := 7802452 },
]

def nearOrbitMasksG5B9P103 : List ℕ :=
  nearOrbitWitnessesG5B9P103.map NearOrbitWitness.mask

end SRG266.Certificates
