/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B9P018 : List NearOrbitWitness := [
  { mask := 14267508515786264, representativeIndex := 369, representative := 6919944289229345, permutationCode := 2214590 },
  { mask := 15913970899295768, representativeIndex := 380, representative := 7482334051469912, permutationCode := 7664034 },
  { mask := 15922483792911896, representativeIndex := 253, representative := 5475656787403108, permutationCode := 11508770 },
  { mask := 15929950795374104, representativeIndex := 380, representative := 7482334051469912, permutationCode := 2214590 },
  { mask := 15929966901009944, representativeIndex := 219, representative := 5334921446539604, permutationCode := 11508770 },
  { mask := 15929967840505368, representativeIndex := 383, representative := 7971842940669202, permutationCode := 11297748 },
  { mask := 15929969719496216, representativeIndex := 62, representative := 1604369299513441, permutationCode := 7802452 },
  { mask := 15929982536898072, representativeIndex := 219, representative := 5334921446539604, permutationCode := 406910 },
  { mask := 16344621100244504, representativeIndex := 168, representative := 5015751043719558, permutationCode := 5300715 },
  { mask := 16345583172890136, representativeIndex := 377, representative := 7411071960449362, permutationCode := 11508770 },
  { mask := 16345585051880984, representativeIndex := 37, representative := 1043595200923745, permutationCode := 7664034 },
  { mask := 23241116638424600, representativeIndex := 335, representative := 5894024719671714, permutationCode := 14527233 },
  { mask := 23381578997157400, representativeIndex := 276, representative := 5542797859458136, permutationCode := 7664034 },
  { mask := 23795270247165464, representativeIndex := 248, representative := 5471812254802338, permutationCode := 14527233 },
  { mask := 23803783140781592, representativeIndex := 340, representative := 6034501305049506, permutationCode := 11297748 },
  { mask := 23803791462026776, representativeIndex := 368, representative := 6919669679758353, permutationCode := 16333121 },
  { mask := 23811266248879640, representativeIndex := 45, representative := 1109980908191970, permutationCode := 14527233 },
  { mask := 24225920448114200, representativeIndex := 113, representative := 4877212830279941, permutationCode := 5300715 },
  { mask := 24225922327105048, representativeIndex := 3, representative := 522871906410565, permutationCode := 5300715 },
  { mask := 24866781305417240, representativeIndex := 319, representative := 5861261652658578, permutationCode := 11297748 },
  { mask := 25351665744522776, representativeIndex := 388, representative := 13665745008958481, permutationCode := 8942493 },
  { mask := 25351667623513624, representativeIndex := 144, representative := 4957064161500177, permutationCode := 8942493 },
  { mask := 27735919921057304, representativeIndex := 275, representative := 5542795728816728, permutationCode := 7664034 },
  { mask := 27744432814673432, representativeIndex := 366, representative := 6917745282816529, permutationCode := 16333121 },
  { mask := 27751915922771480, representativeIndex := 64, representative := 1672647410548962, permutationCode := 14527233 },
  { mask := 32106255846329880, representativeIndex := 357, representative := 6847513977624849, permutationCode := 16333121 },
  { mask := 40763058685681176, representativeIndex := 339, representative := 5897885357908324, permutationCode := 11508770 },
  { mask := 40764020758326808, representativeIndex := 321, representative := 5862975896224070, permutationCode := 11508770 },
  { mask := 40765944903618072, representativeIndex := 28, representative := 1006793335472195, permutationCode := 7802452 },
  { mask := 40973733299658264, representativeIndex := 161, representative := 4980161219638289, permutationCode := 16333121 },
  { mask := 40973749405294104, representativeIndex := 154, representative := 4980127160832081, permutationCode := 16333121 },
  { mask := 40973750344789528, representativeIndex := 155, representative := 4980129037725841, permutationCode := 16333121 },
  { mask := 40973752223780376, representativeIndex := 36, representative := 1041427936034897, permutationCode := 7802452 },
  { mask := 40973765041182232, representativeIndex := 156, representative := 4980131357105169, permutationCode := 16333121 },
  { mask := 41803058806173208, representativeIndex := 339, representative := 5897885357908324, permutationCode := 11297748 },
  { mask := 41804981072473624, representativeIndex := 132, representative := 4910198148770081, permutationCode := 5300715 },
  { mask := 41804982951464472, representativeIndex := 10, representative := 555857224900705, permutationCode := 5300715 },
  { mask := 41818076629605912, representativeIndex := 110, representative := 4772353522000145, permutationCode := 16333121 },
  { mask := 41818108371129880, representativeIndex := 0, representative := 520947763216451, permutationCode := 9117227 },
  { mask := 41835531376176664, representativeIndex := 123, representative := 4887108405274913, permutationCode := 5300715 },
  { mask := 42873607791779352, representativeIndex := 176, representative := 5023447612301714, permutationCode := 5300715 },
  { mask := 42874569864424984, representativeIndex := 328, representative := 5865106185259348, permutationCode := 11297748 },
  { mask := 42943838031650328, representativeIndex := 142, representative := 4954180762049553, permutationCode := 9117227 },
  { mask := 42943838971145752, representativeIndex := 387, representative := 7976168039844208, permutationCode := 11297748 },
  { mask := 42943853667538456, representativeIndex := 104, representative := 4772117513625861, permutationCode := 406910 },
  { mask := 45743706601074200, representativeIndex := 385, representative := 7974021645173090, permutationCode := 11508770 },
  { mask := 45743708480065048, representativeIndex := 35, representative := 1041396194510929, permutationCode := 7664034 },
  { mask := 45745630746365464, representativeIndex := 189, representative := 5050658628510052, permutationCode := 5300715 },
  { mask := 45758756166030872, representativeIndex := 102, representative := 4770399514175761, permutationCode := 16333121 },
  { mask := 45776181050068504, representativeIndex := 143, representative := 4955139575820433, permutationCode := 8942493 },
  { mask := 49682430252752408, representativeIndex := 338, representative := 5897869252272484, permutationCode := 11508770 },
  { mask := 49698441890354712, representativeIndex := 100, representative := 4769437441530129, permutationCode := 16333121 },
  { mask := 54264904733601304, representativeIndex := 324, representative := 5863460659071394, permutationCode := 11297748 },
  { mask := 54273419506208280, representativeIndex := 31, representative := 1015451974602833, permutationCode := 7802452 },
  { mask := 54273425948462616, representativeIndex := 221, representative := 5369792898472209, permutationCode := 7802452 },
  { mask := 54695556813540888, representativeIndex := 145, representative := 4957338582233249, permutationCode := 8942493 },
  { mask := 54765787053411864, representativeIndex := 70, representative := 2519149015187537, permutationCode := 16333121 },
]

def nearOrbitMasksG5B9P018 : List ℕ :=
  nearOrbitWitnessesG5B9P018.map NearOrbitWitness.mask

end SRG266.Certificates
