/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by
`scripts/generate_root_near_orbit_certificates.py`.
-/
import SRG266.Certificates.RootNearOrbitGroups
import SRG266.QuasiSymmetric.RootOrbitCertificate

namespace SRG266.Certificates

open SRG266.QuasiSymmetric

set_option maxRecDepth 100000

def nearOrbitWitnessesG5B9P028 : List NearOrbitWitness := [
  { mask := 14408243856649768, representativeIndex := 363, representative := 6855030144218129, permutationCode := 8942493 },
  { mask := 14830456321519144, representativeIndex := 370, representative := 6919967776614945, permutationCode := 2214590 },
  { mask := 15922766975278632, representativeIndex := 379, representative := 7412102746278232, permutationCode := 7664034 },
  { mask := 16070705060359720, representativeIndex := 373, representative := 6993568546395666, permutationCode := 8942493 },
  { mask := 16347782179302952, representativeIndex := 379, representative := 7412102746278232, permutationCode := 11508770 },
  { mask := 16901935788043816, representativeIndex := 162, representative := 4980399402690721, permutationCode := 5300715 },
  { mask := 16907570784968232, representativeIndex := 134, representative := 4945519803539587, permutationCode := 5300715 },
  { mask := 16908532857613864, representativeIndex := 395, representative := 13766556415374612, permutationCode := 8942493 },
  { mask := 23381853858278952, representativeIndex := 218, representative := 5332103943883096, permutationCode := 7664034 },
  { mask := 23804066323148328, representativeIndex := 216, representative := 5331075034947986, permutationCode := 14527233 },
  { mask := 23944520360635944, representativeIndex := 350, representative := 6104732610241186, permutationCode := 11297748 },
  { mask := 24226197188226600, representativeIndex := 119, representative := 4886627775788037, permutationCode := 8942493 },
  { mask := 25914608986992168, representativeIndex := 178, representative := 5027294401369172, permutationCode := 8942493 },
  { mask := 25914615429246504, representativeIndex := 394, representative := 13735976249138452, permutationCode := 8942493 },
  { mask := 27681960544022056, representativeIndex := 347, representative := 6088432136522898, permutationCode := 14527233 },
  { mask := 27744707675794984, representativeIndex := 333, representative := 5893749858550162, permutationCode := 14527233 },
  { mask := 27744715997040168, representativeIndex := 251, representative := 5472564423625048, permutationCode := 7664034 },
  { mask := 28298861284535848, representativeIndex := 246, representative := 5471537393680786, permutationCode := 14527233 },
  { mask := 28307382499397160, representativeIndex := 369, representative := 6919944289229345, permutationCode := 16333121 },
  { mask := 28720998591868456, representativeIndex := 84, representative := 4746165165404677, permutationCode := 8942493 },
  { mask := 28729519806729768, representativeIndex := 83, representative := 4746164100083973, permutationCode := 8942493 },
  { mask := 29370372342787624, representativeIndex := 265, representative := 5512178462998868, permutationCode := 11508770 },
  { mask := 29855256781893160, representativeIndex := 89, representative := 4746369245614161, permutationCode := 8942493 },
  { mask := 29855265103138344, representativeIndex := 90, representative := 4746370245925137, permutationCode := 8942493 },
  { mask := 32106530707451432, representativeIndex := 330, representative := 5877738220947858, permutationCode := 14527233 },
  { mask := 40906680244481576, representativeIndex := 292, representative := 5792746721675779, permutationCode := 11297748 },
  { mask := 40974027084901928, representativeIndex := 372, representative := 6993536364483218, permutationCode := 14527233 },
  { mask := 40974039902303784, representativeIndex := 208, representative := 5264721069203729, permutationCode := 406910 },
  { mask := 41805257812586024, representativeIndex := 313, representative := 5827654117728353, permutationCode := 11297748 },
  { mask := 41818383232251432, representativeIndex := 110, representative := 4772353522000145, permutationCode := 406910 },
  { mask := 41945718292327976, representativeIndex := 166, representative := 4980429453961761, permutationCode := 5300715 },
  { mask := 41958843711993384, representativeIndex := 108, representative := 4772346207357201, permutationCode := 406910 },
  { mask := 42876768870837800, representativeIndex := 305, representative := 5794874945079377, permutationCode := 11297748 },
  { mask := 43084576191000104, representativeIndex := 177, representative := 5023449868768402, permutationCode := 8942493 },
  { mask := 43084589008401960, representativeIndex := 105, representative := 4772140061516037, permutationCode := 406910 },
  { mask := 45261021168381480, representativeIndex := 293, representative := 5792748852317187, permutationCode := 11297748 },
  { mask := 45266656165305896, representativeIndex := 332, representative := 5881889356194148, permutationCode := 11508770 },
  { mask := 45267618237951528, representativeIndex := 315, representative := 5846979894509894, permutationCode := 11508770 },
  { mask := 45269542383242792, representativeIndex := 220, representative := 5368624682082563, permutationCode := 7802452 },
  { mask := 45274146588046888, representativeIndex := 20, representative := 832659482722385, permutationCode := 406910 },
  { mask := 45468828488543784, representativeIndex := 372, representative := 6993536364483218, permutationCode := 8942493 },
  { mask := 45477324337028648, representativeIndex := 167, representative := 4980435829109281, permutationCode := 16333121 },
  { mask := 45477349703405096, representativeIndex := 163, representative := 4980405777838241, permutationCode := 16333121 },
  { mask := 45745905607487016, representativeIndex := 382, representative := 7971826835033362, permutationCode := 14527233 },
  { mask := 45759001164619304, representativeIndex := 117, representative := 4883809832743049, permutationCode := 8942493 },
  { mask := 45759031027152424, representativeIndex := 109, representative := 4772347083939985, permutationCode := 406910 },
  { mask := 45884443820928552, representativeIndex := 18, representative := 830705474898001, permutationCode := 7664034 },
  { mask := 46306656285797928, representativeIndex := 378, representative := 7411076156722450, permutationCode := 14527233 },
  { mask := 46308580431089192, representativeIndex := 164, representative := 4980427388330081, permutationCode := 5300715 },
  { mask := 46313184635893288, representativeIndex := 107, representative := 4772345207046225, permutationCode := 406910 },
  { mask := 47447435511275048, representativeIndex := 355, representative := 6374440501348720, permutationCode := 11508770 },
  { mask := 47447438329761320, representativeIndex := 175, representative := 5023446672806290, permutationCode := 8942493 },
  { mask := 47447442825917992, representativeIndex := 106, representative := 4772141126836741, permutationCode := 406910 },
  { mask := 49698716751476264, representativeIndex := 196, representative := 5194490829332753, permutationCode := 406910 },
  { mask := 54273694367329832, representativeIndex := 344, representative := 6074150378373346, permutationCode := 11297748 },
  { mask := 54273700809584168, representativeIndex := 371, representative := 6988756316759558, permutationCode := 2214590 },
  { mask := 54414154847071784, representativeIndex := 345, representative := 6074152444005026, permutationCode := 11297748 },
  { mask := 54695831674662440, representativeIndex := 122, representative := 4887108342362273, permutationCode := 8942493 },
  { mask := 54906522394275368, representativeIndex := 72, representative := 2659884356051041, permutationCode := 16333121 },
  { mask := 55328734859144744, representativeIndex := 71, representative := 2521346142609505, permutationCode := 16333121 },
  { mask := 63615203241733672, representativeIndex := 91, representative := 4746371122507921, permutationCode := 8942493 },
]

def nearOrbitMasksG5B9P028 : List ℕ :=
  nearOrbitWitnessesG5B9P028.map NearOrbitWitness.mask

end SRG266.Certificates
