/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0068

4 frontier states of the residue-0 branch, together with
the 5 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0068. -/
def a15EnumChunk0068 : List A15MagState :=
  [⟨10, 22, 244, [(-8)], [6, 6, 6, 6, 6]⟩, ⟨9, 28, 280, [(-8)], [6, 6, 6,
   6, 6, 6]⟩, ⟨14, (-14), 100, [(-8), (-6)], []⟩, ⟨13, (-8), 136, [(-8),
   (-6)], [6]⟩]

/-- The profiles emitted below chunk 0068. -/
def a15EnumChunk0068Out : List (Array ℤ) :=
  [#[(-32), (-12), (-12), (-12), (-12), (-8), (-8), (-8), (-8), (-8),
       0, 24, 24, 24, 24, 24], #[(-32), (-12), (-12), (-12), (-12), (-12),
       (-8), (-8), (-4), (-4), (-4), 24, 24, 24, 24, 24], #[(-32), (-24),
       (-20), (-16), (-16), (-16), (-8), 12, 12, 12, 16, 16, 16, 16, 16,
       16], #[(-32), (-24), (-20), (-20), (-12), (-12), (-12), 12, 12, 12,
       16, 16, 16, 16, 16, 16], #[(-32), (-24), (-20), (-20), (-20), (-12),
       4, 4, 12, 12, 16, 16, 16, 16, 16, 16]]

theorem a15EnumChunk0068_eq :
    a15PolyExpand 0 5 a15EnumChunk0068 = a15EnumChunk0068Out := by
  decide +kernel

end SRG266
