/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0287

20 frontier states of the residue-0 branch, together with
the 3 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0287. -/
def a15EnumChunk0287 : List A15MagState :=
  [⟨13, 11, 249, [(-8)], [8, 11]⟩, ⟨12, 17, 285, [(-8)], [6, 8, 11]⟩, ⟨12,
   5, 285, [(-8), (-6)], [8, 11]⟩, ⟨12, 18, 298, [(-8)], [7, 8, 11]⟩, ⟨12,
   4, 298, [(-8), (-7)], [8, 11]⟩, ⟨13, (-5), 249, [(-8), (-8)], [11]⟩, ⟨12,
   1, 285, [(-8), (-8)], [6, 11]⟩, ⟨12, (-11), 285, [(-8), (-8), (-6)],
   [11]⟩, ⟨12, 2, 298, [(-8), (-8)], [7, 11]⟩, ⟨12, (-12), 298, [(-8), (-8),
   (-7)], [11]⟩, ⟨14, 20, 202, [], [9, 11]⟩, ⟨13, 26, 238, [], [6, 9, 11]⟩,
   ⟨12, 32, 274, [], [6, 6, 9, 11]⟩, ⟨13, 14, 238, [(-6)], [9, 11]⟩, ⟨12,
   20, 274, [(-6)], [6, 9, 11]⟩, ⟨12, 8, 274, [(-6), (-6)], [9, 11]⟩, ⟨13,
   27, 251, [], [7, 9, 11]⟩, ⟨12, 33, 287, [], [6, 7, 9, 11]⟩, ⟨12, 21, 287,
   [(-6)], [7, 9, 11]⟩, ⟨12, 34, 300, [], [7, 7, 9, 11]⟩]

/-- The profiles emitted below chunk 0287. -/
def a15EnumChunk0287Out : List (Array ℤ) :=
  [#[(-32), (-32), (-16), (-16), 0, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 44],
       #[(-32), (-32), (-20), (-4), (-4), 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 44],
       #[(-32), (-32), (-20), (-12), 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 44]]

theorem a15EnumChunk0287_eq :
    a15PolyExpand 0 5 a15EnumChunk0287 = a15EnumChunk0287Out := by
  decide +kernel

end SRG266
