/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0000

8 frontier states of the residue-0 branch, together with
the 8 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0000. -/
def a15EnumChunk0000 : List A15MagState :=
  [⟨16, 0, 0, [], []⟩, ⟨15, 6, 36, [], [6]⟩, ⟨14, 12, 72, [], [6, 6]⟩, ⟨13,
   18, 108, [], [6, 6, 6]⟩, ⟨12, 24, 144, [], [6, 6, 6, 6]⟩, ⟨11, 30, 180,
   [], [6, 6, 6, 6, 6]⟩, ⟨10, 36, 216, [], [6, 6, 6, 6, 6, 6]⟩, ⟨9, 42, 252,
   [], [6, 6, 6, 6, 6, 6, 6]⟩]

/-- The profiles emitted below chunk 0000. -/
def a15EnumChunk0000Out : List (Array ℤ) :=
  [#[(-20), (-20), (-20), (-20), (-20), (-20), 0, 0, 0, 0, 20, 20, 20,
       20, 20, 20], #[(-16), (-16), (-16), (-16), (-16), (-16), (-12),
       (-12), (-12), 4, 16, 16, 24, 24, 24, 24], #[(-16), (-16), (-16),
       (-16), (-16), (-16), (-12), (-12), (-12), 8, 8, 20, 24, 24, 24, 24],
       #[(-20), (-20), (-20), (-20), (-20), (-12), (-8), 0, 0, 0, 12, 12,
       24, 24, 24, 24], #[(-16), (-16), (-16), (-12), (-12), (-12), (-12),
       (-12), (-12), (-12), 12, 24, 24, 24, 24, 24], #[(-16), (-16), (-16),
       (-16), (-16), (-12), (-12), (-12), (-12), 0, 8, 24, 24, 24, 24, 24],
       #[(-20), (-16), (-16), (-16), (-12), (-12), (-12), (-12), (-12), 4,
       4, 24, 24, 24, 24, 24], #[(-20), (-20), (-16), (-12), (-12), (-12),
       (-12), (-12), (-8), (-4), 8, 24, 24, 24, 24, 24]]

theorem a15EnumChunk0000_eq :
    a15PolyExpand 0 5 a15EnumChunk0000 = a15EnumChunk0000Out := by
  decide +kernel

end SRG266
