/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0308

6 frontier states of the residue-0 branch, together with
the 3 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0308. -/
def a15EnumChunk0308 : List A15MagState :=
  [⟨13, 5, 249, [(-11)], [8, 8]⟩, ⟨12, 11, 285, [(-11)], [6, 8, 8]⟩, ⟨12,
   (-1), 285, [(-11), (-6)], [8, 8]⟩, ⟨12, 12, 298, [(-11)], [7, 8, 8]⟩,
   ⟨12, (-2), 298, [(-11), (-7)], [8, 8]⟩, ⟨14, (-19), 185, [(-11), (-8)],
   []⟩]

/-- The profiles emitted below chunk 0308. -/
def a15EnumChunk0308Out : List (Array ℤ) :=
  [#[(-44), (-8), (-8), (-8), (-4), (-4), (-4), (-4), (-4), (-4), (-4),
       0, 16, 16, 32, 32], #[(-44), (-8), (-8), (-8), (-8), (-8), (-8), 0,
       0, 0, 0, 4, 4, 20, 32, 32], #[(-44), (-8), (-8), (-4), (-4), (-4),
       (-4), (-4), (-4), (-4), (-4), (-4), 12, 20, 32, 32]]

theorem a15EnumChunk0308_eq :
    a15PolyExpand 0 5 a15EnumChunk0308 = a15EnumChunk0308Out := by
  decide +kernel

end SRG266
