/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0271

1 frontier states of the residue-0 branch, together with
the 3 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0271. -/
def a15EnumChunk0271 : List A15MagState :=
  [⟨14, 5, 157, [(-6)], [11]⟩]

/-- The profiles emitted below chunk 0271. -/
def a15EnumChunk0271Out : List (Array ℤ) :=
  [#[(-24), (-12), (-12), (-12), (-12), (-12), (-12), (-12), (-12), 4,
       8, 12, 16, 16, 20, 44], #[(-24), (-12), (-12), (-12), (-12), (-12),
       (-12), (-12), (-12), 8, 8, 8, 12, 20, 20, 44], #[(-24), (-20), (-20),
       (-8), (-8), (-8), (-8), (-8), (-8), 4, 4, 4, 16, 20, 20, 44]]

theorem a15EnumChunk0271_eq :
    a15PolyExpand 0 5 a15EnumChunk0271 = a15EnumChunk0271Out := by
  decide +kernel

end SRG266
