/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0494

13 frontier states of the residue-2 branch, together with
the 3 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0494. -/
def a15EnumChunk0494 : List A15MagState :=
  [⟨11, (-17), 253, [(-8), (-6), (-6), (-6)], [9]⟩, ⟨10, (-11), 289, [(-8),
   (-6), (-6), (-6)], [6, 9]⟩, ⟨10, (-23), 289, [(-8), (-6), (-6), (-6),
   (-6)], [9]⟩, ⟨13, 8, 194, [(-8)], [7, 9]⟩, ⟨12, 14, 230, [(-8)], [6, 7,
   9]⟩, ⟨11, 20, 266, [(-8)], [6, 6, 7, 9]⟩, ⟨10, 26, 302, [(-8)], [6, 6, 6,
   7, 9]⟩, ⟨12, 2, 230, [(-8), (-6)], [7, 9]⟩, ⟨11, 8, 266, [(-8), (-6)],
   [6, 7, 9]⟩, ⟨10, 14, 302, [(-8), (-6)], [6, 6, 7, 9]⟩, ⟨11, (-4), 266,
   [(-8), (-6), (-6)], [7, 9]⟩, ⟨10, 2, 302, [(-8), (-6), (-6)], [6, 7, 9]⟩,
   ⟨10, (-10), 302, [(-8), (-6), (-6), (-6)], [7, 9]⟩]

/-- The profiles emitted below chunk 0494. -/
def a15EnumChunk0494Out : List (Array ℤ) :=
  [#[(-30), (-10), (-10), (-10), (-10), (-10), (-10), (-10), (-10),
       (-6), 2, 14, 14, 18, 30, 38], #[(-30), (-10), (-10), (-10), (-10),
       (-10), (-10), (-10), (-10), (-6), 6, 10, 10, 22, 30, 38], #[(-30),
       (-10), (-10), (-10), (-10), (-10), (-10), (-10), (-10), 2, 2, 6, 6,
       26, 30, 38]]

theorem a15EnumChunk0494_eq :
    a15PolyExpand 2 5 a15EnumChunk0494 = a15EnumChunk0494Out := by
  decide +kernel

end SRG266
