/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0687

4 frontier states of the residue-2 branch, together with
the 1 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0687. -/
def a15EnumChunk0687 : List A15MagState :=
  [⟨14, 5, 193, [(-7)], [12]⟩, ⟨13, 11, 229, [(-7)], [6, 12]⟩, ⟨12, 17,
   265, [(-7)], [6, 6, 12]⟩, ⟨11, 23, 301, [(-7)], [6, 6, 6, 12]⟩]

/-- The profiles emitted below chunk 0687. -/
def a15EnumChunk0687Out : List (Array ℤ) :=
  [#[(-26), (-18), (-14), (-10), (-10), (-10), (-10), (-10), (-2), 10,
       10, 10, 10, 10, 10, 50]]

theorem a15EnumChunk0687_eq :
    a15PolyExpand 2 5 a15EnumChunk0687 = a15EnumChunk0687Out := by
  decide +kernel

end SRG266
