/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0184

14 frontier states of the residue-0 branch, together with
the 6 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0184. -/
def a15EnumChunk0184 : List A15MagState :=
  [⟨13, (-25), 209, [(-9), (-8), (-8)], []⟩, ⟨12, (-19), 245, [(-9), (-8),
   (-8)], [6]⟩, ⟨11, (-13), 281, [(-9), (-8), (-8)], [6, 6]⟩, ⟨12, (-31),
   245, [(-9), (-8), (-8), (-6)], []⟩, ⟨11, (-25), 281, [(-9), (-8), (-8),
   (-6)], [6]⟩, ⟨11, (-37), 281, [(-9), (-8), (-8), (-6), (-6)], []⟩, ⟨12,
   (-18), 258, [(-9), (-8), (-8)], [7]⟩, ⟨11, (-12), 294, [(-9), (-8),
   (-8)], [6, 7]⟩, ⟨11, (-24), 294, [(-9), (-8), (-8), (-6)], [7]⟩, ⟨12,
   (-32), 258, [(-9), (-8), (-8), (-7)], []⟩, ⟨11, (-26), 294, [(-9), (-8),
   (-8), (-7)], [6]⟩, ⟨11, (-38), 294, [(-9), (-8), (-8), (-7), (-6)], []⟩,
   ⟨12, (-17), 273, [(-9), (-8), (-8)], [8]⟩, ⟨12, (-33), 273, [(-9), (-8),
   (-8), (-8)], []⟩]

/-- The profiles emitted below chunk 0184. -/
def a15EnumChunk0184Out : List (Array ℤ) :=
  [#[(-36), (-32), (-32), 0, 0, 4, 4, 4, 4, 4, 4, 4, 16, 16, 16, 24],
       #[(-36), (-32), (-32), 0, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 24, 24],
       #[(-36), (-32), (-32), 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 12, 24, 24],
       #[(-36), (-32), (-32), 0, 4, 4, 4, 4, 4, 4, 4, 4, 12, 12, 16, 28],
       #[(-36), (-32), (-32), 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 16, 16, 28],
       #[(-36), (-32), (-32), 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 20, 28]]

theorem a15EnumChunk0184_eq :
    a15PolyExpand 0 5 a15EnumChunk0184 = a15EnumChunk0184Out := by
  decide +kernel

end SRG266
