/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0387

2 frontier states of the residue-2 branch, together with
the 1 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0387. -/
def a15EnumChunk0387 : List A15MagState :=
  [⟨13, (-20), 134, [(-7), (-7), (-6)], []⟩, ⟨12, (-14), 170, [(-7), (-7),
   (-6)], [6]⟩]

/-- The profiles emitted below chunk 0387. -/
def a15EnumChunk0387Out : List (Array ℤ) :=
  [#[(-26), (-26), (-22), (-18), (-18), (-14), (-10), 14, 14, 14, 14,
       14, 14, 14, 18, 18]]

theorem a15EnumChunk0387_eq :
    a15PolyExpand 2 5 a15EnumChunk0387 = a15EnumChunk0387Out := by
  decide +kernel

end SRG266
