/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0642

12 frontier states of the residue-2 branch, together with
the 0 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0642. -/
def a15EnumChunk0642 : List A15MagState :=
  [⟨13, (-3), 219, [(-7), (-7)], [11]⟩, ⟨12, 3, 255, [(-7), (-7)], [6,
   11]⟩, ⟨11, 9, 291, [(-7), (-7)], [6, 6, 11]⟩, ⟨12, (-9), 255, [(-7),
   (-7), (-6)], [11]⟩, ⟨11, (-3), 291, [(-7), (-7), (-6)], [6, 11]⟩, ⟨11,
   (-15), 291, [(-7), (-7), (-6), (-6)], [11]⟩, ⟨12, 4, 268, [(-7), (-7)],
   [7, 11]⟩, ⟨11, 10, 304, [(-7), (-7)], [6, 7, 11]⟩, ⟨11, (-2), 304, [(-7),
   (-7), (-6)], [7, 11]⟩, ⟨12, (-10), 268, [(-7), (-7), (-7)], [11]⟩, ⟨11,
   (-4), 304, [(-7), (-7), (-7)], [6, 11]⟩, ⟨11, (-16), 304, [(-7), (-7),
   (-7), (-6)], [11]⟩]

/-- The profiles emitted below chunk 0642. -/
def a15EnumChunk0642Out : List (Array ℤ) :=
  []

theorem a15EnumChunk0642_eq :
    a15PolyExpand 2 5 a15EnumChunk0642 = a15EnumChunk0642Out := by
  decide +kernel

end SRG266
