/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0662

1 frontier states of the residue-2 branch, together with
the 1 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0662. -/
def a15EnumChunk0662 : List A15MagState :=
  [⟨14, (-18), 170, [(-11), (-7)], []⟩]

/-- The profiles emitted below chunk 0662. -/
def a15EnumChunk0662Out : List (Array ℤ) :=
  [#[(-42), (-26), (-6), (-6), (-6), (-6), (-6), (-6), (-6), 6, 6, 10,
       22, 22, 22, 22]]

theorem a15EnumChunk0662_eq :
    a15PolyExpand 2 5 a15EnumChunk0662 = a15EnumChunk0662Out := by
  decide +kernel

end SRG266
