/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0045

10 frontier states of the residue-0 branch, together with
the 0 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0045. -/
def a15EnumChunk0045 : List A15MagState :=
  [⟨11, 9, 221, [(-6), (-6)], [6, 7, 8]⟩, ⟨10, 15, 257, [(-6), (-6)], [6,
   6, 7, 8]⟩, ⟨9, 21, 293, [(-6), (-6)], [6, 6, 6, 7, 8]⟩, ⟨11, (-3), 221,
   [(-6), (-6), (-6)], [7, 8]⟩, ⟨10, 3, 257, [(-6), (-6), (-6)], [6, 7, 8]⟩,
   ⟨9, 9, 293, [(-6), (-6), (-6)], [6, 6, 7, 8]⟩, ⟨10, (-9), 257, [(-6),
   (-6), (-6), (-6)], [7, 8]⟩, ⟨9, (-3), 293, [(-6), (-6), (-6), (-6)], [6,
   7, 8]⟩, ⟨9, (-15), 293, [(-6), (-6), (-6), (-6), (-6)], [7, 8]⟩, ⟨13, 22,
   162, [], [7, 7, 8]⟩]

/-- The profiles emitted below chunk 0045. -/
def a15EnumChunk0045Out : List (Array ℤ) :=
  []

theorem a15EnumChunk0045_eq :
    a15PolyExpand 0 5 a15EnumChunk0045 = a15EnumChunk0045Out := by
  decide +kernel

end SRG266
