/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0436

4 frontier states of the residue-2 branch, together with
the 1 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0436. -/
def a15EnumChunk0436 : List A15MagState :=
  [⟨12, (-15), 185, [(-8), (-7), (-6)], [6]⟩, ⟨11, (-9), 221, [(-8), (-7),
   (-6)], [6, 6]⟩, ⟨10, (-3), 257, [(-8), (-7), (-6)], [6, 6, 6]⟩, ⟨9, 3,
   293, [(-8), (-7), (-6)], [6, 6, 6, 6]⟩]

/-- The profiles emitted below chunk 0436. -/
def a15EnumChunk0436Out : List (Array ℤ) :=
  [#[(-30), (-26), (-22), (-18), (-10), (-2), (-2), (-2), (-2), (-2),
       18, 18, 18, 18, 18, 26]]

theorem a15EnumChunk0436_eq :
    a15PolyExpand 2 5 a15EnumChunk0436 = a15EnumChunk0436Out := by
  decide +kernel

end SRG266
