/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0282

7 frontier states of the residue-0 branch, together with
the 0 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0282. -/
def a15EnumChunk0282 : List A15MagState :=
  [⟨14, 19, 185, [], [8, 11]⟩, ⟨13, 25, 221, [], [6, 8, 11]⟩, ⟨12, 31, 257,
   [], [6, 6, 8, 11]⟩, ⟨11, 37, 293, [], [6, 6, 6, 8, 11]⟩, ⟨13, 13, 221,
   [(-6)], [8, 11]⟩, ⟨12, 19, 257, [(-6)], [6, 8, 11]⟩, ⟨11, 25, 293,
   [(-6)], [6, 6, 8, 11]⟩]

/-- The profiles emitted below chunk 0282. -/
def a15EnumChunk0282Out : List (Array ℤ) :=
  []

theorem a15EnumChunk0282_eq :
    a15PolyExpand 0 5 a15EnumChunk0282 = a15EnumChunk0282Out := by
  decide +kernel

end SRG266
