/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0581

1 frontier states of the residue-2 branch, together with
the 6 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0581. -/
def a15EnumChunk0581 : List A15MagState :=
  [⟨14, 1, 181, [(-9)], [10]⟩]

/-- The profiles emitted below chunk 0581. -/
def a15EnumChunk0581Out : List (Array ℤ) :=
  [#[(-34), (-10), (-10), (-10), (-10), (-10), (-10), (-10), (-6),
       (-6), 14, 14, 14, 14, 18, 42], #[(-34), (-14), (-14), (-14), (-6),
       (-6), (-6), (-6), (-6), (-6), 10, 10, 14, 14, 22, 42], #[(-34),
       (-14), (-14), (-14), (-14), (-14), 2, 2, 2, 2, 2, 2, 14, 14, 22, 42],
       #[(-34), (-18), (-10), (-10), (-10), (-10), (-10), (-6), (-6), 2, 14,
       14, 14, 14, 14, 42], #[(-34), (-18), (-18), (-14), (-14), (-14), 6,
       6, 6, 6, 6, 6, 6, 14, 14, 42], #[(-34), (-18), (-18), (-14), (-14),
       (-10), 2, 6, 6, 6, 6, 6, 6, 6, 22, 42]]

theorem a15EnumChunk0581_eq :
    a15PolyExpand 2 5 a15EnumChunk0581 = a15EnumChunk0581Out := by
  decide +kernel

end SRG266
