/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0454

21 frontier states of the residue-2 branch, together with
the 2 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0454. -/
def a15EnumChunk0454 : List A15MagState :=
  [⟨12, 14, 228, [(-8)], [6, 8, 8]⟩, ⟨11, 20, 264, [(-8)], [6, 6, 8, 8]⟩,
   ⟨10, 26, 300, [(-8)], [6, 6, 6, 8, 8]⟩, ⟨12, 2, 228, [(-8), (-6)], [8,
   8]⟩, ⟨11, 8, 264, [(-8), (-6)], [6, 8, 8]⟩, ⟨10, 14, 300, [(-8), (-6)],
   [6, 6, 8, 8]⟩, ⟨11, (-4), 264, [(-8), (-6), (-6)], [8, 8]⟩, ⟨10, 2, 300,
   [(-8), (-6), (-6)], [6, 8, 8]⟩, ⟨10, (-10), 300, [(-8), (-6), (-6),
   (-6)], [8, 8]⟩, ⟨12, 15, 241, [(-8)], [7, 8, 8]⟩, ⟨11, 21, 277, [(-8)],
   [6, 7, 8, 8]⟩, ⟨11, 9, 277, [(-8), (-6)], [7, 8, 8]⟩, ⟨11, 22, 290,
   [(-8)], [7, 7, 8, 8]⟩, ⟨12, 1, 241, [(-8), (-7)], [8, 8]⟩, ⟨11, 7, 277,
   [(-8), (-7)], [6, 8, 8]⟩, ⟨11, (-5), 277, [(-8), (-7), (-6)], [8, 8]⟩,
   ⟨11, 8, 290, [(-8), (-7)], [7, 8, 8]⟩, ⟨11, (-6), 290, [(-8), (-7),
   (-7)], [8, 8]⟩, ⟨12, 16, 256, [(-8)], [8, 8, 8]⟩, ⟨11, 22, 292, [(-8)],
   [6, 8, 8, 8]⟩, ⟨11, 10, 292, [(-8), (-6)], [8, 8, 8]⟩]

/-- The profiles emitted below chunk 0454. -/
def a15EnumChunk0454Out : List (Array ℤ) :=
  [#[(-30), (-10), (-10), (-10), (-10), (-10), (-10), (-10), (-10), 2,
       2, 2, 10, 26, 34, 34], #[(-30), (-14), (-14), (-14), (-6), (-6),
       (-2), (-2), (-2), (-2), (-2), (-2), (-2), 30, 34, 34]]

theorem a15EnumChunk0454_eq :
    a15PolyExpand 2 5 a15EnumChunk0454 = a15EnumChunk0454Out := by
  decide +kernel

end SRG266
