/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0125

12 frontier states of the residue-0 branch, together with
the 1 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0125. -/
def a15EnumChunk0125 : List A15MagState :=
  [⟨12, 15, 215, [(-7)], [6, 7, 9]⟩, ⟨11, 21, 251, [(-7)], [6, 6, 7, 9]⟩,
   ⟨10, 27, 287, [(-7)], [6, 6, 6, 7, 9]⟩, ⟨12, 3, 215, [(-7), (-6)], [7,
   9]⟩, ⟨11, 9, 251, [(-7), (-6)], [6, 7, 9]⟩, ⟨10, 15, 287, [(-7), (-6)],
   [6, 6, 7, 9]⟩, ⟨11, (-3), 251, [(-7), (-6), (-6)], [7, 9]⟩, ⟨10, 3, 287,
   [(-7), (-6), (-6)], [6, 7, 9]⟩, ⟨10, (-9), 287, [(-7), (-6), (-6), (-6)],
   [7, 9]⟩, ⟨12, 16, 228, [(-7)], [7, 7, 9]⟩, ⟨11, 22, 264, [(-7)], [6, 7,
   7, 9]⟩, ⟨10, 28, 300, [(-7)], [6, 6, 7, 7, 9]⟩]

/-- The profiles emitted below chunk 0125. -/
def a15EnumChunk0125Out : List (Array ℤ) :=
  [#[(-28), (-24), (-24), (-4), (-4), (-4), (-4), (-4), (-4), (-4),
       (-4), 12, 16, 16, 28, 36]]

theorem a15EnumChunk0125_eq :
    a15PolyExpand 0 5 a15EnumChunk0125 = a15EnumChunk0125Out := by
  decide +kernel

end SRG266
