/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0022

4 frontier states of the residue-0 branch, together with
the 0 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0022. -/
def a15EnumChunk0022 : List A15MagState :=
  [⟨12, 0, 170, [(-7), (-6)], [6, 7]⟩, ⟨11, 6, 206, [(-7), (-6)], [6, 6,
   7]⟩, ⟨10, 12, 242, [(-7), (-6)], [6, 6, 6, 7]⟩, ⟨9, 18, 278, [(-7),
   (-6)], [6, 6, 6, 6, 7]⟩]

/-- The profiles emitted below chunk 0022. -/
def a15EnumChunk0022Out : List (Array ℤ) :=
  []

theorem a15EnumChunk0022_eq :
    a15PolyExpand 0 5 a15EnumChunk0022 = a15EnumChunk0022Out := by
  decide +kernel

end SRG266
