/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0334

5 frontier states of the residue-0 branch, together with
the 9 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0334. -/
def a15EnumChunk0334 : List A15MagState :=
  [⟨13, 1, 229, [(-12)], [6, 7]⟩, ⟨12, 7, 265, [(-12)], [6, 6, 7]⟩, ⟨13,
   (-11), 229, [(-12), (-6)], [7]⟩, ⟨12, (-5), 265, [(-12), (-6)], [6, 7]⟩,
   ⟨12, (-17), 265, [(-12), (-6), (-6)], [7]⟩]

/-- The profiles emitted below chunk 0334. -/
def a15EnumChunk0334Out : List (Array ℤ) :=
  [#[(-48), (-12), (-8), (-4), (-4), (-4), (-4), (-4), (-4), (-4),
       (-4), 12, 16, 20, 24, 28], #[(-48), (-20), (-8), (-4), (-4), (-4),
       (-4), (-4), (-4), 0, 12, 12, 12, 12, 24, 28], #[(-48), (-20), (-4),
       (-4), (-4), (-4), (-4), (-4), (-4), (-4), 8, 12, 12, 16, 24, 28],
       #[(-48), (-20), (-20), (-4), 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 24, 28],
       #[(-48), (-20), (-20), (-8), 0, 4, 4, 4, 4, 4, 4, 4, 4, 12, 24, 28],
       #[(-48), (-12), (-8), (-8), (-8), (-8), (-8), 4, 4, 4, 4, 4, 4, 24,
       24, 28], #[(-48), (-12), (-4), (-4), (-4), (-4), (-4), (-4), (-4),
       (-4), (-4), 4, 16, 24, 24, 28], #[(-48), (-16), (-4), (-4), (-4),
       (-4), (-4), (-4), (-4), (-4), 4, 4, 12, 24, 24, 28], #[(-48), (-24),
       (-20), 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 24, 28]]

theorem a15EnumChunk0334_eq :
    a15PolyExpand 0 5 a15EnumChunk0334 = a15EnumChunk0334Out := by
  decide +kernel

end SRG266
