/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0432

12 frontier states of the residue-2 branch, together with
the 3 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0432. -/
def a15EnumChunk0432 : List A15MagState :=
  [⟨11, (-6), 234, [(-8), (-6), (-6)], [7, 7]⟩, ⟨10, 0, 270, [(-8), (-6),
   (-6)], [6, 7, 7]⟩, ⟨10, (-12), 270, [(-8), (-6), (-6), (-6)], [7, 7]⟩,
   ⟨12, 13, 211, [(-8)], [7, 7, 7]⟩, ⟨11, 19, 247, [(-8)], [6, 7, 7, 7]⟩,
   ⟨10, 25, 283, [(-8)], [6, 6, 7, 7, 7]⟩, ⟨11, 7, 247, [(-8), (-6)], [7, 7,
   7]⟩, ⟨10, 13, 283, [(-8), (-6)], [6, 7, 7, 7]⟩, ⟨10, 1, 283, [(-8), (-6),
   (-6)], [7, 7, 7]⟩, ⟨11, 20, 260, [(-8)], [7, 7, 7, 7]⟩, ⟨10, 26, 296,
   [(-8)], [6, 7, 7, 7, 7]⟩, ⟨10, 14, 296, [(-8), (-6)], [7, 7, 7, 7]⟩]

/-- The profiles emitted below chunk 0432. -/
def a15EnumChunk0432Out : List (Array ℤ) :=
  [#[(-30), (-22), (-22), (-18), (-10), 2, 2, 2, 2, 2, 2, 2, 2, 26, 30,
       30], #[(-30), (-10), (-10), (-10), (-10), (-10), (-10), (-10), (-10),
       (-10), 10, 10, 10, 30, 30, 30], #[(-30), (-14), (-14), (-14), (-14),
       (-14), (-2), (-2), (-2), (-2), 2, 2, 14, 30, 30, 30]]

theorem a15EnumChunk0432_eq :
    a15PolyExpand 2 5 a15EnumChunk0432 = a15EnumChunk0432Out := by
  decide +kernel

end SRG266
