/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0521

6 frontier states of the residue-2 branch, together with
the 1 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0521. -/
def a15EnumChunk0521 : List A15MagState :=
  [⟨12, (-3), 215, [(-9), (-7)], [6, 7]⟩, ⟨11, 3, 251, [(-9), (-7)], [6, 6,
   7]⟩, ⟨10, 9, 287, [(-9), (-7)], [6, 6, 6, 7]⟩, ⟨12, (-15), 215, [(-9),
   (-7), (-6)], [7]⟩, ⟨11, (-9), 251, [(-9), (-7), (-6)], [6, 7]⟩, ⟨10,
   (-3), 287, [(-9), (-7), (-6)], [6, 6, 7]⟩]

/-- The profiles emitted below chunk 0521. -/
def a15EnumChunk0521Out : List (Array ℤ) :=
  [#[(-34), (-26), (-22), (-14), (-14), (-14), 10, 10, 10, 10, 10, 10,
       10, 10, 14, 30]]

theorem a15EnumChunk0521_eq :
    a15PolyExpand 2 5 a15EnumChunk0521 = a15EnumChunk0521Out := by
  decide +kernel

end SRG266
