/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0664

6 frontier states of the residue-2 branch, together with
the 0 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0664. -/
def a15EnumChunk0664 : List A15MagState :=
  [⟨13, (-24), 206, [(-11), (-7), (-6)], []⟩, ⟨12, (-18), 242, [(-11),
   (-7), (-6)], [6]⟩, ⟨11, (-12), 278, [(-11), (-7), (-6)], [6, 6]⟩, ⟨12,
   (-30), 242, [(-11), (-7), (-6), (-6)], []⟩, ⟨11, (-24), 278, [(-11),
   (-7), (-6), (-6)], [6]⟩, ⟨11, (-36), 278, [(-11), (-7), (-6), (-6),
   (-6)], []⟩]

/-- The profiles emitted below chunk 0664. -/
def a15EnumChunk0664Out : List (Array ℤ) :=
  []

theorem a15EnumChunk0664_eq :
    a15PolyExpand 2 5 a15EnumChunk0664 = a15EnumChunk0664Out := by
  decide +kernel

end SRG266
