/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0668

4 frontier states of the residue-2 branch, together with
the 12 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0668. -/
def a15EnumChunk0668 : List A15MagState :=
  [⟨13, 3, 221, [(-11)], [6, 8]⟩, ⟨12, 9, 257, [(-11)], [6, 6, 8]⟩, ⟨11,
   15, 293, [(-11)], [6, 6, 6, 8]⟩, ⟨13, (-9), 221, [(-11), (-6)], [8]⟩]

/-- The profiles emitted below chunk 0668. -/
def a15EnumChunk0668Out : List (Array ℤ) :=
  [#[(-42), (-14), (-6), (-6), (-6), (-6), (-6), (-6), (-6), (-6),
       (-2), 14, 14, 18, 26, 34], #[(-42), (-10), (-6), (-6), (-6), (-6),
       (-6), (-6), (-6), (-6), (-6), 10, 14, 22, 26, 34], #[(-42), (-10),
       (-10), (-10), (-10), (-10), (-10), 2, 2, 2, 2, 2, 10, 22, 26, 34],
       #[(-42), (-6), (-6), (-6), (-6), (-6), (-6), (-6), (-6), (-6), (-2),
       (-2), 14, 26, 26, 34], #[(-42), (-10), (-6), (-6), (-6), (-6), (-6),
       (-6), (-6), (-6), (-2), 6, 10, 26, 26, 34], #[(-42), (-14), (-6),
       (-6), (-6), (-6), (-6), (-6), (-6), (-2), 2, 6, 6, 26, 26, 34],
       #[(-42), (-22), (-6), (-6), (-6), (-6), (-6), (-6), (-6), (-2), 10,
       14, 14, 18, 18, 34], #[(-42), (-22), (-14), (-14), (-2), (-2), (-2),
       (-2), (-2), (-2), 14, 14, 14, 14, 14, 34], #[(-42), (-22), (-14),
       (-14), (-10), (-10), 6, 6, 6, 6, 6, 6, 14, 14, 14, 34], #[(-42),
       (-22), (-10), (-10), (-10), (-10), 2, 2, 2, 2, 2, 10, 14, 14, 22,
       34], #[(-42), (-22), (-14), (-14), (-2), 2, 2, 2, 2, 2, 2, 2, 2, 22,
       22, 34], #[(-42), (-22), (-18), (-6), (-6), 2, 2, 2, 2, 2, 2, 2, 2,
       22, 22, 34]]

theorem a15EnumChunk0668_eq :
    a15PolyExpand 2 5 a15EnumChunk0668 = a15EnumChunk0668Out := by
  decide +kernel

end SRG266
