/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0126

5 frontier states of the residue-0 branch, together with
the 4 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0126. -/
def a15EnumChunk0126 : List A15MagState :=
  [⟨11, 10, 264, [(-7), (-6)], [7, 7, 9]⟩, ⟨10, 16, 300, [(-7), (-6)], [6,
   7, 7, 9]⟩, ⟨10, 4, 300, [(-7), (-6), (-6)], [7, 7, 9]⟩, ⟨11, 23, 277,
   [(-7)], [7, 7, 7, 9]⟩, ⟨13, (-5), 179, [(-7), (-7)], [9]⟩]

/-- The profiles emitted below chunk 0126. -/
def a15EnumChunk0126Out : List (Array ℤ) :=
  [#[(-28), (-28), (-16), (-8), (-8), (-8), (-8), (-8), (-8), 4, 16,
       16, 16, 16, 16, 36], #[(-28), (-28), (-20), (-20), (-16), 4, 4, 4, 4,
       4, 4, 4, 16, 16, 16, 36], #[(-28), (-28), (-20), (-20), (-20), 0, 8,
       8, 8, 8, 8, 8, 8, 12, 12, 36], #[(-28), (-28), (-20), (-20), (-20),
       4, 4, 8, 8, 8, 8, 8, 8, 8, 16, 36]]

theorem a15EnumChunk0126_eq :
    a15PolyExpand 0 5 a15EnumChunk0126 = a15EnumChunk0126Out := by
  decide +kernel

end SRG266
