/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SRG266 formalization contributors

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0405

2 frontier states of the residue-2 branch, together with
the 2 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0405. -/
def a15EnumChunk0405 : List A15MagState :=
  [⟨14, 1, 113, [(-7)], [8]⟩, ⟨13, 7, 149, [(-7)], [6, 8]⟩]

/-- The profiles emitted below chunk 0405. -/
def a15EnumChunk0405Out : List (Array ℤ) :=
  [#[(-26), (-14), (-14), (-14), (-10), (-10), (-10), (-10), (-10),
       (-10), 18, 18, 18, 18, 22, 34], #[(-26), (-18), (-18), (-18), (-18),
       (-14), 2, 2, 2, 2, 2, 2, 22, 22, 22, 34]]

theorem a15EnumChunk0405_eq :
    a15PolyExpand 2 5 a15EnumChunk0405 = a15EnumChunk0405Out := by
  decide +kernel

end SRG266
