/-
Copyright (c) 2026 Kay Akiyama.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kay Akiyama

This file is generated by `scripts/generate_a15_enumeration_chunks.py`.
Do not edit it by hand.
-/
import SRG266.Hosts.A15EnumerationFrontier

/-!
# Bounded A15 enumeration chunk 0239

2 frontier states of the residue-0 branch, together with
the 0 canonical profiles their subtrees emit.
-/

namespace SRG266

set_option maxRecDepth 4000000
set_option maxHeartbeats 0

/-- Frontier states of chunk 0239. -/
def a15EnumChunk0239 : List A15MagState :=
  [⟨13, (-9), 185, [(-10), (-6)], [7]⟩, ⟨12, (-3), 221, [(-10), (-6)], [6,
   7]⟩]

/-- The profiles emitted below chunk 0239. -/
def a15EnumChunk0239Out : List (Array ℤ) :=
  []

theorem a15EnumChunk0239_eq :
    a15PolyExpand 0 5 a15EnumChunk0239 = a15EnumChunk0239Out := by
  decide +kernel

end SRG266
