/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Checks.A5FingerprintEq
import SRG266.Certificates.ADERootOrbits.Checks.A5FingerprintInjective
import SRG266.Certificates.ADERootOrbits.Checks.A5Norm
import SRG266.Certificates.ADERootOrbits.Checks.A5SimpleNeg
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection0Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection0Image
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection1Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection1Image
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection2Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection2Image
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection3Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection3Image
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection4Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A5Reflection4Image

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

noncomputable def certA5 : ADERootOrbitCertificate (ADEType.A 5) where
  rootCount := 30
  root := certA5Roots
  fingerprint := certA5Fingerprint
  fingerprint_eq := certA5FingerprintEq
  fingerprint_injective := certA5FingerprintInjective
  coordinate_bound := certA5CoordinateBound
  norm_two := certA5Norm
  simpleIndex := certA5Simple
  simple_eq := certA5SimpleCheck
  negIndex := certA5Neg
  neg_eq := certA5NegCheck
  reflectionIndex := certA5Reflect
  reflectionPairing := certA5ReflectPairing
  reflectionPairing_eq := by
    intro i a
    fin_cases i
    · exact certA5Reflection0Pairing a
    · exact certA5Reflection1Pairing a
    · exact certA5Reflection2Pairing a
    · exact certA5Reflection3Pairing a
    · exact certA5Reflection4Pairing a
  reflection_fingerprint := by
    intro i a
    fin_cases i
    · exact certA5Reflection0Fingerprint a
    · exact certA5Reflection1Fingerprint a
    · exact certA5Reflection2Fingerprint a
    · exact certA5Reflection3Fingerprint a
    · exact certA5Reflection4Fingerprint a
  reflection_changedCoordinate_bound := by
    intro i a
    fin_cases i
    · exact certA5Reflection0ChangedBound a
    · exact certA5Reflection1ChangedBound a
    · exact certA5Reflection2ChangedBound a
    · exact certA5Reflection3ChangedBound a
    · exact certA5Reflection4ChangedBound a
  rootCount_eq_rank_mul_coxeter := by decide +kernel
end ADERootOrbitData
end Lattice
end SRG266
