/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Checks.A9FingerprintEq
import SRG266.Certificates.ADERootOrbits.Checks.A9FingerprintInjective
import SRG266.Certificates.ADERootOrbits.Checks.A9Norm
import SRG266.Certificates.ADERootOrbits.Checks.A9SimpleNeg
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection0Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection0Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection1Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection1Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection2Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection2Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection3Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection3Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection4Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection4Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection5Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection5Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection6Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection6Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection7Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection7Image
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection8Pairing
import SRG266.Certificates.ADERootOrbits.Checks.A9Reflection8Image

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

noncomputable def certA9 : ADERootOrbitCertificate (ADEType.A 9) where
  rootCount := 90
  root := certA9Roots
  fingerprint := certA9Fingerprint
  fingerprint_eq := certA9FingerprintEq
  fingerprint_injective := certA9FingerprintInjective
  coordinate_bound := certA9CoordinateBound
  norm_two := certA9Norm
  simpleIndex := certA9Simple
  simple_eq := certA9SimpleCheck
  negIndex := certA9Neg
  neg_eq := certA9NegCheck
  reflectionIndex := certA9Reflect
  reflectionPairing := certA9ReflectPairing
  reflectionPairing_eq := by
    intro i a
    fin_cases i
    · exact certA9Reflection0Pairing a
    · exact certA9Reflection1Pairing a
    · exact certA9Reflection2Pairing a
    · exact certA9Reflection3Pairing a
    · exact certA9Reflection4Pairing a
    · exact certA9Reflection5Pairing a
    · exact certA9Reflection6Pairing a
    · exact certA9Reflection7Pairing a
    · exact certA9Reflection8Pairing a
  reflection_fingerprint := by
    intro i a
    fin_cases i
    · exact certA9Reflection0Fingerprint a
    · exact certA9Reflection1Fingerprint a
    · exact certA9Reflection2Fingerprint a
    · exact certA9Reflection3Fingerprint a
    · exact certA9Reflection4Fingerprint a
    · exact certA9Reflection5Fingerprint a
    · exact certA9Reflection6Fingerprint a
    · exact certA9Reflection7Fingerprint a
    · exact certA9Reflection8Fingerprint a
  reflection_changedCoordinate_bound := by
    intro i a
    fin_cases i
    · exact certA9Reflection0ChangedBound a
    · exact certA9Reflection1ChangedBound a
    · exact certA9Reflection2ChangedBound a
    · exact certA9Reflection3ChangedBound a
    · exact certA9Reflection4ChangedBound a
    · exact certA9Reflection5ChangedBound a
    · exact certA9Reflection6ChangedBound a
    · exact certA9Reflection7ChangedBound a
    · exact certA9Reflection8ChangedBound a
  rootCount_eq_rank_mul_coxeter := by decide +kernel
end ADERootOrbitData
end Lattice
end SRG266
