/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Checks.D10FingerprintEq
import SRG266.Certificates.ADERootOrbits.Checks.D10FingerprintInjective
import SRG266.Certificates.ADERootOrbits.Checks.D10Norm
import SRG266.Certificates.ADERootOrbits.Checks.D10SimpleNeg
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection0Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection0Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection1Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection1Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection2Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection2Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection3Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection3Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection4Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection4Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection5Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection5Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection6Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection6Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection7Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection7Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection8Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection8Image
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection9Pairing
import SRG266.Certificates.ADERootOrbits.Checks.D10Reflection9Image

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

noncomputable def certD10 : ADERootOrbitCertificate (ADEType.D 10) where
  rootCount := 180
  root := certD10Roots
  fingerprint := certD10Fingerprint
  fingerprint_eq := certD10FingerprintEq
  fingerprint_injective := certD10FingerprintInjective
  coordinate_bound := certD10CoordinateBound
  norm_two := certD10Norm
  simpleIndex := certD10Simple
  simple_eq := certD10SimpleCheck
  negIndex := certD10Neg
  neg_eq := certD10NegCheck
  reflectionIndex := certD10Reflect
  reflectionPairing := certD10ReflectPairing
  reflectionPairing_eq := by
    intro i a
    fin_cases i
    · exact certD10Reflection0Pairing a
    · exact certD10Reflection1Pairing a
    · exact certD10Reflection2Pairing a
    · exact certD10Reflection3Pairing a
    · exact certD10Reflection4Pairing a
    · exact certD10Reflection5Pairing a
    · exact certD10Reflection6Pairing a
    · exact certD10Reflection7Pairing a
    · exact certD10Reflection8Pairing a
    · exact certD10Reflection9Pairing a
  reflection_fingerprint := by
    intro i a
    fin_cases i
    · exact certD10Reflection0Fingerprint a
    · exact certD10Reflection1Fingerprint a
    · exact certD10Reflection2Fingerprint a
    · exact certD10Reflection3Fingerprint a
    · exact certD10Reflection4Fingerprint a
    · exact certD10Reflection5Fingerprint a
    · exact certD10Reflection6Fingerprint a
    · exact certD10Reflection7Fingerprint a
    · exact certD10Reflection8Fingerprint a
    · exact certD10Reflection9Fingerprint a
  reflection_changedCoordinate_bound := by
    intro i a
    fin_cases i
    · exact certD10Reflection0ChangedBound a
    · exact certD10Reflection1ChangedBound a
    · exact certD10Reflection2ChangedBound a
    · exact certD10Reflection3ChangedBound a
    · exact certD10Reflection4ChangedBound a
    · exact certD10Reflection5ChangedBound a
    · exact certD10Reflection6ChangedBound a
    · exact certD10Reflection7ChangedBound a
    · exact certD10Reflection8ChangedBound a
    · exact certD10Reflection9ChangedBound a
  rootCount_eq_rank_mul_coxeter := by decide +kernel
end ADERootOrbitData
end Lattice
end SRG266
