/- This file is generated by scripts/generate_ade_root_orbit_certificates.py. -/
import SRG266.Certificates.ADERootOrbits.Checks.E7FingerprintEq
import SRG266.Certificates.ADERootOrbits.Checks.E7FingerprintInjective
import SRG266.Certificates.ADERootOrbits.Checks.E7Norm
import SRG266.Certificates.ADERootOrbits.Checks.E7SimpleNeg
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection0Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection0Image
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection1Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection1Image
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection2Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection2Image
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection3Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection3Image
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection4Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection4Image
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection5Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection5Image
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection6Pairing
import SRG266.Certificates.ADERootOrbits.Checks.E7Reflection6Image

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SRG266
namespace Lattice
namespace ADERootOrbitData

noncomputable def certE7 : ADERootOrbitCertificate (ADEType.E7) where
  rootCount := 126
  root := certE7Roots
  fingerprint := certE7Fingerprint
  fingerprint_eq := certE7FingerprintEq
  fingerprint_injective := certE7FingerprintInjective
  coordinate_bound := certE7CoordinateBound
  norm_two := certE7Norm
  simpleIndex := certE7Simple
  simple_eq := certE7SimpleCheck
  negIndex := certE7Neg
  neg_eq := certE7NegCheck
  reflectionIndex := certE7Reflect
  reflectionPairing := certE7ReflectPairing
  reflectionPairing_eq := by
    intro i a
    fin_cases i
    · exact certE7Reflection0Pairing a
    · exact certE7Reflection1Pairing a
    · exact certE7Reflection2Pairing a
    · exact certE7Reflection3Pairing a
    · exact certE7Reflection4Pairing a
    · exact certE7Reflection5Pairing a
    · exact certE7Reflection6Pairing a
  reflection_fingerprint := by
    intro i a
    fin_cases i
    · exact certE7Reflection0Fingerprint a
    · exact certE7Reflection1Fingerprint a
    · exact certE7Reflection2Fingerprint a
    · exact certE7Reflection3Fingerprint a
    · exact certE7Reflection4Fingerprint a
    · exact certE7Reflection5Fingerprint a
    · exact certE7Reflection6Fingerprint a
  reflection_changedCoordinate_bound := by
    intro i a
    fin_cases i
    · exact certE7Reflection0ChangedBound a
    · exact certE7Reflection1ChangedBound a
    · exact certE7Reflection2ChangedBound a
    · exact certE7Reflection3ChangedBound a
    · exact certE7Reflection4ChangedBound a
    · exact certE7Reflection5ChangedBound a
    · exact certE7Reflection6ChangedBound a
  rootCount_eq_rank_mul_coxeter := by decide +kernel
end ADERootOrbitData
end Lattice
end SRG266
